project:
  type: book

book:
  title: "LIBRO EXAMENES EFA 2023"
  subtitle: ""
  author: "[_Profesor Alberto Bernat_](https://www.linkedin.com/in/albertobernat/)"
  cover-image: EFPA_logo.png
  date: "d-M-yyy"

  chapters:
    - index.qmd
    - intro.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
    cover-image: images/portada_2020.png
  pdf:
    documentclass: scrreprt

editor: visual

