project:
  type: book

book:
  title: "Certificación European Financial Advisor - EFA™   <br> Asociación Europea de Planificación Financiera - EFPA™"
  subtitle: "<br> **Ejercicios y exámenes resueltos**"
  author: "[_**Profesor Alberto Bernat**_](https://www.linkedin.com/in/albertobernat/) <br> Máster en Dirección y Planificación Financiera  <br> Universidad Europea Miguel de Cervantes <br>  Economista (Colegiado nº. 3.685) <br>   Asesor Financiero (EFA nº. 14.672)"
  cover-image: EFPA_logo.png"
  date: "now"

    
  chapters:
    - index.qmd
    - preguntas-frecuentes.qmd
    - part: EJERCICIOS RESUELTOS
      chapters: 
      - M1-test.qmd
      - M2-test.qmd
      - M3-test.qmd
      - M4-test.qmd
      - M5-test.qmd
      - M6-test.qmd
      - M7-test.qmd
      - M8-test.qmd
      - M9-test.qmd
      - M10-test.qmd
    - part: EXÁMENES TEST
      chapters:
      - ano_2021.qmd
      - ano_2020.qmd
      - ano_2019.qmd
      - ano_2018.qmd
      - ano_2017.qmd
      - ano_2016.qmd
    - part: EXÁMENES PRÁCTICA
      chapters:
      - caso-practicos_21.qmd
      - caso-practicos_20.qmd
      - caso-practicos_19.qmd
      - caso-practicos_18.qmd

format:
  html:
    lang: "es"
    title-block-author-single: ""
    theme: [cosmo, style.scss]
    cover-image: images/portada_2020.png
    css: styles.css
  pdf: 
    lang: "es"
    documentclass: scrreprt
    keep-tex: true

editor: visual

