# Módulo 4 {.unnumbered}

## Seguros


1.  ¿Es válido el contrato de seguro sin la existencia de riesgo?:

```{=html}
<!-- -->
```
a)  Siempre.

b)  Nunca.

c)  Dependiendo de si hay o no interés asegurable.

d)  A veces.

<details>

<summary>

</summary>

::: {.FOO .callout-tip appearance="simple"}
La respuesta **correcta es la b**.
:::

</details>

------------------------------------------------------------------------

2.  ¿Qué es el interés asegurado?:

```{=html}
<!-- -->
```
a)  La relación existente entre asegurado y tomador

b)  La probabilidad de ocurrencia de un evento determinado

c)  La relación existente entre el asegurado y el bien expuesto al riesgo

d)  El interés del asegurado en que no se produzca el siniestro

<details>

<summary>

</summary>

::: {.FOO .callout-tip appearance="simple"}
La respuesta **correcta es la c**.

En base a esa relación, un siniestro produce una pérdida económica que el seguro debe compensar.
:::

</details>

------------------------------------------------------------------------

3.  Un interés económico "objetivo" existe en:

```{=html}
<!-- -->
```
a)  Todo tipo de seguros

b)  Solo en lo seguros sobre personas

c)  En los seguros de daños

d)  Solo en los seguros de responsabilidad civil

<details>

<summary>

</summary>

::: {.FOO .callout-tip appearance="simple"}
La respuesta **correcta es la c**.

En los seguros personales el capital asegurado lo decide el tomador- asegurado. En los seguros de responsabilidad civil, la indemnización depende de la importancia y valoración del daño causado. Únicamente en los seguros de daños hay un interés económico objetivo, ya que la suma asegurada debe corresponderse con el valor que objetivamente tienen los bienes.
:::

</details>

------------------------------------------------------------------------

4.  En terminología aseguradora la producción del evento previsto en la póliza y que da lugar al cumplimiento de la principal obligación del asegurador se llama:

```{=html}
<!-- -->
```
a)  Riesgo

b)  Siniestro

c)  Declaración

d)  Ninguna de las anteriores

<details>

<summary>

</summary>

::: {.FOO .callout-tip appearance="simple"}
La respuesta **correcta es la b**.

El término siniestro es ampliamente conocido por los usuarios, especialmente para el ramo del automóvil, donde se suele hacer referencia a siniestro parcial o sinistro total.
:::

</details>

------------------------------------------------------------------------

5.  Para que el seguro de daños pueda cumplir su función indemnizatoria, depende de:

```{=html}
<!-- -->
```
a)  La voluntad del asegurador

b)  La correcta relación entre el valor del interés y la suma asegurada

c)  La tasación del daño

d)  Que la Entidad aseguradora pague rápidamente

<details>

<summary>

</summary>

::: {.FOO .callout-tip appearance="simple"}
La respuesta **correcta es la b**.

Es una función reparadora y compensadora, pero no "enriquecedora". Por ello es necesaria una valoración económica del interés asegurado lo más exacta posible.
:::

</details>

------------------------------------------------------------------------

6.  El contrato por el que se asegure la muerte de una persona de 12 años sería:

```{=html}
<!-- -->
```
a)  Válido

b)  Anulable

c)  Nulo

d)  Rescindible

<details>

<summary>

</summary>

::: {.FOO .callout-tip appearance="simple"}
La respuesta **correcta es la c**.

Está prohibida, legalmente la contratación de seguros de vida, para caso de muerte, sobre menores de 14 años de edad.
:::

</details>

------------------------------------------------------------------------

7.  El cálculo de las primas en los seguros de vida se basa en las bases técnicas. Son elementos principales de éstas:

```{=html}
<!-- -->
```
a)  La suma asegurada

b)  La duración

c)  La intensidad

d)  La mortalidad y el interés técnico

<details>

<summary>

</summary>

::: {.FOO .callout-tip appearance="simple"}
La respuesta **correcta es la d**.

La duración y la intensidad también forman parte de las bases técnicas de los seguros. Sin embargo, en el caso concreto de los seguros de vida, la "mortalidad y el interés técnico" tienen un tratamiento especial y una importancia superior.
:::

</details>

------------------------------------------------------------------------

8.  ¿Qué es un seguro de vida indexado?:

```{=html}
<!-- -->
```
a)  Un seguro con participación en beneficios

b)  Un seguro vinculado a un índice de mortalidad determinado

c)  Un seguro de vida cuyos capitales pueden ser revalorizables.

d)  Un seguro con incremento fijo establecido de antemano

<details>

<summary>

</summary>

::: {.FOO .callout-tip appearance="simple"}
La respuesta **correcta es la c**.

La característica común de este tipo de productos es la existencia de una rentabilidad variable en función de la evolución de un índice (comúnmente bursátil), que aunque deseablemente deben ser revalorizables, también pueden ser depreciables en rendimientos e incluso en patrimonio inicial aportado.
:::

</details>

------------------------------------------------------------------------

9.  El asegurador está obligado al pago de la prestación, salvo que el siniestro haya sido causado con:

```{=html}
<!-- -->
```
a)  Desidia de terceros.

b)  Mala fe del asegurado.

c)  Existencia de infraseguro.

d)  Desinformación del asegurador.

<details>

<summary>

</summary>

::: {.FOO .callout-tip appearance="simple"}
La respuesta **correcta es la b**.

De las cuestiones anteriormente enunciadas, únicamente la mala fe del asegurado permite al asegurador no hacer frente a su obligación de reparar el daño.

La posible negligencia o desidia de terceros no afecta.

El infraseguro si que podría afectar al montante de la prestación, pero en ningún caso la eliminaría.

Es evidente que la desinformación del asegurador, no es nunca responsabilidad del tomador del seguro, ni del beneficiario y por ello nunca debe ser causa que impida el pago de la prestación.
:::

</details>

------------------------------------------------------------------------

10. Un asegurador tiene que ser necesariamente:

```{=html}
<!-- -->
```
a)  Una persona jurídica

b)  Una mutua

c)  Una Sociedad Anónima

d)  Una cooperativa

<details>

<summary>

</summary>

::: {.FOO .callout-tip appearance="simple"}
La respuesta **correcta es la a**.

Es un requisito legal ser persona jurídica. También puede ser mutua, sociedad anónima o cooperativa, pero no de forma obligatoria.
:::

</details>

------------------------------------------------------------------------

11. Cuando el titular de un interés asegurable asume personalmente, y de forma voluntaria y calculada, las consecuencias económicas de un siniestro nos encontramos ante una situación de:

```{=html}
<!-- -->
```
a)  Seguro a través de un asegurador.

b)  Autoseguro.

c)  Sobreseguro.

d)  Infraseguro.

<details>

<summary>

</summary>

::: {.FOO .callout-tip appearance="simple"}
La respuesta **correcta es la b**.

Es una de las formas de afrontar un riesgo por parte del titular del interés asegurable. El sobreseguro y el infraseguro hacen referencia a aspectos de valoración que no afectan a la asunción de las consecuencias económicas de un siniestro.
:::

</details>

------------------------------------------------------------------------

12. El tomador del seguro es:

```{=html}
<!-- -->
```
a)  Las persona sobre la que recaen los beneficios del seguro.

b)  La persona que firma el contrato de seguro asumiendo las obligaciones y derechos derivados de él.

c)  La persona jurídica que asume los riesgos a cambio de una prima.

d)  El titular del interés asegurado.

<details>

<summary>

</summary>

::: {.FOO .callout-tip appearance="simple"}
La respuesta **correcta es la b**.

La respuesta a) se corresponde con la figura del beneficiario. La c) con la figura del asegurador y la d) con la del asegurado.
:::

</details>

------------------------------------------------------------------------

13. La regla proporcional se aplica cuando existe:

```{=html}
<!-- -->
```
a)  Autoseguro.

b)  Sobreseguro.

c)  Infraseguro.

d)  Coaseguro.

<details>

<summary>

</summary>

::: {.FOO .callout-tip appearance="simple"}
La respuesta **correcta es la c**.

El infraseguro y el sobreseguro son consecuencia de una incorrecta valoración del riesgo. La regla proporcional se aplica en caso de infraseguro. Cuando en caso de siniestro la suma asegurada es inferior al valor del interés asegurado, el asegurador sólo indemnizará el daño causado en la misma proporción en la que aquélla cubre el interés asegurado.
:::

</details>

------------------------------------------------------------------------

14. Son seguros de prestación de servicios:

```{=html}
<!-- -->
```
a)  Los seguros de decesos.

b)  Los seguros de responsabilidad civil

c)  Los seguros de daños.

d)  Los seguros de vida.

<details>

<summary>

</summary>

::: {.FOO .callout-tip appearance="simple"}
La respuesta **correcta es la a**.

Los otros tres son, esencialmente, de tipo indemnizatorio.
:::

</details>

------------------------------------------------------------------------

15. El tipo de interés, en los seguros de vida:

```{=html}
<!-- -->
```
a)  Influye, pero sólo en el capital.

b)  No tiene ningún tipo de relevancia.

c)  No influye en la prestación a pagar por parte de la aseguradora

d)  Determina la prima.

<details>

<summary>

</summary>

::: {.FOO .callout-tip appearance="simple"}
La respuesta **correcta es la d**.

La rentabilidad de las inversiones, también denominada interés técnico, consiste en el tipo de interés que las entidades revierten a los asegurados por el rendimiento esperado de la inversión de los fondos acumulados para el pago de las prestaciones, lo que repercute en una menor prima.
:::

</details>

------------------------------------------------------------------------

16. Las entidades que ejerzan su actividad en varios ramos de seguro distintos del de vida, deberán tener el capital o fondo mutual correspondiente:

```{=html}
<!-- -->
```
a)  A la suma de los requeridos para todos los ramos en los que actúe.

b)  Al ramo para el que se exija mayor cuantía.

c)  A un porcentaje adicional del 25% del ramo en el que se exija mayor capital.

d)  A un 85 % si disponen de un régimen de derrama pasiva.

<details>

<summary>

</summary>

::: {.FOO .callout-tip appearance="simple"}
La respuesta **correcta es la b**.

No es necesario disponer de un capital o fondo mutual que acumule los diferentes ramos, tampoco se establecen porcentajes, y el criterio que prevalece es que el capital o fondo mutual lo determina el ramo en el que se exija mayor cuantía.
:::

</details>

------------------------------------------------------------------------

17. Indicar cuál de las siguientes características no es aplicable al contrato de seguro:

```{=html}
<!-- -->
```
a)  Buena fe.

b)  Oneroso.

c)  Aleatorio.

d)  Unilateral.

<details>

<summary>

</summary>

::: {.FOO .callout-tip appearance="simple"}
La respuesta **correcta es la d**.

Es necesaria la intervención de dos partes, tomador y asegurador, y por tanto el acuerdo debe ser bilateral, el resto de características está presente en diferentes tipos de seguros.
:::

</details>

------------------------------------------------------------------------

18. El elemento formal que vincula al asegurador durante 15 días es:

```{=html}
<!-- -->
```
a)  La carta de garantía.

b)  La solicitud de seguro.

c)  La propuesta de seguro.

d)  El boletín de adhesión.

<details>

<summary>

</summary>

::: {.FOO .callout-tip appearance="simple"}
La respuesta **correcta es la c**.

Debido a que así está determinado en la normativa vigente del sector asegurador.
:::

</details>

------------------------------------------------------------------------

19. El seguro de responsabilidad civil tiene por objeto:

```{=html}
<!-- -->
```
a)  Cubrir daños que afecten a bienes propiedad del asegurado.

b)  Resarcir al asegurado de las pérdidas patrimoniales que sufra con ocasión de reclamaciones por daños a terceros.

c)  Cubrir daños que afecten a bienes propiedad del beneficiario.

d)  Cubrir servicios que se necesiten con ocasión de un siniestro.

<details>

<summary>

</summary>

::: {.FOO .callout-tip appearance="simple"}
La respuesta **correcta es la b**.

El seguro de responsabilidad civil protege el patrimonio del asegurado frente a reclamaciones de terceros perjudicados.
:::

</details>

------------------------------------------------------------------------

20. El seguro de vida, para el caso de muerte, estipulado sobre la vida de un tercero (asegurado) requiere:

```{=html}
<!-- -->
```
a)  El consentimiento de la Compañía Aseguradora.

b)  El consentimiento del tomador del seguro.

c)  El consentimiento del titular del interés asegurado.

d)  La autorización del beneficiario.

<details>

<summary>

</summary>

::: {.FOO .callout-tip appearance="simple"}
La respuesta **correcta es la c**.

Es necesario el consentimiento del titular del interés asegurado ("asegurado" - "vida del asegurado"). Es el caso típico del seguro de vida vinculado a la contratación de una hipoteca, en el cual se designa como beneficiaria a la Entidad Bancaria.
:::

</details>

------------------------------------------------------------------------

21. ¿Quién designa al beneficiario en un seguro de vida individual?:

```{=html}
<!-- -->
```
a)  El tomador del seguro.

b)  El asegurado.

c)  La Compañía.

d)  El propio beneficiario.

<details>

<summary>

</summary>

::: {.FOO .callout-tip appearance="simple"}
La respuesta **correcta es la a**.

Es el tomador, como parte contratante, y no el asegurado el que tiene ese derecho.
:::

</details>

------------------------------------------------------------------------

22. ¿Qué entendemos por un seguro de vida referenciado?:

```{=html}
<!-- -->
```
a)  Un seguro de vida sin revalorización.

b)  Un seguro con una rentabilidad variable.

c)  Un seguro cuyas primas están sujetas a incrementos.

d)  Un seguro con participación en beneficios.

<details>

<summary>

</summary>

::: {.FOO .callout-tip appearance="simple"}
La respuesta **correcta es la b**.

La característica típica de estos productos es la existencia de una rentabilidad variable dependiente de la evolución de un índice. Para evitar pérdidas en caso de una caída del índice bursátil normalmente cuentan con un "suelo" de rentabilidad.

Se supone, a modo de ejemplo, que ese "suelo" es de un 110% de la prima pagada.

Eso quiere decir que, pase lo que pase, siempre se percibirá ese porcentaje de lo que se invirtió. Es decir, en este ejemplo, el producto tendrá una rentabilidad, en cualquier caso, de un 10 %.
:::

</details>

------------------------------------------------------------------------

23. Las prestaciones de un seguro de vida, no vinculado a cuestiones laborales, para el caso de supervivencia tienen la consideración de:

```{=html}
<!-- -->
```
a)  Rendimientos del trabajo.

b)  Rendimientos del capital mobiliario.

c)  Rendimientos del capital inmobiliario.

d)  Rendimientos no sujetos.

<details>

<summary>

</summary>

::: {.FOO .callout-tip appearance="simple"}
La respuesta **correcta es la b**.

No serán rendimientos del trabajo y tampoco lo son del capital inmobiliario. A su vez la normativa fiscal española, considera que dichos rendimientos están sujetos a tributación, no son ganancias o pérdidas patrimoniales, y se consideran rendimientos del capital mobiliario, en determinados casos sometidos a reducción del gravamen fiscal según antigüedad de la inversión y otras condiciones vinculadas a las características del seguro en fase de aportaciones y prestaciones.
:::

</details>

------------------------------------------------------------------------

24. La percepción de cantidades por parte de los beneficiarios de un seguro de vida por causa de fallecimiento tributan por el Impuesto sobre Sucesiones y Donaciones cuando:

```{=html}
<!-- -->
```
a)  El beneficiario coincide con el tomador

b)  El beneficiario es distinto del tomador-asegurado

c)  Cuando el beneficiario y el asegurado coinciden

d)  Ninguna de las anteriores.

<details>

<summary>

</summary>

::: {.FOO .callout-tip appearance="simple"}
La respuesta **correcta es la b**.

Para tributar a través del Impuesto sobre Sucesiones y Donaciones es necesario que el tomador y el asegurado sean diferentes. Si el tomador o asegurado es el que percibe el capital, tributa por el IRPF.
:::

</details>

------------------------------------------------------------------------

25. Cuando el beneficiario y el asegurado son personas diferentes, y el primero es una empresa, la prestación en caso de fallecimiento tributa por:

```{=html}
<!-- -->
```
a)  IRPF.

b)  Impuesto sobre Sucesiones y Donaciones

c)  Impuesto de Sociedades

d)  Impuesto sobre Primas de Seguro

<details>

<summary>

</summary>

::: {.FOO .callout-tip appearance="simple"}
La respuesta **correcta es la c**.

La prestación figurará como ingreso del ejercicio fiscal en el Impuesto sobre Sociedades.
:::

</details>

------------------------------------------------------------------------

26. La prestación de un seguro de vida, en caso de fallecimiento, ¿forma parte de la herencia?:

```{=html}
<!-- -->
```
a)  Nunca.

b)  Solo en caso de aceptación por parte del beneficiario.

c)  Solo si el fallecido no ha realizado testamento

d)  Si en caso de que el fallecido (tomador) hubiera designado beneficiario a uno de sus herederos.

<details>

<summary>

</summary>

::: {.FOO .callout-tip appearance="simple"}
La respuesta **correcta es la d**.

Si el beneficiario tiene, además, la condición de "heredero", la cantidad que perciba del seguro se suma al porcentaje que tenga en la herencia.
:::

</details>

------------------------------------------------------------------------

27. La función del Consorcio de Compensación de Seguros es:

```{=html}
<!-- -->
```
a.  La cobertura de riesgos extraordinarios sobre las personas y las cosas.

b.  La cobertura de riesgos ordinarios.

c.  Es una sociedad privada.

d.  Ninguna es correcta.

<details>

<summary>

</summary>

::: {.FOO .callout-tip appearance="simple"}
La respuesta **correcta es la a**.

El **Consorcio compensa los daños producidos a las personas y en los bienes por determinados fenómenos extraordinarios** de la naturaleza y por algunos acontecimientos derivados de determinados hechos de incidencia política o social, a condición de tener suscrita una póliza en alguno o algunos de los ramos respecto de los que la legislación vigente establece la obligación de incluir en sus correspondientes coberturas la garantía de estos riesgos.
:::

</details>

------------------------------------------------------------------------

28. El coaseguro y el reaseguro son técnicas para:

```{=html}
<!-- -->
```
a.  Aumentar el riesgo técnico-asegurador.

b.  Otorgar superiores prestaciones a los asegurados.

c.  De aumentar el número de asegurados.

d.  De distribuir los riesgos.

<details>

<summary>

</summary>

::: {.FOO .callout-tip appearance="simple"}
La respuesta **correcta es la d**.

Si una Compañía aseguradora va a rebasar su capacidad de aceptación de riesgos, para poder seguir atendiendo nuevas peticiones, para seguir vendiendo seguros, para seguir en el mercado recurre a dos técnicas básicas para gestionar el riesgo: Coaseguro y Reaseguro.
:::

</details>

------------------------------------------------------------------------

29. Para que exista una operación de coaseguro, además del abridor, como mínimo debe haber:

```{=html}
<!-- -->
```
a.  Dos aseguradores o más.

b.  Tres aseguradores o más.

c.  Otro asegurador.

d.  Al menos cuatro aseguradores.

<details>

<summary>

</summary>

::: {.FOO .callout-tip appearance="simple"}
La respuesta **correcta es la c**.

Una operación de **coaseguro consiste en repartir un mismo riesgo entre dos o más aseguradores** en la proporción en la que entre ellos determinen a través de un contrato. Lógicamente ante el individuo que contrata el seguro se encuentra una **compañía aseguradora que es quien realiza el contrato de seguro**. Esta compañía es la **abridora** del coaseguro Esta será la que posteriormente reparta con otra u otras los riesgos según tengan acordado.
:::

</details>

------------------------------------------------------------------------

30. En el coaseguro el asegurador es responsable ante el asegurado de:

```{=html}
<!-- -->
```
a.  Una parte del riesgo.

b.  La totalidad del riesgo.

c.  Solo es responsable del riesgo ante otros aseguradores.

d.  No es responsable del riesgo.

<details>

<summary>

</summary>

::: {.FOO .callout-tip appearance="simple"}
La respuesta **correcta es la a**.

En el **coaseguro el asegurador es responsable ante el asegurado de una parte del riesgo**.
:::

</details>

------------------------------------------------------------------------

31. En el reaseguro el asegurador es responsable ante el asegurado de:

```{=html}
<!-- -->
```
a.  Una parte del riesgo.

b.  La totalidad del riesgo.

c.  Solo es responsable del riesgo ante otros aseguradores.

d.  No es responsable del riesgo.

<details>

<summary>

</summary>

::: {.FOO .callout-tip appearance="simple"}
La respuesta **correcta es la b**.

Al contrario que ocurre con el coaseguro, en el **reaseguro el asegurador es responsable ante el asegurado de la totalidad del riesgo**.
:::

</details>

------------------------------------------------------------------------

32. Un Plan de Previsión Asegurado es un:

```{=html}
<!-- -->
```
a.  Seguro de vida-ahorro con las ventajas fiscales de un plan de pensiones.

b.  Seguro Unit Linked.

c.  Seguro de enfermedad.

d.  Plan Individual de Ahorro Sistemático.

<details>

<summary>

</summary>

::: {.FOO .callout-tip appearance="simple"}
La respuesta **correcta es la a**.

Un Plan de Previsión Asegurado es un seguro de vida-ahorro con las ventajas fiscales de un plan de pensiones.
:::

</details>

------------------------------------------------------------------------

33. Un plan de jubilación es:

```{=html}
<!-- -->
```
a.  Un plan de pensiones de aportación definida.

b.  Un plan de pensiones de prestación definida.

c.  Un seguro de vida temporal.

d.  Un seguro de vida-ahorro para caso de supervivencia a la jubilación.

<details>

<summary>

</summary>

::: {.FOO .callout-tip appearance="simple"}
La respuesta **correcta es la d**.

Un plan de jubilación es un seguro de vida-ahorro para caso de supervivencia a la jubilación.
:::

</details>

------------------------------------------------------------------------

34. Un Unit Linked:

```{=html}
<!-- -->
```
a.  No es un seguro de vida-ahorro.

b.  Es un vehículo para invertir que incluye un seguro.

c.  No permite modificaciones en la inversión realizada.

d.  Es un seguro de vida-riesgo.

<details>

<summary>

</summary>

::: {.FOO .callout-tip appearance="simple"}
La respuesta **correcta es la b**.

Un Unit Linked podemos decir que es un vehículo para invertir que incluye un seguro.
:::

</details>

------------------------------------------------------------------------

35. Uno de los siguientes no es un valor garantizado en los seguros de vida-ahorro:

```{=html}
<!-- -->
```
a.  Valor de rescate.

b.  Valor de reducción o capital reducido.

c.  Doble capital en caso de muerte por accidente.

d.  Préstamos o anticipos sobre pólizas.

<details>

<summary>

</summary>

::: {.FOO .callout-tip appearance="simple"}
La respuesta **correcta es la c**.

El doble capital en caso de muerte por accidente no es un valor garantizado en los seguros de vida-ahorro.
:::

</details>

------------------------------------------------------------------------

36. La mayor parte de la prima abonada en un Unit-Linked se dedica a:

```{=html}
<!-- -->
```
a.  Inversión.

b.  Riesgo de fallecimiento.

c.  Reducir impuestos.

d.  Ninguna de las anteriores.

<details>

<summary>

</summary>

::: {.FOO .callout-tip appearance="simple"}
La respuesta **correcta es la a**.

La mayor parte de la prima abonada en un Unit-Linked se dedica a inversión.
:::

</details>

------------------------------------------------------------------------

37. En el valor de rescate antes del siniestro en un seguro de vida-ahorro:

```{=html}
<!-- -->
```
a.  No hay derecho de rescate.

b.  Existe provisión matemática.

c.  No existen valores garantizados.

d.  Es igual al valor de reducción.

<details>

<summary>

</summary>

::: {.FOO .callout-tip appearance="simple"}
La respuesta **correcta es la b**.

En el valor de rescate antes del siniestro en un seguro de vida-ahorro existe provisión matemática.
:::

</details>

------------------------------------------------------------------------

38. La reducción en un seguro de vida-ahorro:

```{=html}
<!-- -->
```
a.  Es cuando la prima pagada va decreciendo su importe.

b.  Consiste en que el tomador deje de pagar la prima y el asegurador proceda a rebajar la suma asegurada.

c.  Consiste en incrementar la suma asegurada.

d.  No puede ser inferior al valor de la provisión matemática.

<details>

<summary>

</summary>

::: {.FOO .callout-tip appearance="simple"}
La respuesta **correcta es la b**.

La **reducción en un seguro de vida-ahorro consiste en que el tomador deje de pagar la prima y el asegurador proceda a rebajar la suma asegurada**.
:::

</details>

------------------------------------------------------------------------

39. En la póliza:

```{=html}
<!-- -->
```
a.  La puede modificar unilateralmente el tomador, previa comunicación al asegurador en tiempo y forma.

b.  No pueden modificarse bajo ningún concepto.

c.  Para modificarse debe cancelarse la póliza y contratar un nuevo seguro.

d.  La puede modificar unilateralmente el asegurado, previa comunicación al asegurador en tiempo y forma.

<details>

<summary>

</summary>

::: {.FOO .callout-tip appearance="simple"}
La respuesta **correcta es la a**.

**El tomador del seguro puede aumentar o disminuir libremente las garantías pactadas, comunicando dichos cambios al asegurador con un mes de antelación al vencimiento**, durante la vigencia de la póliza y coincidiendo con las fechas de vencimiento, por ejemplo ante necesidades que tenga el beneficiario (pago de vivienda, educación de los hijos, próxima jubilación, etc.)
:::

</details>

------------------------------------------------------------------------

40. En el seguro Unit Linked:

```{=html}
<!-- -->
```
a.  Los costes para el inversor son menores que si invirtiera directamente en los fondos.

b.  Los costes para el inversor son los mismos que si invirtiera directamente en los fondos.

c.  Las reestructuraciones de inversiones en fondos tributan fiscalmente.

d.  Los costes para el inversor son mayores para el inversor que si invirtiera directamente en los fondos.

<details>

<summary>

</summary>

::: {.FOO .callout-tip appearance="simple"}
La respuesta **correcta es la d**.

Por el lado de los costes, es importante destacar que **en los Unit Linked una parte de las aportaciones que se realizan va destinada a pagar la prima del seguro de vida, y que ésta aumenta a medida que avanza la edad del asegurado**. Dicho de otra forma, el porcentaje del capital que se destina al seguro es mayor con el paso de los años y el que se destina a inversión, menor, salvo que se aumenten las aportaciones en la medida que se incremente la prima.
:::

</details>

------------------------------------------------------------------------

41. Una de las siguientes afirmaciones es cierta:

```{=html}
<!-- -->
```
a.  El anticipo en un seguro de vida corresponde a un préstamo sobre el capital asegurado cuyo límite es su valor del rescate.

b.  El asegurado es la persona que contrata el seguro con el asegurador firmando la póliza.

c.  Los seguros de vida no pueden ser a prima única.

d.  En los seguros de vida-riesgo no es imprescindible que como garantía básica se cubra el fallecimiento.

<details>

<summary>

</summary>

::: {.FOO .callout-tip appearance="simple"}
La respuesta **correcta es la a**.

El anticipo es un préstamo que el asegurador concede al tomador, en función del derecho que éste tiene sobre la reserva matemática.

El derecho de anticipo tiene como límite el importe de la reserva matemática y se pacta a un tipo de interés igual al que se capitaliza ésta y se liquida a voluntad del tomador, o bien compensando su importe con las cantidades por entregar al beneficiario al producirse las contingencias previstas en la póliza o en caso de rescate.

El derecho de anticipo, al igual que el rescate, se reconoce en el artículo 94 de la Ley de Contrato de Seguro, para todas las modalidades de seguro excepto para aquéllas con un exclusivo componente de riesgo.

Cabe recordar que, **si existe un anticipio sobre la póliza y luego se aplica un rescate, dicho anticipo será descontado cuando se calcule el valor de rescate**.
:::

</details>

------------------------------------------------------------------------
