<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="es" xml:lang="es"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.2.269">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Certificación European Financial Advisor - EFA™  Asociación Europea de Planificación Financiera - EFPA™ - Casos prácticos 2018</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1.6em;
  vertical-align: middle;
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./caso-practicos_19.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 20,
  "language": {
    "search-no-results-text": "Sin resultados",
    "search-matching-documents-text": "documentos encontrados",
    "search-copy-link-title": "Copiar el enlace en la búsqueda",
    "search-hide-matches-text": "Ocultar resultados adicionales",
    "search-more-match-text": "resultado adicional en este documento",
    "search-more-matches-text": "resultados adicionales en este documento",
    "search-clear-button-title": "Borrar",
    "search-detached-cancel-button-title": "Cancelar",
    "search-submit-button-title": "Enviar"
  }
}</script>

  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<link rel="stylesheet" href="styles.css">
</head>

<body class="nav-sidebar floating">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
    <div class="container-fluid d-flex justify-content-between">
      <h1 class="quarto-secondary-nav-title">Casos prácticos 2018</h1>
      <button type="button" class="quarto-btn-toggle btn" aria-label="Show secondary navigation">
        <i class="bi bi-chevron-right"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Certificación European Financial Advisor - EFA™ <br> Asociación Europea de Planificación Financiera - EFPA™</a> 
    </div>
      </div>
      <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
      </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link"><span class="smallcaps">INTRODUCCIÓN</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./preguntas-frecuentes.html" class="sidebar-item-text sidebar-link">Preguntas frecuentes</a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="true">EJERCICIOS RESUELTOS</a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="true">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./M1-test.html" class="sidebar-item-text sidebar-link">Módulo 1</a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./M2-test.html" class="sidebar-item-text sidebar-link">Módulo 2</a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./M3-test.html" class="sidebar-item-text sidebar-link">Módulo 3</a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./M4-test.html" class="sidebar-item-text sidebar-link">Módulo 4</a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./M5-test.html" class="sidebar-item-text sidebar-link">Módulo 5</a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./M6-test.html" class="sidebar-item-text sidebar-link">Módulo 6</a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./M7-test.html" class="sidebar-item-text sidebar-link">Módulo 7</a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./M8-test.html" class="sidebar-item-text sidebar-link">Módulo 8</a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./M9-test.html" class="sidebar-item-text sidebar-link">Módulo 9</a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./M10-test.html" class="sidebar-item-text sidebar-link">Módulo 10</a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" aria-expanded="true">EXÁMENES TEST</a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" aria-expanded="true">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./ano_2021.html" class="sidebar-item-text sidebar-link">Año 2021</a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./ano_2020.html" class="sidebar-item-text sidebar-link">Año 2020</a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./ano_2019.html" class="sidebar-item-text sidebar-link">Año 2019</a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./ano_2018.html" class="sidebar-item-text sidebar-link">Año 2018</a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./ano_2017.html" class="sidebar-item-text sidebar-link">Año 2017</a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./ano_2016.html" class="sidebar-item-text sidebar-link">Año 2016</a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" aria-expanded="true">EXÁMENES PRÁCTICA</a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" aria-expanded="true">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./caso-practicos_21.html" class="sidebar-item-text sidebar-link">Casos prácticos 2021</a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./caso-practicos_20.html" class="sidebar-item-text sidebar-link">Casos prácticos 2020</a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./caso-practicos_19.html" class="sidebar-item-text sidebar-link">Casos prácticos 2019</a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./caso-practicos_18.html" class="sidebar-item-text sidebar-link active">Casos prácticos 2018</a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Tabla de contenidos</h2>
   
  <ul>
  <li><a href="#performance-de-fondos-ii" id="toc-performance-de-fondos-ii" class="nav-link active" data-scroll-target="#performance-de-fondos-ii">Performance de fondos (II)</a></li>
  <li><a href="#capita-market-line-cml" id="toc-capita-market-line-cml" class="nav-link" data-scroll-target="#capita-market-line-cml">Capita Market Line (CML)</a></li>
  <li><a href="#reverse-convertible-cfa" id="toc-reverse-convertible-cfa" class="nav-link" data-scroll-target="#reverse-convertible-cfa">Reverse Convertible (CFA)</a></li>
  <li><a href="#rf-curva-cupón-cero" id="toc-rf-curva-cupón-cero" class="nav-link" data-scroll-target="#rf-curva-cupón-cero">RF curva cupón cero</a></li>
  <li><a href="#rf-precio-y-duración" id="toc-rf-precio-y-duración" class="nav-link" data-scroll-target="#rf-precio-y-duración">RF precio y duración</a></li>
  <li><a href="#performance-de-cartera-i" id="toc-performance-de-cartera-i" class="nav-link" data-scroll-target="#performance-de-cartera-i">Performance de cartera (I)</a></li>
  <li><a href="#fondo-parcialmente-garantizado" id="toc-fondo-parcialmente-garantizado" class="nav-link" data-scroll-target="#fondo-parcialmente-garantizado">Fondo Parcialmente Garantizado</a></li>
  <li><a href="#compensación-de-pérdidas-iic" id="toc-compensación-de-pérdidas-iic" class="nav-link" data-scroll-target="#compensación-de-pérdidas-iic">Compensación de pérdidas (IIC)</a></li>
  <li><a href="#aportaciones-realizadas-a-pp.pp." id="toc-aportaciones-realizadas-a-pp.pp." class="nav-link" data-scroll-target="#aportaciones-realizadas-a-pp.pp.">Aportaciones realizadas a PP.PP.</a></li>
  <li><a href="#renta-fija-valoración" id="toc-renta-fija-valoración" class="nav-link" data-scroll-target="#renta-fija-valoración">Renta Fija (valoración)</a></li>
  <li><a href="#gestión-de-carteras-2020" id="toc-gestión-de-carteras-2020" class="nav-link" data-scroll-target="#gestión-de-carteras-2020">Gestión de carteras (2020)</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title d-none d-lg-block">Casos prácticos 2018</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  

</header>

<section id="performance-de-fondos-ii" class="level2">
<h2 class="anchored" data-anchor-id="performance-de-fondos-ii">Performance de fondos (II)</h2>
<p>Considera la siguiente información:</p>
<table class="table">
<colgroup>
<col style="width: 35%">
<col style="width: 43%">
<col style="width: 7%">
<col style="width: 13%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;"><strong>Fondo</strong></th>
<th style="text-align: center;"><strong>Rentabilidad Acumulada a 3 años</strong></th>
<th style="text-align: center;"><strong>Beta</strong></th>
<th style="text-align: center;"><strong>Volatilidad</strong></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Fondo de Renta Variable ABC</td>
<td style="text-align: center;">53,40%</td>
<td style="text-align: center;">0,96</td>
<td style="text-align: center;">14,32%</td>
</tr>
<tr class="even">
<td style="text-align: left;">Índice de Renta Variable</td>
<td style="text-align: center;">46,91%</td>
<td style="text-align: center;">1</td>
<td style="text-align: center;">12,89%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Fondo de Renta Fija XYZ</td>
<td style="text-align: center;">27,87%</td>
<td style="text-align: center;">1,10</td>
<td style="text-align: center;">8,84%</td>
</tr>
<tr class="even">
<td style="text-align: left;">Índice de Renta Fija</td>
<td style="text-align: center;">24,33%</td>
<td style="text-align: center;">1</td>
<td style="text-align: center;">5,72%</td>
</tr>
</tbody>
</table>
<p>El coeficiente de correlación entre las rentabilidades del Fondo de Renta Variable ABC y del Fondo de Renta Fija XYZ es 0,21.</p>
<p>Formamos una cartera P con el 70% Fondo de Renta Variable ABC y el 30% Fondo de Renta Fija XYZ.</p>
<p><strong>SE PIDE</strong>:</p>
<ol type="a">
<li><p>Calcular el alfa de los Fondos ABC y XYZ.</p></li>
<li><p>Calcular el Tracking Error y el Ratio de Información de los 2 fondos.</p></li>
<li><p>Calcular la volatilidad de la cartera P.</p></li>
</ol>
<details>
<summary>
</summary>
<div class="FOO">
<p><strong>Apartado a</strong></p>
<ul>
<li>En este caso nos proporcionan las rentabilidades acumuladas a 3 años, luego lo primero que hacemos es convertir estas rentabilidades en rentabilidades anuales. Para ello nos planteamos la siguiente equivalencia financiera de tantos,</li>
</ul>
<div class="rmdimportant">
<p><span class="math display">\[\left(1+i\right)^3=\left(1+i_{trianual}\right)\]</span></p>
<ul>
<li>de donde despejamos el tipo efectivo anual <span class="math inline">\(i\)</span>,</li>
</ul>
<p><span class="math display">\[i=\left(1+i_{trianual}\right)^{(1/3)}-1\]</span></p>
</div>
<ul>
<li>si susutituimos y calculamos en la expresión anterior obtendremos las rentabilidades anuales,</li>
</ul>
<p><span class="math display">\[i_{ABC}=\left(1+0,5340\right)^{(1/3)}-1=0,153229(15,33\%)\]</span> <span class="math display">\[i_{I_{RV}}=\left(1+0,4691\right)^{(1/3)}-1=0,13679(13,68\%)\]</span></p>
<p><span class="math display">\[i_{XYZ}=\left(1+0,2787\right)^{(1/3)}-1=0,08539(8,54\%)\]</span></p>
<p><span class="math display">\[i_{I_{RF}}=\left(1+0,2433\right)^{(1/3)}-1=0,07528(7,53\%)\]</span></p>
<ul>
<li>Ahora podemos calcular el alfa de estos fondos como,</li>
</ul>
<div class="rmdnote">
<ul>
<li><strong>Alpha de Jensen</strong></li>
</ul>
<p><span class="math display">\[\alpha_F=R_f-\beta_F\cdot R_{I}\]</span></p>
<p>Donde,</p>
<ul>
<li><p><span class="math inline">\(\alpha_p\)</span>, es el alpha de Jensen del fondo <span class="math inline">\(F\)</span>.</p></li>
<li><p><span class="math inline">\(R_f\)</span>, es la rentabilidad del activo sin riego.</p></li>
<li><p><span class="math inline">\(\beta_F\)</span>, es la beta (sensibilidad a los movimientos del mercado) del fondo <span class="math inline">\(F\)</span>.</p></li>
<li><p><span class="math inline">\(R_I\)</span>, es la rentabilidad esperada del índice <span class="math inline">\(I\)</span>.</p></li>
</ul>
</div>
<ul>
<li>Luego tenemos que para el <strong>Fondo ABC</strong>:</li>
</ul>
<p><span class="math display">\[\alpha_{ABC}=R_{f_{ABC}}-\beta_{ABC}\cdot R_{I_{RV}}\]</span> <span class="math display">\[\alpha_{ABC}=15,33-0,96\cdot 13,68=2,1972\%\]</span></p>
<ul>
<li>y, para el <strong>Fondo XYZ</strong>:</li>
</ul>
<p><span class="math display">\[\alpha_{XYZ}=R_{f_{XYZ}}-\beta_{XYZ}\cdot R_{I_{RF}}\]</span> <span class="math display">\[\alpha_{XYZ}=8,54-1,10\cdot 7,53=0,257\%\]</span></p>
<p><strong>Apartado b</strong></p>
<ul>
<li>En este apartado primero nos piden <strong>calcular el <em>Tracking Error</em></strong>,</li>
</ul>
<div class="rmdnote">
<ul>
<li><strong><em>Tracking Error</em> (o error de tracking)</strong></li>
</ul>
<p><span class="math display">\[TE=\sigma_{\alpha,F}=\sqrt{\sigma_p^2-\beta_p^2\cdot \sigma_F^2}\]</span></p>
<p>Donde,</p>
<ul>
<li><p><span class="math inline">\(\sigma_{\alpha,F}\)</span>, es la desviación típica (volatilidad o riesgo) del alpha de Jensen respecto de la fondo <span class="math inline">\(F\)</span>.</p></li>
<li><p><span class="math inline">\(\sigma_p^2\)</span>, es la varianza del fondo <span class="math inline">\(F\)</span> .</p></li>
<li><p><span class="math inline">\(\beta_p^2\)</span>, es la beta al cuadrado del fondo <span class="math inline">\(F\)</span>.</p></li>
<li><p><span class="math inline">\(\sigma_I\)</span>, es la varianza al cuadrado del Índice <span class="math inline">\(I\)</span> (o <em>benchmark</em>).</p></li>
</ul>
</div>
<ul>
<li>luego, el TE para el fondo ABC será de:</li>
</ul>
<p><span class="math display">\[TE_{ABC}=\sqrt{14,32^2-0,96^2\cdot 12,89^2}=7,21\%\]</span></p>
<ul>
<li>y, para el fondo XYZ será de:</li>
</ul>
<p><span class="math display">\[TE_{XYZ}=\sqrt{8,84^2-1,10^2\cdot 5,72^2}=6,21\%\]</span></p>
<ul>
<li>y, en segundo lugar <strong>calculamos el Ratio de información</strong>:</li>
</ul>
<div class="rmdnote">
<ul>
<li><strong>Ratio de Información</strong></li>
</ul>
<p><span class="math display">\[RI=\frac{\alpha_p}{TE}\]</span></p>
<p>Donde,</p>
<ul>
<li><p><span class="math inline">\(\alpha_p\)</span>, es el alpha de Jensen del fondo <span class="math inline">\(F\)</span>.</p></li>
<li><p><span class="math inline">\(\sigma_{\alpha,F}\)</span>, es la desviación típica (volatilidad o riesgo) del alpha de Jensen respecto del fondo <span class="math inline">\(F\)</span>.</p></li>
</ul>
</div>
<ul>
<li>luego, el RI para el fondo ABC será de:</li>
</ul>
<p><span class="math display">\[RI_{ABC}=\frac{\alpha_{F_{ABC}}}{TE_{ABC}}=\frac{2,1972}{7,21}=0,30\]</span> * y, el RI para el fondo XYZ será de:</p>
<p><span class="math display">\[RI_{XYZ}=\frac{\alpha_{F_{XYZ}}}{TE_{XYZ}}=\frac{0,257}{6,21}=0,041\]</span></p>
<p><strong>Apartado c</strong></p>
<ul>
<li>En este apartado <strong>calculamos la volatilidad de la cartera</strong> como:</li>
</ul>
<div class="rmdnote">
<p>la volatilidad de la cartera en función del coeficiente de correlación:</p>
<p><span class="math display">\[\sigma_p=\sqrt{w_{1}^2\cdot\sigma_1^2+w_2^2\cdot\sigma_2^2+2\cdot w_1\cdot w_2\cdot\rho_{1,2}\cdot\sigma_{1}\cdot\sigma_{2}}\]</span></p>
<p>Donde,</p>
<ul>
<li><p><span class="math inline">\(\sigma_p\)</span>, es la volatilidad (riesgo) de la cartera <span class="math inline">\(p\)</span>.</p></li>
<li><p><span class="math inline">\(w_1\)</span>, es la ponderación (o proporción) del activo <span class="math inline">\(1\)</span> dentro de la cartera <span class="math inline">\(p\)</span>.</p></li>
<li><p><span class="math inline">\(\sigma_1\)</span>, es la varianza del título <span class="math inline">\(1\)</span>.</p></li>
<li><p><span class="math inline">\(w_2\)</span>, es la ponderación (o proporción) del activo <span class="math inline">\(2\)</span> dentro de la cartera <span class="math inline">\(p\)</span>.</p></li>
<li><p><span class="math inline">\(\sigma_2\)</span>, es la varianza del título <span class="math inline">\(2\)</span>.</p></li>
<li><p><span class="math inline">\(\rho_{1,2}\)</span>, es el coeficiente de correlación entre los activos 1 y 2.</p></li>
</ul>
</div>
<ul>
<li>luego bastará con sustituir los datos en la fórmula anterior,</li>
</ul>
<p><span class="math display">\[\sigma_p=\sqrt{0,7^2\cdot14,32^2+0,3^2\cdot8,84^2+2\cdot 0,7\cdot 0,3\cdot0,21\cdot14,32\cdot8,84}\]</span></p>
<ul>
<li>y, calcular:</li>
</ul>
<p><span class="math display">\[\sigma_p=10,89\%\]</span></p>
</div>
</details>
<hr>
</section>
<section id="capita-market-line-cml" class="level2">
<h2 class="anchored" data-anchor-id="capita-market-line-cml">Capita Market Line (CML)</h2>
<p>Considere un mercado con las siguientes características:</p>
<ul>
<li><p><strong>Rentabilidad esperada</strong>: 12%</p></li>
<li><p><strong>Volatilidad</strong>: 15%</p></li>
<li><p><strong>Rentabilidad sin riesgo</strong>: 2,0%</p></li>
</ul>
<p>Si un cliente que considera que el mercado es eficiente, quiere construir una cartera asumiendo una volatilidad del 9%;</p>
<ol type="1">
<li><p>¿Cuál es la rentabilidad máxima que podría obtener?</p></li>
<li><p>¿Cuál es la ponderación de debe darle al activo sin riesgo y a la cartera de mercado?</p></li>
</ol>
<p>Para la parte satélite de su cartera, el cliente ha encontrado una acción de la empresa AAA, que tiene la siguiente línea característica:</p>
<p><span class="math display">\[R(E) _{AAA}  = 1,85\% + (R_{MDO} \cdot 1,35)\]</span></p>
<ol start="3" type="1">
<li>¿Podría determinar si resultaría recomendable incorporar dicha acción a la cartera del cliente?</li>
</ol>
<details>
<summary>
</summary>
<div class="FOO">
<p><strong>Apartado 1</strong></p>
<ul>
<li>En este caso nos piden hallar la <strong>máxima rentabilidad</strong> que se podría obtener <strong>para cada nivel de riesgo deseado</strong>, luego está rentabilidad vendrá dada por la <strong>Capita Market Line (CML)</strong>:</li>
</ul>
<div class="rmdnote">
<p><span class="math display">\[R(E)_{p}=R_f+\left(\frac{E_{MDO}-R_f}{\sigma_{MDO}}\right)\cdot\sigma_p\]</span></p>
<p>Donde,</p>
<ul>
<li><p><span class="math inline">\(R(E)_{p}\)</span>, es la rentabilidad esperada de la cartera <span class="math inline">\(p\)</span>.</p></li>
<li><p><span class="math inline">\(R_f\)</span>, es la rentabilidad del activo sin riego.</p></li>
<li><p><span class="math inline">\(_{MDO}\)</span>, es la rentabilidad esperada de la cartera de mercado.</p></li>
<li><p><span class="math inline">\(\sigma_{MDO}\)</span>, es la volatilidad (o riesgo) de la cartera de mercado.</p></li>
<li><p><span class="math inline">\(\sigma_{AAA}\)</span>, es la la volatilidad (o riesgo) de la cartera <span class="math inline">\(p\)</span>.</p></li>
</ul>
</div>
<ul>
<li>Luego en este caso tenemos que la <strong>rentabilidad esperada de la cartera “p”</strong>, según el CAPM será de:</li>
</ul>
<p><span class="math display">\[R(E)_{AAA}=2\%+\left(\frac{12\%-2\%}{15\%}\right)\cdot  9\%=8\%\]</span></p>
<p><strong>Apartado 2</strong></p>
<ul>
<li>En este caso nos piden la <strong>ponderación del activo libre de riesgo y de la cartera “p”</strong>. Para hallarla bastará con plantear la siguiente ecuación,</li>
</ul>
<p><span class="math display">\[8=(W_1\cdot 2)+[(1-W_1)\cdot 12]\]</span></p>
<ul>
<li>donde tenemos que <strong>resolver</strong> por la ponderación del activo libre de riesgo (W_1),</li>
</ul>
<p><span class="math display">\[8=2\cdot W_1+12-12\cdot W_1\]</span> <span class="math display">\[12W_1-2W_1= 12-8\]</span> <span class="math display">\[10\cdot W_1=4\]</span></p>
<ul>
<li>Luego tenemos que,</li>
</ul>
<p><span class="math display">\[W_1=0,4=40\%\]</span></p>
<ul>
<li>Conocida la ponderación del activo libre de riesgo (W_1) podemos <strong>hallar</strong> fácilmente, por diferencia, <strong>la ponderación de la cartera de mercado (W_2)</strong>:</li>
</ul>
<p><span class="math display">\[W_2=(100\%-40\%)=60\%\]</span></p>
<ul>
<li>donde, el <strong>resultado</strong> es un <strong>40% del patrimonio invertido en el activo libre de riesgo y un 60% invertido en la cartera de mercado</strong>.</li>
</ul>
<p><strong>Apartado 3</strong></p>
<ul>
<li>la <strong>rentabilidad exigida a las acciones de la empresa AAA</strong>, considerando una beta de 1,35 sería:</li>
</ul>
<p><span class="math display">\[R(E)_{K_{AAA}}=2\%+\left(12\%-2\%\right)\cdot  1,35=15,50\%\]</span></p>
<ul>
<li>según la <strong>CML</strong>, la <strong>rentabilidad esperada del AAA</strong> es:</li>
</ul>
<p><span class="math display">\[R(E)_{K_{AAA}}=1,85\%+\left(12\%\cdot  1,35\right)=18,05\%\]</span></p>
<ul>
<li>luego, con estos datos, <strong>la acción de la empresa AAA se encuentra por encima de la CML</strong> con lo que sería recomendable comprarla para poder incorporarla a su cartera ya que según nuestros cálculos (Modelo CAPM) la acción de AAA <strong>se encuentra infravalorada y se espera que su rentabilidad aumente del 15,50% actual al 18,05% objetivo</strong>.</li>
</ul>
</div>
</details>
<hr>
</section>
<section id="reverse-convertible-cfa" class="level2">
<h2 class="anchored" data-anchor-id="reverse-convertible-cfa">Reverse Convertible (CFA)</h2>
<p>Un Reverse Convertible (CFA) sobre las acciones de TECN presenta las siguientes características relevantes:</p>
<ul>
<li><p><strong>Pasivo total inicial (que hay que captar)</strong>: 100 millones de euros.</p></li>
<li><p><strong>Inversión mínima</strong>: 6.000 €.</p></li>
<li><p><strong>Plazo de la inversión</strong>: 30 meses.</p></li>
<li><p><strong>Valor de referencia TECN</strong>.</p></li>
<li><p><strong>Cotización de TECN en la fecha de emisión del CFA</strong>: 36,00 €.</p></li>
<li><p><strong>Remuneración</strong>:</p>
<pre><code>Cupón único, en cualquier caso, de 1.230 €.</code></pre>
<p>Si al vencimiento del CFA, la cotización de TECN está por encima del 90% de su cotización en la fecha de emisión (36 x 90% = 32,40 €), se recupera el importe invertido en efectivo y se cobra el cupón.</p>
<p>Si al vencimiento del CFA la cotización de TECN está por debajo del 90% de su cotización en la fecha de emisión (32,40), no se recupera la inversión en efectivo sino que se perciben acciones de TECN. El número de acciones a percibir por cada 6.000 de inversión es de 185,18 (6.000/32,40). Como no se pueden entregar 0,18 acciones, se abonará el importe residual en efectivo.</p></li>
<li><p><strong>La TAE en depósitos ordinarios para el mismo plazo es del 4,50%</strong>.</p></li>
</ul>
<p><strong>SE PIDE</strong>:</p>
<ol type="a">
<li><p>Explicar la construcción del reverse convertible y calcular la prima de la opción de venta.</p></li>
<li><p>Plantear los posibles escenarios de la rentabilidad obtenida según el precio de TECN a vencimiento.</p></li>
</ol>
<details>
<summary>
</summary>
<div class="FOO">
<p><strong>Apartado a</strong></p>
<ul>
<li><p>Construcción del Producto Estructurado CFA (Reverse Convertible) para un suscriptor de 6.000 euros:</p></li>
<li><p>Depósito a 30 meses VN = 6.000 euros al 4,50% TAE</p></li>
<li><p>Venta de una opción PUT (short put) cuyo subyacente son acciones de TECN con precio de ejercicio 32,40 euros.</p></li>
</ul>
<p><img src="images/nueva.jpg" class="img-fluid"></p>
<ul>
<li>En <strong>t=30</strong> meses:</li>
</ul>
<p><span class="math display">\[I_{deposito}=C_n-C_0=C_n\cdot(1+i)^n-C_0\]</span></p>
<p><span class="math display">\[I_{deposito}=6000\cdot(1+0,045)^{(30/12)}-6000=697,65\]</span></p>
<ul>
<li>En <strong>t=0</strong>:</li>
</ul>
<p>Prima de la venta de la <strong>put = P</strong></p>
<ul>
<li><strong>Valor de la prima en t=30</strong> meses:</li>
</ul>
<p><span class="math display">\[P\cdot(1+0,045)^{(30/12)}\]</span></p>
<ul>
<li>Luego, se tendrá que cumplir que:</li>
</ul>
<p><span class="math display">\[1.230=697,95+P\cdot(1+0,045)^{(30/12)}\]</span></p>
<ul>
<li>de donde, despejamos la prima de la opción put (P):</li>
</ul>
<p><span class="math display">\[P= 476,61\ euros\]</span></p>
<p><strong>Apartado b</strong></p>
<ul>
<li><p><strong>ESCENARIO 1</strong>: Precio de TECN a vencimiento <span class="math inline">\(\geq 32,40\ euros\)</span></p>
<p>Resultado a vencimiento = 1230 + 6000 = 7230 €</p></li>
<li><p>Luego la TAE vendrá dada por:</p></li>
</ul>
<p><span class="math display">\[C_n=C_0\cdot (1+TAE)^n\]</span></p>
<ul>
<li>donde al sustituir y calcular,</li>
</ul>
<p><span class="math display">\[7.230=6.000\cdot (1+TAE)^{\frac{30}{12}}\Rightarrow TAE=7,74\%\]</span></p>
<ul>
<li><strong>ESCENARIO 2</strong>: Precio de TECN a vencimiento <span class="math inline">\(&lt; 32,40\ euros\)</span></li>
</ul>
<p>Resultado a vencimiento = 1230 + 185 acciones de TECN compradas a 32,40 euros</p>
<pre><code>- ESCENARIO 2.1: Precio de TECN a vencimiento = 29,53 euros (punto muerto con intereses)

Resultado a vencimiento = 1230 + 185,18 · 29,53 = 6698,36 euros

Luego la TAE vendrá dada por:</code></pre>
<p><span class="math display">\[C_n=C_0\cdot (1+TAE)^n\]</span></p>
<pre><code>donde al sustituir y calcular,</code></pre>
<p><span class="math display">\[6.698,36=6.000\cdot (1+TAE)^{\frac{30}{12}}\Rightarrow TAE=4,5\%\]</span></p>
<pre><code> - ESCENARIO 2.2: Precio de TECN a vencimiento = 25,76 euros (punto muerto sin intereses)

Resultado a vencimiento = 1230 + 185,18 · 25,76 = 6000 euros

Luego la TAE vendrá dada por:</code></pre>
<p><span class="math display">\[C_n=C_0\cdot (1+TAE)^n\]</span></p>
<pre><code>donde al sustituir y calcular,</code></pre>
<p><span class="math display">\[6.000=6.000\cdot (1+TAE)^{\frac{30}{12}}\Rightarrow TAE=0\%\]</span></p>
<pre><code> - ESCENARIO 2.3: Precio de TECN a vencimiento &lt; 25,76 euros

Resultado a vencimiento &lt; 6000 € (Pérdida de patrimonio) =&gt; TAE &lt; 0%</code></pre>
<p><img src="images/reverse_caso.PNG" class="img-fluid"></p>
</div>
</details>
<hr>
</section>
<section id="rf-curva-cupón-cero" class="level2">
<h2 class="anchored" data-anchor-id="rf-curva-cupón-cero">RF curva cupón cero</h2>
<p>Determinar el precio de un bono cuyas características figuran a continuación:</p>
<table class="table">
<thead>
<tr class="header">
<th style="text-align: left;"><strong>Características:</strong></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Vencimiento: 4 años</td>
</tr>
<tr class="even">
<td style="text-align: left;">Cupón nominal anual: 4%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Amortización a la par: 100%</td>
</tr>
</tbody>
</table>
<p>No se dispone de la TIR de dicha emisión a 4 años, pero si se dispone de las siguientes cotizaciones de bonos de cupón cero emitidos por la misma entidad y con la misma calificación crediticia.</p>
<table class="table">
<thead>
<tr class="header">
<th style="text-align: left;"><strong>Cotizaciones:</strong></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Bonos de cupón cero vto. 1 año: 97.7995%</td>
</tr>
<tr class="even">
<td style="text-align: left;">Bonos de cupón cero vto. 2 años: 95.1814%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Bonos de cupón cero vto. 3 años: 92.0493%</td>
</tr>
<tr class="even">
<td style="text-align: left;">Bonos de cupón cero vto. 4 años: 88.3330%</td>
</tr>
</tbody>
</table>
<p>Una vez obtenido el precio del bono, determinar la TIR de dicha emisión.</p>
<details>
<summary>
</summary>
<div class="FOO">
<p>Para la determinación del precio del bono utilizamos el concepto de ausencia de oportunidades de arbitraje, según el cual el valor de los flujos de caja descontado según los tipos de interés vigentes para cada plazo nos determinará el precio teórico del bono.</p>
<p>En primer lugar debemos determinar el tipo de interés <em>spot</em> vigente para cada uno de los cuatro plazos, a partir del precio de los bonos cupón cero. Para hacerlo empleamos la siguiente fórmula:</p>
<div class="rmdnote">
<p><span class="math display">\[P_ n=P_ 0 (1+{ _{ 0 }{S  }_{n} })^n\]</span></p>
<p>donde,</p>
<ul>
<li><p><span class="math inline">\(P_ n\)</span> = precio de amortización del bono en el momento n (momento de vencimiento)</p></li>
<li><p><span class="math inline">\(P_ 0\)</span> = precio de cotización actual del bono cupón cero emitido por misma entidad y con mismo <em>rating</em> (calificación crediticia)</p></li>
<li><p><span class="math inline">\({ _{ 0 }{S }_{n} }\)</span> = tipo <em>spot</em> entre el momento cero y n (n º de periodos hasta vencimiento)</p></li>
<li><p><span class="math inline">\(n\)</span> = número de periodos transcurridos (entre cero y n)</p></li>
</ul>
</div>
<ul>
<li>Que aplicada para el tipo <strong><em>spot</em></strong> a un año será,</li>
</ul>
<p><span class="math display">\[100=97.7995(1+{ _{ 0 }{ S }_{ 1 } })^{ 1 }\Longrightarrow { _{ 0 }{ S }_{ 1 } }={ \left( \frac { 100 }{ 97.7995 }  \right)  }^{ \frac { 1 }{ 1 }  }-1=0.0225(2.25\%)\]</span></p>
<ul>
<li>Para el tipo <em>spot</em> a dos años,</li>
</ul>
<p><span class="math display">\[100=95.1814(1+{ _{ 0 }{ S }_{ 2 } })^{ 2 }\Longrightarrow { _{ 0 }{ S }_{ 2 } }={ \left( \frac { 100 }{ 95.1814 }  \right)  }^{ \frac { 1 }{ 2 }  }-1=0.0250(2.5\%)\]</span></p>
<ul>
<li>Para el tipo <em>spot</em> a tres años,</li>
</ul>
<p><span class="math display">\[100=92.0493(1+{ _{ 0 }{ S }_{ 3 } })^{ 3 }\Longrightarrow { _{ 0 }{ S }_{ 3 } }={ \left( \frac { 100 }{ 92.0493 }  \right)  }^{ \frac { 1 }{ 3 }  }-1=0.0280(2.8\%)\]</span></p>
<ul>
<li>Y para el tipo <em>spot</em> a cuatro años,</li>
</ul>
<p><span class="math display">\[100=88.3330(1+{ _{ 0 }{ S }_{ 4 } })^{ 4 }\Longrightarrow { _{ 0 }{ S }_{ 4 } }={ \left( \frac { 100 }{ 88.3330 }  \right)  }^{ \frac { 1 }{ 4 }  }-1=0.0315(3.15\%)\]</span></p>
<ul>
<li>El <strong>precio teórico</strong> del bono vendrá dado por la siguiente fórmula,</li>
</ul>
<div class="rmdnote">
<p><span class="math display">\[P_{ 0 }=\sum _{ i=1 }^{ n }{ C_{ i } } (1+{ _{ 0 }{ S }_{ n} })^{ -n }+N(1+{ _{ 0 }{ S }_{ n} })^{ -n }\]</span></p>
<p>donde,</p>
<ul>
<li><p><span class="math inline">\(P_ 0\)</span> = precio teórico actual del bono</p></li>
<li><p><span class="math inline">\(C_i\)</span> = cupóN nominal anual</p></li>
<li><p><span class="math inline">\({ _{ 0 }{S }_{n} }\)</span> = tipo <em>spot</em></p></li>
<li><p><span class="math inline">\(n\)</span> = número de periodos transcurridos</p></li>
<li><p><span class="math inline">\(N\)</span> = nominal que amortizará el bono a vencimiento</p></li>
</ul>
</div>
<p>Que en nuestro caso quedaría,</p>
<p><span class="math display">\[P_ 0=C_1\cdot(1+{ _{ 0 }{S  }_{1} })^{-1}+C_2\cdot(1+{ _{ 0 }{S  }_{2} })^{-2}+C_3\cdot(1+{ _{ 0 }{S  }_{3} })^{-3}+(C_4+N)\cdot (1+{ _{ 0 }{S  }_{4} })^{-4}\]</span></p>
<p>Que al sustituir y calcular nos da un precio de,</p>
<p><span class="math display">\[P_ 0=4\cdot(1.0225)^{-1}+4\cdot(1.0250)^{-2}+4\cdot(1.0280)^{-3}+(104)\cdot(1.0315)^{-4}=103.267 \]</span></p>
<p>Ahora que conocemos el precio del bono, ya podemos calcular su <strong>TIR</strong>,</p>
<p><span class="math display">\[P_{ 0 }=C_{ 1 }\cdot(1+{ TIR })^{ -1 }+C_{ 2 }\cdot(1+{ TIR })^{ -2 }+C_{ 3 }\cdot(1+{ TIR })^{ -3 }+(C_{ 4 }+N)\cdot(1+{ { TIR } })^{ -4 }\]</span></p>
<p>Que al sustituir y calcular nos da un resultado de,</p>
<p><span class="math display">\[103.267=4\cdot(1+{ TIR })^{ -1 }+4\cdot(1+{ TIR })^{ -2 }+4\cdot(1+{ TIR })^{ -3 }+(4+100)\cdot(1+{ { TIR } })^{ -4 }\]</span></p>
<p><span class="math display">\[TIR=0.0311(3.11\%)\]</span></p>
</div>
</details>
<hr>
</section>
<section id="rf-precio-y-duración" class="level2">
<h2 class="anchored" data-anchor-id="rf-precio-y-duración">RF precio y duración</h2>
<p><strong>Dados los siguientes bonos</strong>:</p>
<table class="table">
<colgroup>
<col style="width: 11%">
<col style="width: 15%">
<col style="width: 26%">
<col style="width: 11%">
<col style="width: 12%">
<col style="width: 22%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: center;">Bono</th>
<th style="text-align: center;">Cupón Anual</th>
<th style="text-align: center;">Vencimiento (años)</th>
<th style="text-align: center;">TIR</th>
<th style="text-align: center;">Precio</th>
<th style="text-align: center;">Duración Corregida</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">A</td>
<td style="text-align: center;">0,0%</td>
<td style="text-align: center;">10</td>
<td style="text-align: center;">6%</td>
<td style="text-align: center;">-</td>
<td style="text-align: center;">-</td>
</tr>
<tr class="even">
<td style="text-align: center;">B</td>
<td style="text-align: center;">3,0%</td>
<td style="text-align: center;">3</td>
<td style="text-align: center;">3%</td>
<td style="text-align: center;">-</td>
<td style="text-align: center;">-</td>
</tr>
<tr class="odd">
<td style="text-align: center;">C</td>
<td style="text-align: center;">5,0%</td>
<td style="text-align: center;">2</td>
<td style="text-align: center;">2%</td>
<td style="text-align: center;">-</td>
<td style="text-align: center;">-</td>
</tr>
</tbody>
</table>
<p>Y sabiendo que todos los bonos se amortizan al 100% al vencimiento de los mismos.</p>
<p><strong>Se pide</strong>:</p>
<ol type="1">
<li><p>Rellene las casillas en blanco (precio y duración corregida).</p></li>
<li><p>¿Cuál será el nuevo precio aproximado que experimentara el bono B, si los tipos de interés aumentan en 50 p.b.?</p></li>
</ol>
<details>
<summary>
</summary>
<div class="FOO">
<p><strong>Pregunta 1</strong>: Para calcular el precio de un bono aplicamos la siguiente fórmula,</p>
<div class="rmdnote">
<p><span class="math display">\[P_0=\sum_{ t=1}^{ n}\frac{F_t}{(1+TIR)^{t}}\]</span></p>
<p>donde,</p>
<ul>
<li><p><span class="math inline">\(P_0\)</span>, es el precio entero de un bono o valor actual del mismo (<span class="math inline">\(V_0\)</span>).</p></li>
<li><p><span class="math inline">\(F_t\)</span>, Flujos a percibir por la tenencia de un bono (cupón y principal).</p></li>
<li><p><span class="math inline">\(TIR\)</span>, es la Tasa Interna de Rendimiento (o Rentabilidad).</p></li>
<li><p><span class="math inline">\(t\)</span>, es el tiempo.</p></li>
</ul>
</div>
<p>Y, <strong>para el cálculo de la Duración corregida primero hemos de calcular la Duración de Macaulay (o simplemente Duración)</strong>. Que viene dada por la siguiente expresión:</p>
<div class="rmdnote">
<p><span class="math display">\[D=\frac{\sum_{t=1}^{n}\frac{F_t\cdot t}{\left(1+TIR\right)^t}}{P}\]</span></p>
<p>donde,</p>
<ul>
<li><p><span class="math inline">\(D\)</span>, Duración de Macaulay.</p></li>
<li><p><span class="math inline">\(F_t\)</span>, Flujos a percibir por la tenencia de un bono (cupón y principal).</p></li>
<li><p><span class="math inline">\(P\)</span>, es el precio entero de un bono o valor actual del mismo (<span class="math inline">\(V_0\)</span>).</p></li>
<li><p><span class="math inline">\(TIR\)</span>, es la Tasa Interna de Rendimiento (o Rentabilidad).</p></li>
<li><p><span class="math inline">\(t\)</span>, es el tiempo.</p></li>
</ul>
</div>
<p>Por tanto, conocida la Duración de Macaulay (o simplemente Duración) ya podemos calcular la Duración corregida a partir de la siguiente expresión:</p>
<div class="rmdnote">
<p><span class="math display">\[D_{corregida}=\frac{Duracion\,de\, Macaulay}{\left(1+TIR\right)}=\frac{D}{\left(1+TIR\right)} \]</span></p>
<p>donde,</p>
<ul>
<li><p><span class="math inline">\(D_{corregida}\)</span>, será la Duración corregida.</p></li>
<li><p><span class="math inline">\(D\)</span>, Duración de Macaulay.</p></li>
<li><p><span class="math inline">\(TIR\)</span>, es la Tasa Interna de Rendimiento (o Rentabilidad).</p></li>
</ul>
</div>
<p><br></p>
<ul>
<li>Para el <strong>Bono A</strong> (notesé que este es un bono cupón cero) tenemos que su precio será,</li>
</ul>
<p><span class="math display">\[P_{A,0}=\frac{F_t}{(1+TIR)^{t}}=\frac{100}{(1+0.06)^{10}}=55.83947769\]</span> La Duración de Macaulay, para un bono del tipo cupón cero, la duración coincide con el plazo hasta su vencimiento (10 años en este caso). Luego,</p>
<p><span class="math display">\[D_A=10\,años\]</span> Nota: sin embargo, para un bono clásico parte de su valor actual se deriva de la corriente de los flujos de caja habidos antes de su vencimiento, lo que hace que su duración sea menor que el plazo hasta su vencimiento.</p>
<p>Y, finalmente, la Duración corregida del bono A será,</p>
<p><span class="math display">\[D_{corregida,A}=\frac{D}{\left(1+TIR\right)}=\frac{10}{(1+0.06)}=9.4339\]</span></p>
<p><br></p>
<ul>
<li>Para el <strong>Bono B</strong> (notesé que este es un bono clásico) tenemos que su precio será,</li>
</ul>
<p><span class="math display">\[P_{0,B}=\frac{3}{(1+0.03)^{1}}+\frac{3}{(1+0.03)^{2}}+\frac{103}{(1+0.03)^{3}}=100\]</span> La Duración de Macaulay,</p>
<p><span class="math display">\[D_{0,B}=\frac{1\cdot\left(\frac{3}{(1+0.03)^{1}}\right)+2\cdot\left(\frac{3}{(1+0.03)^{2}}\right)+3\cdot\left(\frac{103}{(1+0.03)^{3}}\right)}{100}=\frac{291.3469696}{100}=2.913469696\]</span></p>
<p>Y, finalmente, la Duración corregida del bono B será,</p>
<p><span class="math display">\[D_{corregida,B}=\frac{D_B}{\left(1+TIR\right)}=\frac{2.913469696}{(1+0.03)}=2.828611355\]</span></p>
<p><br></p>
<ul>
<li>Para el <strong>Bono C</strong> (notesé que este es un bono clásico al igual que el B) tenemos que su precio será,</li>
</ul>
<p><span class="math display">\[P_{0,C}=\frac{5}{(1+0.02)^{1}}+\frac{102}{(1+0.05)^{2}}=105.8246828\]</span></p>
<p>La Duración de Macaulay,</p>
<p><span class="math display">\[D_{C}=\frac{1\cdot\left(\frac{5}{(1+0.02)^{1}}\right)+2\cdot \left(\frac{105}{(1+0.02)^{2}}\right)}{105.8246828}=\frac{206.7474048}{105.8246828}=1.953678474\]</span></p>
<p>Y, finalmente, la Duración corregida del bono B será,</p>
<p><span class="math display">\[D_{corregida,C}=\frac{D_C}{\left(1+TIR\right)}=\frac{2.913469696}{(1+0.02)}=1.915371053\]</span></p>
<p>Luego, la tabla quedaría como sigue:</p>
<table class="table">
<colgroup>
<col style="width: 11%">
<col style="width: 15%">
<col style="width: 26%">
<col style="width: 11%">
<col style="width: 12%">
<col style="width: 22%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: center;">Bono</th>
<th style="text-align: center;">Cupón Anual</th>
<th style="text-align: center;">Vencimiento (años)</th>
<th style="text-align: center;">TIR</th>
<th style="text-align: center;">Precio (euros)</th>
<th style="text-align: center;">Duración Corregida (años)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">A</td>
<td style="text-align: center;">0,0%</td>
<td style="text-align: center;">10</td>
<td style="text-align: center;">6%</td>
<td style="text-align: center;">55,83</td>
<td style="text-align: center;">9,43</td>
</tr>
<tr class="even">
<td style="text-align: center;">B</td>
<td style="text-align: center;">3,0%</td>
<td style="text-align: center;">3</td>
<td style="text-align: center;">3%</td>
<td style="text-align: center;">100,00</td>
<td style="text-align: center;">2,82</td>
</tr>
<tr class="odd">
<td style="text-align: center;">C</td>
<td style="text-align: center;">5,0%</td>
<td style="text-align: center;">2</td>
<td style="text-align: center;">2%</td>
<td style="text-align: center;">105,82</td>
<td style="text-align: center;">1,91</td>
</tr>
</tbody>
</table>
<p><strong>Pregunta 2</strong>: Para estimar el efecto en precio ante variaciones en la TIR (tipos de interés) utilizamos la siguiente fórmula,</p>
<div class="rmdnote">
<p><span class="math display">\[\frac{\Delta P}{P}\simeq   \left(-D_{corregida}\right)\cdot\Delta TIR\]</span></p>
</div>
<p>Luego, si sustituimos la <span class="math inline">\(D_{corregida,B}=2.82\)</span> y la <span class="math inline">\(\Delta TIR=0.50\%\)</span> tenemos que:</p>
<p><span class="math display">\[\frac{\Delta P_B}{P_B}\simeq-2.828611355\cdot0.5\%=-1.414305\]</span></p>
<p>Entonces, de cumplirse este alza en los tipos de interés, el precio final del bono se estima que caería hasta el:</p>
<p><span class="math display">\[P_{f,B}=P_{0,B}-\frac{\Delta P_B}{P_B}=100-1.414305=98.585694(98.59\%)\]</span></p>
<p><a href="https://www.albertobernat.com/1488-2/">Puedes encontrar más información de cómo resolver este tipo de ejercicios con la Calculadora Financiera pinchando en este enlace</a></p>
</div>
</details>
<hr>
</section>
<section id="performance-de-cartera-i" class="level2">
<h2 class="anchored" data-anchor-id="performance-de-cartera-i">Performance de cartera (I)</h2>
<p>Se dispone de la siguiente información relativa a dos acciones, A y B:</p>
<p><br></p>
<table class="table">
<colgroup>
<col style="width: 12%">
<col style="width: 13%">
<col style="width: 18%">
<col style="width: 35%">
<col style="width: 20%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: center;">Activo</th>
<th style="text-align: center;">Peso (%)</th>
<th style="text-align: center;">Volatilidad (%)</th>
<th style="text-align: center;">Rentabilidad esperada (%)</th>
<th style="text-align: center;">Correlación</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">A</td>
<td style="text-align: center;">80</td>
<td style="text-align: center;">23</td>
<td style="text-align: center;">12</td>
<td style="text-align: center;">0.45</td>
</tr>
<tr class="even">
<td style="text-align: center;">B</td>
<td style="text-align: center;">20</td>
<td style="text-align: center;">15</td>
<td style="text-align: center;">7</td>
<td style="text-align: center;"></td>
</tr>
</tbody>
</table>
<p><br></p>
<p><strong>Se pide</strong>:</p>
<ol type="1">
<li><p>Rentabilidad de la cartera formada por A y B.</p></li>
<li><p>Volatilidad de la cartera formada por A y B.</p></li>
<li><p>Cartera de mínima varianza.</p></li>
</ol>
<details>
<summary>
</summary>
<div class="FOO">
<p>Llamaremos p a la cartera formada por los activos A y B.</p>
<p>Calculamos la rentabilidad de dicha cartera con la siguiente fórmula:</p>
<p><span class="math display">\[{ E }_{ p }={ w }_{ A }\cdot { R }_{ A }+{ w }_{ B }\cdot { R }_{ B }\]</span></p>
<p><span class="math display">\[E_p=0.8\cdot0.12+0.2\cdot0.07=0.11(11\%)\]</span></p>
<p>Calculamos la volatilidad:</p>
<p><span class="math display">\[\sigma _{p}=\sqrt{w_{1}^{2}\sigma_{1}^{2}+(1-w_{1})^{2}\sigma_{2}^{2}+2w_{1}(1-w_{1})\rho _{1,2}\sigma _{1}\sigma _{2}}\]</span> <span class="math display">\[\sigma_p=\sqrt{0.8^2\cdot0.23^2+0.2^2\cdot0.15^2+2\cdot0.8\cdot0.2\cdot0.45\cdot0.23\cdot0.15}=0.1993088(19.93\%)\]</span></p>
<p>Cálculo de la cartera de mínima varianza. Se trata de calcular los pesos para cada activo que hacen que la volatilidad de la cartera sea la mínima posible dados unos niveles de volatilidad y correlación para los 2 activos que forman la cartera.</p>
<p><span class="math display">\[{ { w }_{ A }^{ * }=\frac { { \sigma  }_{ B }^{ 2 }-{ \rho  }_{ 1,2 }{ \sigma  }_{ A }{ \sigma  }_{ B } }{ { \sigma  }_{ A }^{ 2 }+{ \sigma  }_{ B }^{ 2 }-2{ \rho  }_{ 1,2 }{ \sigma  }_{ A }{ \sigma  }_{ B } }  }\]</span></p>
<p><span class="math display">\[w_{ A }^{ * }=\frac{0.15^2-0.45\cdot0.23\cdot0.15}{0.23^2+0.15^2-2\cdot0.45\cdot0.23\cdot0.15}=0.1572717(15.72\%)\]</span> <span class="math display">\[w_{ B }=(1-w_{ A }^{ * })=(1-0.1572717)=0.8427283(84.27\%)\]</span></p>
</div>
</details>
<hr>
</section>
<section id="fondo-parcialmente-garantizado" class="level2">
<h2 class="anchored" data-anchor-id="fondo-parcialmente-garantizado">Fondo Parcialmente Garantizado</h2>
<p>Suponemos que un inversor decide invertir 30.000 euros en un fondo parcialmente garantizado, que le ofrece una participación en la subida punto a punto del IBEX35 a vencimiento, sobre una referencia inicial de dicho índice de 8.000 puntos.</p>
<p><br></p>
<table class="table">
<colgroup>
<col style="width: 100%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;"><strong>Se observa lo siguiente:</strong></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Cotización actual del IBEX35: 8.154,60 puntos.</td>
</tr>
<tr class="even">
<td style="text-align: left;">Vencimiento del fondo: 3 años, sin ventanas temporales de liquidez.</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Tipo de interés anualizado a 3 años: 3,60%.</td>
</tr>
<tr class="even">
<td style="text-align: left;">Comisiones de gestión, administración y custodia y otros gastos durante 3 años: 734,96 euros.</td>
</tr>
<tr class="odd">
<td style="text-align: left;">La prima unitaria de la opción tiene un precio de 1.500 euros por cada 8.000 euros de nominal.</td>
</tr>
</tbody>
</table>
<p><br></p>
<p><strong>Se pide</strong>:</p>
<ol type="1">
<li><p>¿Cuáles son los elementos integrantes en este fondo garantizado y en qué consiste la función de cada uno?</p></li>
<li><p>Calcular el nivel de participación en la subida punto a punto del IBEX35 a vencimiento, suponiendo que el cliente gozará de una garantía sobre el patrimonio inicial a vencimiento del 95%.</p></li>
<li><p>Si el cliente quisiese obtener un 100% de participación en la subida punto a punto del IBEX35, ¿qué garantía sobre el patrimonio inicial se le podrá ofrecer a vencimiento?</p></li>
</ol>
<details>
<summary>
</summary>
<div class="FOO">
<p><strong>Pregunta 1</strong>: Renta Fija, opciones, comisiones y gastos. Las opciones son <strong><em>call plain vanilla</em></strong> y la renta Fija son <strong>bonos cupón cero</strong>.</p>
<p><strong>Pregunta 2</strong>. Para poder garantizar un 95% del patrimonio a vencimiento:</p>
<p>Hemos dicho que se trata de un bono cupón cero, empleando la siguiente fórmula, calculamos el precio del bono en el momento actual (<span class="math inline">\({ P }_{ 0 }\)</span>). Así sabremos el precio al que cotiza el bono en el momento de compra y la cantidad que reembolsamos a vencimiento.</p>
<p><span class="math display">\[{ P }_{ 0 }=\frac { N }{ { (1+r) }^{ n } } =\quad \frac { 95\% }{ { (1+0.036) }^{ 3 } } =\frac { 0.95 }{ { 1.036 }^{ 3 } } =85.4367\]</span></p>
<p>La Renta Fija que compramos hoy (<span class="math inline">\({ P }_{ 0 }\)</span>), nos cuesta un <span class="math inline">\(85.4367\%\)</span> sobre una inversión inicial (<span class="math inline">\(I\)</span>) de 30.000 euros. Esto es, <strong>25,631.01 euros</strong>. Siendo la cantidad que reembolsamos a vencimiento <span class="math inline">\({C}_{3}\)</span>, del <span class="math inline">\(95\)</span>% sobre una inversión inicial (<span class="math inline">\(I\)</span>) de 30.000 euros. Esto es, <strong>28,500.00 euros</strong>.</p>
<p>El gasto en renta fija será de:</p>
<p><span class="math display">\[G_{rf}=\frac{85.4367}{100}\cdot30000=25631.01\]</span></p>
<p>Bien, llegados a este punto ya sabemos que, con las condiciones de mercado que nos dice, podemos garantizar al inversor un reembolso de 28,500,00 euros a vencimiento (3 años), invirtiendo 25,631.01 euros en un activo de Renta Fija (bono cupón cero). Es decir, que de los 30,000.00 euros iniciales ya tenemos comprometidos 25,631.01 euros con la compra del bono. Ahora, tendremos que descontar también las “comisiones de gestión, administración y custodia, y otros gastos durante los 3 años” que durar? la operación. Que son de 734.96 euros.</p>
<p>Por tanto, el dinero disponible para compra de las opciones call plain vanilla será:</p>
<p><span class="math display">\[Dd = 30000.00 - 25631.01 - 734.96 \]</span></p>
<p>Sabemos de cuanto dinero disponemos para la compra de opciones, y también sabemos que la prima unitaria de la opcion tiene un precio de 1,500.00 euros por cada 8,000.00 euros de nominal. Lo que haremos será plantear una regla de tres simple que nos permita calcular una participación del 100% en la subida del IBEX35.</p>
<p><span class="math display">\[\begin{bmatrix} 1500\Longleftrightarrow 8000 \\ x_1\Longleftrightarrow 30000\\ \end{bmatrix}\]</span></p>
<p>donde,</p>
<p><span class="math display">\[x_1 = \frac{(1500\cdot30000) }{ 8000}=5625\]</span></p>
<p>Luego hace falta 5,625.00 euros para dar una participación del 100% en la subida del IBEX35.</p>
<p>De modo que si sólo tenemos 3.634,04 euros disponible para comprar opciones, podremos dar una subida de:</p>
<p><span class="math display">\[\begin{bmatrix} 5625\Longleftrightarrow 100 \\ 3634.04\Longleftrightarrow x_2\\ \end{bmatrix}\]</span></p>
<p>donde,</p>
<p><span class="math display">\[x_2 = \frac{(3634.04\cdot100) }{ 5625}=64.60516\]</span></p>
<p>Luego el <strong>nivel de participación ser? del 64,61%</strong> a vencimiento sobre la subida punto a punto del IBEX35, suponiendo que el cliente gozará de una garantá sobre el patrimonio inicial a vencimiento del 95%.</p>
<p><strong>Pregunta 3</strong>. Para poder ofrecer al cliente un nivel de participación del 100% a sobre la subida punto a punto del IBEX35:</p>
<p>En la pregunta 2 hemos dicho que para hacer para dar una participación del 100%, sería necesario comprar opciones por importe de 5,625.00 euros que sobre una inversión inicial de 30,000.00 euros:</p>
<p><span class="math display">\[P_{100}=\left(\frac{5625}{30000}\right)\cdot100=18.75\%\]</span></p>
<p>Ahora sabemos que tenemos comprometidos un <span class="math inline">\(18.75\%\)</span> de nuestros recursos solamente con la compra de las opciones que nos permiten ofrecer al inversor un nivel de participación del 100% a vencimiento, sobre la subida punto a punto del IBEX35.</p>
<p>Lo siguiente es calcular los gastos aparejados a la operación como son:las comisiones de gestión; administración; y custodia. Así como los otros gastos a los que habrá que hacer frente durante los 3 años que dure la operación. Estos gastos los expresaremos en porcentaje sobre el total de la inversión, como hemos hecho en el apartado anterior con las coberturas.</p>
<p><span class="math display">\[\%_{gastos}=\left(\frac{734.96}{30000}\right)\cdot100=2.45\%\]</span></p>
<p>En este punto ya conocemos <strong>todos los gastos necesarios</strong> para comprar un nivel de participación del 100% a 3 años sobre la subida punto a punto del IBEX35, por tanto vamos a ver de cuanto dinero disponemos para comprar el activo de Renta Fija (bono cupón cero) que necesitamos:</p>
<p><span class="math display">\[NB = I - x_1 - G \]</span> donde,</p>
<p><span class="math display">\[NB = 30000 - 5625 - 734.96= 23640.04\]</span></p>
<p>Este resultado (NB), nos está indicando cuanto dinero podemos invertir hoy en Fija. Que si lo capitalizamos (valor final), al tipo de interés anualizado a 3 años, nos dará el importe en euros que percibiremos a vencimiento.</p>
<p>Esto es,</p>
<p><span class="math display">\[{ C }_{ 3 }={ C }_{ 0 }\cdot { (1+i) }^{ n }=23.640,04\cdot{ (1+0,036) }^{ 3 }=26286.18\]</span></p>
<p>Ahora que conocemos el importe del reembolso a vencimiento, ya podemos calcular cuanto representa sobre la inversión inicial. Es decir, la garantía sobre el patrimonio inicial:</p>
<p><span class="math display">\[G_{pi}=\frac{C_3}{I}\cdot10=\frac{26286.18}{30000}\cdot100=87.6206\%\]</span></p>
<p>Luego, si el cliente quisiera obtener un 100% de participación en la subida punto a punto del IBEX-35, la garantía sobre el patrimonio inicial que se le podría ofrecer a vencimiento sería de <span class="math inline">\(87.6206\%\)</span></p>
</div>
</details>
<hr>
</section>
<section id="compensación-de-pérdidas-iic" class="level2">
<h2 class="anchored" data-anchor-id="compensación-de-pérdidas-iic">Compensación de pérdidas (IIC)</h2>
<p><br></p>
<p>Un contribuyente compra el 1 de octubre de 200x-2, 1.000 participaciones a 15 euros cada una. El 11 de octubre de 200x-2 se transmiten las participaciones por 14.100 euros. El 12 de octubre de 200x-2 se compran 1.000 participaciones, de las mismas características a las primeras, por 14.500 euros. El 2 de junio de 200x transmite las últimas 1.000 participaciones por 20.000 euros.</p>
<p><br></p>
<p><strong>Se pide</strong>:</p>
<ol type="1">
<li><p>Calcule la ganancia/pérdida patrimonial del período impositivo 200x-2.</p></li>
<li><p>Determine en que período impositivo podrían ser objeto de compensación la ganancia/pérdida patrimonial del punto anterior.</p></li>
</ol>
<details>
<summary>
</summary>
<div class="FOO">
<p><strong>1ª venta 200x-2</strong></p>
<ul>
<li><p>Valor de transmisión 11/10/200x-2: 14.100</p></li>
<li><p>Valor de adquisición 1/10/200x-2: 15.000</p></li>
<li><p>Pérdida patrimonial: -900</p></li>
</ul>
<p>Por aplicación de la norma anti-cómputo, la totalidad de las pérdidas obtenidas no podrían ser objeto de compensación en ese período impositivo.</p>
<p><br></p>
<p><strong>2ª venta 200x</strong></p>
<ul>
<li><p>Valor de transmisión 2/06/200x: 20.000</p></li>
<li><p>Valor de adquisición 12/10/200x-2: 14.500</p></li>
<li><p>Ganancia patrimonial: 5.500</p></li>
</ul>
<p>Al haberse transmitido todas las participaciones que fueron recompradas, las pérdidas generadas en el ejercicio 200x-2 (900 euros) que no fueron compensadas ese año podrán ser objeto de compensación en la declaración del IRPF de 200x con las ganancias obtenidas en este ejercicio que también formen parte de la base del ahorro (con los 5.500 euros).</p>
</div>
</details>
<hr>
</section>
<section id="aportaciones-realizadas-a-pp.pp." class="level2">
<h2 class="anchored" data-anchor-id="aportaciones-realizadas-a-pp.pp.">Aportaciones realizadas a PP.PP.</h2>
<p>Un contribuyente muestra los siguientes datos:</p>
<p><br></p>
<table class="table">
<colgroup>
<col style="width: 100%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;"><strong>Datos:</strong></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Edad: 30 años</td>
</tr>
<tr class="even">
<td style="text-align: left;">Situación familiar: soltero y sin hijos.</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Rentas netas del trabajo: 20.000 euros.</td>
</tr>
<tr class="even">
<td style="text-align: left;">Abre el 1/1/200x un plan de pensiones individual (PPI)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Aportaciones al PPI: 5.000 euros, a lo largo del año.</td>
</tr>
<tr class="even">
<td style="text-align: left;">En su empresa le han aportado este año: 3.000 euros al plan de pensiones de empleo (PPE).</td>
</tr>
</tbody>
</table>
<p><br></p>
<p><strong>Se pide</strong>:</p>
<ol type="1">
<li><p>Calcule el límite de aportación anual al conjunto de los Planes de Pensiones.</p></li>
<li><p>En el caso de existir excesos de aportación no reducidos, ¿cuál será el plazo máximo en el que se podrá aplicar tal reducción?</p></li>
</ol>
<details>
<summary>
</summary>
<div class="FOO">
<p>Por tanto:</p>
<table class="table">
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: center;">Con plan de pensiones</th>
<th style="text-align: center;">Sin plan de pensiones</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Rentas del trabajo</td>
<td style="text-align: center;">20.000</td>
<td style="text-align: center;">20.000</td>
</tr>
<tr class="even">
<td style="text-align: left;">Base imponible</td>
<td style="text-align: center;">20.000</td>
<td style="text-align: center;">20.000</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Aportaciones PPI</td>
<td style="text-align: center;">6.000</td>
<td style="text-align: center;">-</td>
</tr>
<tr class="even">
<td style="text-align: left;">Base liquidable</td>
<td style="text-align: center;">14.000</td>
<td style="text-align: center;">20.000</td>
</tr>
<tr class="odd">
<td style="text-align: left;">IRPF aprox. a pagar 2017</td>
<td style="text-align: center;">1.670,60</td>
<td style="text-align: center;">3.161,35</td>
</tr>
</tbody>
</table>
<p>Cumple con el límite financiero de aportación de 8.000 euros, pero sólo puede disfrutar de beneficio fiscal por 6.000 euros (el 30% de sus rentas netas del trabajo). No obstante, por el exceso no reducido podrá disfrutar del beneficio fiscal correspondiente en los siguientes 5 ejercicios**.</p>
<p><strong>Normativa</strong>:</p>
<p>Las aportaciones realizadas al plan de pensiones individual dan derecho a reducir la base imponible general del IRPF limitadas por la cuantía menor de:</p>
<ul>
<li><p>El 30% de la suma de los rendimientos netos del trabajo personal y de actividades económicas percibidos en el ejercicio</p></li>
<li><p>8.000 euros anuales</p></li>
</ul>
<p>Si se acredita un grado de minusvalía física o sensorial igual o superior al 65% o psíquica igual o superior al 33% se eleva el máximo de aportación con ventaja fiscal hasta 24.250€.</p>
<p>La aportación financiera máxima que se puede realizar al conjunto de planes de pensiones individuales (PPI), planes de pensiones de empleo (PPE), planes de previsión asegurados (PPA), mutualidades de previsión social (MPS), planes de previsión social empresarial (PPSE) y seguros de dependencia (SD) es de 8.000 € (24.250 € en caso de discapacitados).</p>
<p><strong>Particularidades</strong>:</p>
<p>El límite de reducción del IRPF es conjunto para todas las aportaciones a planes de pensiones individuales (PPI), planes de pensiones de empleo (PPE), planes de previsión asegurados (PPA), mutualidades de previsión social (MPS), planes de previsión social empresarial (PPSE) y seguros de dependencia (SD).</p>
<p>Hay un límite de reducción adicional de 2.500 euros si el plan de pensiones es a favor del cónyuge, siempre que éste no obtenga rendimientos netos del trabajo ni de actividades económicas, o los obtenga en una cuantía inferior a 8.000 €.</p>
<p>Los excesos de aportación no reducidos se pueden aplicar en los 5 años siguientes. De modo particular, tras la jubilación existe la posibilidad de seguir realizando aportaciones para la cobertura de la jubilación, siempre que el contribuyente no haya cobrado el plan de pensiones por esa contingencia.</p>
<p>A partir de 1 de Enero de 2015 se flexibilizó la posibilidad de disponer de los derechos consolidados correspondientes a aportaciones y contribuciones a sistemas de previsión social, que podrán hacerse efectivos, además de en los supuestos tasados de enfermedad grave y desempleo de larga duración, una vez que hayan transcurrido 10 años desde que las aportaciones tuvieron lugar.</p>
<p>No obstante, los derechos consolidados existentes a 31 de diciembre de 2015 sólo podrán hacerse efectivos a partir del 1 de enero de 2025, en los términos establecidos reglamentariamente.</p>
</div>
</details>
<hr>
</section>
<section id="renta-fija-valoración" class="level2">
<h2 class="anchored" data-anchor-id="renta-fija-valoración">Renta Fija (valoración)</h2>
<p>Calcular el precio entero, cupón corrido, precio ex cupón, duración, duración corregida y sensibilidad del siguiente activo de renta fija:</p>
<ul>
<li><p>Fecha valor actual: 28-2-2005</p></li>
<li><p>Vencimiento: 3,5 años.</p></li>
<li><p>Fecha de pago de cupones: 28 de agosto de 2005, 2006, 2007 y 2008</p></li>
<li><p>Cupón nominal anual: 5,00%</p></li>
<li><p>Amortización: A la par por 1.000 €</p></li>
<li><p>Fecha de amortización: 28-8-2008</p></li>
<li><p>TIR actual: 2,90%</p></li>
</ul>
<p>Se pide:</p>
<ol type="1">
<li><p>Determinar el precio entero, cupón corrido y precio ex cupón.</p></li>
<li><p>Calcular la duración, duración corregida y la sensibilidad.</p></li>
<li><p>Estimar a través de la sensibilidad el precio entero del bono con una nueva TIR del 3,25% y con una nueva TIR del 2,80%.</p></li>
<li><p>Comprobar los resultados y aproximación de dichas estimaciones, contrastándolas con los precios reales del bono con la TIR de 3,25% y 2,80%.</p></li>
</ol>
<details>
<summary>
</summary>
<div class="FOO">
<ol type="1">
<li>Determinar el precio entero, cupón corrido y precio excupón</li>
</ol>
<p><strong>Cupón corrido</strong></p>
<p><span class="math display">\[CC= 50 \cdot \frac{184}{365} = 25,205\]</span></p>
<p><strong>Precio entero</strong></p>
<p><span class="math display">\[P_0=\frac{50}{1,029^{\frac{181}{365}}}+\frac{50}{1,029^{\frac{546}{365}}}+\frac{50}{1,029^{\frac{911}{365}}}+\frac{1050}{1,029^{\frac{1277}{365}}}=1.093,82\]</span></p>
<p><strong>Cotización o precio excupón</strong></p>
<p><span class="math display">\[P_{0,\ Ex}= 1.093,82 – 25,205 = 1.068,618\]</span></p>
<ol start="2" type="1">
<li>Calcular la duración, duración corregida y la sensibilidad</li>
</ol>
<p>Duración:</p>
<p><img src="images/dur.png" class="img-fluid"></p>
<p><strong>Duración corregida o modificada</strong>:</p>
<p><span class="math display">\[DM = \frac{D} {(1+TIR)} = \frac{3,233} {1,029}   = 3,142\]</span></p>
<p><strong>Sensibilidad</strong></p>
<p><span class="math display">\[S = DM \cdot \frac{P}{100} = 3,142 \cdot 1.093,82 = 34,366\]</span></p>
<ol start="3" type="1">
<li>Estimar a través de la sensibilidad el precio entero del bono con una nueva TIR del 3,25% y con una nueva TIR del 2,80%</li>
</ol>
<ul>
<li><strong>Con la TIR en 3,25%</strong></li>
</ul>
<p><span class="math display">\[\Delta P/P = -DM \cdot \Delta i \cdot 100 = -3,142 \cdot (0,0325-0,029) \cdot 100 = -1,099\%\]</span></p>
<p><strong>Nuevo Precio estimado: 1.081,798 euros</strong></p>
<p><span class="math display">\[\Delta P/P = -DM \cdot \Delta i \cdot P = -3,142 \cdot (0,0325-0,029) \cdot 1.093,82 = -12,028\]</span> <strong>Nuevo Precio estimado: 1.081,792 euros</strong></p>
<ul>
<li><strong>Con la TIR en 2,80%</strong></li>
</ul>
<p><span class="math display">\[\Delta P/P = -DM \cdot \Delta i \cdot 100 = -3,142 \cdot (0,028-0,029) \cdot 100 = -0,3142\%\]</span></p>
<p><strong>Nuevo Precio estimado: 1.097,256</strong></p>
<p><span class="math display">\[\Delta P/P = -DM \cdot \Delta i \cdot 100 = -3,142 \cdot (0,028-0,029) \cdot 1.093,82 = 3,436\]</span></p>
<p><strong>Nuevo Precio estimado: 1.097,256</strong></p>
<p>Puede verse como las aproximaciones son mejores cuánto más pequeñas son las variaciones de la TIR.</p>
<ol start="4" type="1">
<li>Comprobar los resultados y aproximación de dichas estimaciones, contrastándolas con los precios reales del bono con la TIR de 3,25% y 2,80%.</li>
</ol>
<ul>
<li><strong>Precio con TIR al 3,25%</strong></li>
</ul>
<p><strong>Precio entero</strong></p>
<p><span class="math display">\[P_0=\frac{50}{1,0325^{\frac{181}{365}}}+\frac{50}{1,0325^{\frac{546}{365}}}+\frac{50}{1,0325^{\frac{911}{365}}}+\frac{1050}{1,0325^{\frac{1277}{365}}}=1.081,885\]</span></p>
<p><strong>Diferencia absoluta precio</strong></p>
<p><span class="math display">\[Dif.= 1.081,885 - 1.093,82 = -11,935 =&gt; Error: 12,028 – 11,935 = 0,093\]</span> Sobreestimamos la caída.</p>
<p><strong>Diferencia porcentual precio</strong></p>
<p><span class="math display">\[Dif. \%= 1.081,885 - \frac {1.093,82}  {1.093,82} = -1,091 \% =&gt; Error: 1,099\% - 1,091 \% =
0,008 \%\]</span> Sobreestimamos la caída.</p>
<ul>
<li><strong>Precio con TIR al 2,80%</strong></li>
</ul>
<p><strong>Precio entero</strong></p>
<p><span class="math display">\[P_0=\frac{50}{1,028^{\frac{181}{365}}}+\frac{50}{1,028^{\frac{546}{365}}}+\frac{50}{1,028^{\frac{911}{365}}}+\frac{1050}{1,028^{\frac{1277}{365}}}=1.097,267\]</span></p>
<p><strong>Diferencia absoluta precio</strong></p>
<p><span class="math display">\[Dif. = 1.097,267 - 1.093,82 = 3,447 =&gt; Error: 3,436 – 3,447 = -0,011\]</span> Infraestimamos la subida.</p>
<p><strong>Diferencia porcentual precio</strong></p>
<p><span class="math display">\[Dif. \%= 1.097,267 - \frac {1.093,82}  {1.093,82} = 0,315\% =&gt; Error: 0,3142\% - 0,315\% = - 0,008\%\]</span></p>
<p>Infraestimamos la subida.</p>
</div>
</details>
<hr>
</section>
<section id="gestión-de-carteras-2020" class="level2">
<h2 class="anchored" data-anchor-id="gestión-de-carteras-2020">Gestión de carteras (2020)</h2>
<p>El departamento de análisis de una Agencia de Valores estima que, para el próximo año, las rentabilidades esperadas de dos activos A y B serán del 16% y del 22%, con unas volatilidades respectivas del 17% y del 24%. Si la correlación entre ambos activos es de 0,6.</p>
<p>Se pide:</p>
<ol type="1">
<li><p>La rentabilidad esperada de una cartera formada por un 60% del título A y un 40% del título B será:</p></li>
<li><p>La volatilidad de la cartera es:</p></li>
<li><p>La cartera formada con los títulos A y B que ofrece la máxima rentabilidad esperada posible es:</p></li>
<li><p>La cartera formada con los títulos A y B que permite obtener el mínimo riesgo posible es…</p></li>
<li><p>Considerando dos títulos con volatilidades positivas, ¿es posible formar una cartera de volatilidad nula?</p></li>
<li><p>El coeficiente beta es un parámetro que se usa para medir…</p></li>
<li><p>Un activo se denomina defensivo cuando…</p></li>
</ol>
<details>
<summary>
</summary>
<div class="FOO">



<ol type="1">
<li>La rentabilidad esperada de una cartera formada por un 60% del título A y un 40% del título B será:</li>
</ol>
<p><span class="math display">\[E_p=w_1\cdot E_1+w_2\cdot E_2+...+w_n\cdot E_n\]</span></p>
<p>Donde,</p>
<ul>
<li><p><span class="math inline">\(E_p\)</span>, es la rentabilidad esperada de la cartera.</p></li>
<li><p><span class="math inline">\(w_n\)</span>, es la ponderación (o proporción) del activo <span class="math inline">\(n\)</span> dentro de la cartera.</p></li>
<li><p><span class="math inline">\(E_n\)</span>, es rentabilidad esperada del activo <span class="math inline">\(n\)</span>.</p></li>
</ul>
<p><br></p>
<p><span class="math display">\[E_p=0.60\cdot 0.16+0.40 \cdot 0.22\]</span></p>
<p><span class="math display">\[E_p=0.184(18.40\%)\]</span></p>
<hr>
<ol start="2" type="1">
<li>La volatilidad de la cartera, la podemos escribir en función del coeficiente de correlación (ya que este es el dato de relación entre los activos A y B de que disponemos):</li>
</ol>
<p><span class="math display">\[\sigma_p=\sqrt{w_{1}^2\cdot\sigma_1^2+w_2^2\cdot\sigma_2^2+2\cdot w_1\cdot w_2\cdot\rho_{1,2}\cdot\sigma_{1}\cdot\sigma_{2}}\]</span> Donde,</p>
<ul>
<li><p><span class="math inline">\(\sigma_p\)</span>, es la volatilidad (riesgo) de la cartera <span class="math inline">\(p\)</span>.</p></li>
<li><p><span class="math inline">\(w_1\)</span>, es la ponderación (o proporción) del activo <span class="math inline">\(1\)</span> dentro de la cartera <span class="math inline">\(p\)</span>.</p></li>
<li><p><span class="math inline">\(\sigma_1^2\)</span>, es la varianza del título <span class="math inline">\(1\)</span>.</p></li>
<li><p><span class="math inline">\(w_2\)</span>, es la ponderación (o proporción) del activo <span class="math inline">\(2\)</span> dentro de la cartera <span class="math inline">\(p\)</span>.</p></li>
<li><p><span class="math inline">\(\sigma_2^2\)</span>, es la varianza del título <span class="math inline">\(2\)</span>.</p></li>
<li><p><span class="math inline">\(\rho_{1,2}\)</span>, es el coeficiente de correlación entre los activos 1 y 2.</p></li>
</ul>
<p><br></p>
<p><span class="math display">\[\sigma_p=\sqrt{0.6^2\cdot 0.17^2+0.4^2\cdot 0.24^2+2\cdot 0.6\cdot \:0.4\cdot 0.6\cdot 0.17\cdot 0.24}\]</span></p>
<p><span class="math display">\[\sigma_p=0.17711(17.71\%)\]</span></p>
<hr>
<ol start="3" type="1">
<li>La cartera formada con los títulos A y B que ofrece la máxima rentabilidad esperada posible es:</li>
</ol>
<p><strong>Un 0% en A y un 100% en B</strong>, ya que la rentabilidad esperada de A es 17%, mientras que la de B es 24%, y por ese motivo una cartera que tenga el 100% de activo de B es la máxima rentabilidad esperada.</p>
<hr>
<ol start="4" type="1">
<li>La cartera formada con los títulos A y B que permite obtener el mínimo riesgo posible es:</li>
</ol>
<ul>
<li><p>Para calcular la composición de la cartera de mínimo riesgo se aplica el siguiente proceso:</p>
<ul>
<li>Se trata de <strong>calcular los pesos para cada activo que hacen que la volatilidad de la cartera sea la mínima posible</strong>, dados unos niveles de volatilidad y correlación para los 2 activos que forman la cartera. Luego calculamos la <strong>composición de la cartera de mínimo riesgo</strong> empleando la siguiente expresión:</li>
</ul></li>
</ul>
<p><strong>Composición de la cartera de mínimo riesgo</strong></p>
<p><span class="math display">\[{ { w }_{ A }=\frac { { \sigma  }_{ B }^{ 2 }-{ \rho  }_{ 1,2 }{ \sigma  }_{ A }{ \sigma  }_{ B } }{ { \sigma  }_{ A }^{ 2 }+{ \sigma  }_{ B }^{ 2 }-2{ \rho  }_{ 1,2 }{ \sigma  }_{ A }{ \sigma  }_{ B } }  }\]</span></p>
<p>y,</p>
<p><span class="math display">\[w_{ B }=(1-w_{ A })\]</span></p>
<p>Donde,</p>
<ul>
<li><p><span class="math inline">\({ w }_{ A }\)</span>, es la ponderación (o proporción) del activo <span class="math inline">\(A\)</span> dentro de la cartera de mínimo riesgo.</p></li>
<li><p><span class="math inline">\({ w }_{ B }\)</span>, es la ponderación (o proporción) del activo <span class="math inline">\(B\)</span> dentro de la cartera de mínimo riesgo.</p></li>
<li><p><span class="math inline">\(\sigma_A^2\)</span>, es la varianza del título <span class="math inline">\(A\)</span>.</p></li>
<li><p><span class="math inline">\(\sigma_B^2\)</span>, es la varianza del título <span class="math inline">\(B\)</span>.</p></li>
<li><p><span class="math inline">\(\rho_{A,B}\)</span>, es el coeficiente de correlación entre los activos A y B.</p></li>
</ul>
<p>Así, al sustituir y calcular tenemos que</p>
<p><span class="math display">\[w_{ A }=\frac{0.24^2-0.6\cdot 0.17\cdot 0.24}{0.17^2+0.24^2-2\cdot 0.6\cdot 0.17\cdot 0.24}=0.88225(\approx 88.23\%)\]</span> <br></p>
<p><span class="math display">\[{ w }_{ B }=(1-w_{ A }^{ * })=(1-0.88225)=0.11774(11.77\%)\]</span></p>
<hr>
<ol start="5" type="1">
<li>Considerando dos títulos con volatilidades positivas, ¿es posible formar una cartera de volatilidad nula?</li>
</ol>
<p><strong>Cartera de mínimo riesgo (correlación <span class="math inline">\(\rho=-1\)</span>)</strong></p>
<p><span class="math display">\[\sigma_p=|w_1\cdot\sigma_1-w_2\cdot\sigma_2|\]</span></p>
<p>Donde,</p>
<ul>
<li><p><span class="math inline">\(\sigma_p\)</span>, es la volatilidad (riesgo) de la cartera <span class="math inline">\(p\)</span>.</p></li>
<li><p><span class="math inline">\(w_1\)</span>, es la ponderación (o proporción) del activo <span class="math inline">\(1\)</span> dentro de la cartera <span class="math inline">\(p\)</span>.</p></li>
<li><p><span class="math inline">\(\sigma_1\)</span>, es la varianza del título <span class="math inline">\(1\)</span>.</p></li>
<li><p><span class="math inline">\(w_2\)</span>, es la ponderación (o proporción) del activo <span class="math inline">\(2\)</span> dentro de la cartera <span class="math inline">\(p\)</span>.</p></li>
<li><p><span class="math inline">\(\sigma_2\)</span>, es la varianza del título <span class="math inline">\(2\)</span>.</p></li>
</ul>
<p><span class="math display">\[w_1=\frac{\sigma_{2}}{\sigma_1+ \sigma_2 }\]</span></p>
<p><span class="math display">\[w_2=\frac{\sigma_{1}}{\sigma_1+ \sigma_2 }\]</span></p>
<p>Donde,</p>
<ul>
<li><p><span class="math inline">\(w_1\)</span>, es la ponderación (o proporción) del activo <span class="math inline">\(1\)</span> dentro de la cartera <span class="math inline">\(p\)</span>.</p></li>
<li><p><span class="math inline">\(w_2\)</span>, es la ponderación (o proporción) del activo <span class="math inline">\(2\)</span> dentro de la cartera <span class="math inline">\(p\)</span>.</p></li>
<li><p><span class="math inline">\(\sigma_1\)</span>, es la varianza del título <span class="math inline">\(1\)</span>.</p></li>
<li><p><span class="math inline">\(\sigma_2\)</span>, es la varianza del título <span class="math inline">\(2\)</span>.</p></li>
</ul>
<p>Si la correlación entre ambos títulos es perfectamente negativa (<span class="math inline">\(\rho=-1\)</span>), querrá decir que el comportamiento del rendimiento de cada activo es opuesto al del otro.</p>
<p>Aunque este es un caso que difícilmente se dará en la práctica su utilidad teórica es grande. Por rtanto, la diversificación seleccionando activos con coeficientes de correlación negativos permite reducir el riesgo de una cartera, e incluso anularlo.</p>
<hr>
<ol start="6" type="1">
<li>El coeficiente beta es un parámetro que se usa para medir <strong>el riesgo sistemático.</strong></li>
</ol>
<ul>
<li><strong>Beta de un activo</strong></li>
</ul>
<p><span class="math display">\[\beta_{i,m}=\frac{\sigma_{i,m}}{\sigma_m^2}=\frac{\sigma_i}{\sigma_m}\cdot\rho_{i,m}\]</span></p>
<p>Donde,</p>
<ul>
<li><p><span class="math inline">\(\beta_{p, m}\)</span>, es la beta del activo <span class="math inline">\(i\)</span> respecto del mercado <span class="math inline">\(m\)</span>.</p></li>
<li><p><span class="math inline">\(\sigma_{i,m}\)</span>, es la covarianza entre las rentabilidades del activo <span class="math inline">\(i\)</span> y el mercado <span class="math inline">\(m\)</span>.</p></li>
<li><p><span class="math inline">\(\sigma_m^2\)</span>, es la varianza del mercado <span class="math inline">\(m\)</span>.</p></li>
<li><p><span class="math inline">\(\sigma_i\)</span>, es la volatilidad del activo <span class="math inline">\(i\)</span>.</p></li>
<li><p><span class="math inline">\(\sigma_m\)</span>, es la volatilidad del mercado <span class="math inline">\(m\)</span>.</p></li>
<li><p><span class="math inline">\(\rho_{i,m}\)</span>, es el coeficiente de correlación entre el activo <span class="math inline">\(i\)</span> y el mercado <span class="math inline">\(m\)</span>.</p></li>
</ul>
<p>El coeficiente beta del activo i representa la variación que, por término medio, experimenta la rentabilidad del activo i respecto a una variación unitaria en la rentabilidad del índice de referencia (o mercado).</p>
<ul>
<li><strong>Beta de una cartera</strong></li>
</ul>
<p><span class="math display">\[\beta_{p, m}=w_1\cdot\beta_1+w_2\cdot\beta_2+...+w_n\cdot\beta_n\]</span></p>
<p>Donde,</p>
<ul>
<li><p><span class="math inline">\(\beta_{p, m}\)</span>, es la beta de la cartera (o fondo) <span class="math inline">\(p\)</span> respecto del mercado <span class="math inline">\(m\)</span>.</p></li>
<li><p><span class="math inline">\(w_n\)</span>, es la ponderación del activo <span class="math inline">\(n\)</span> dentro de la de cartera de activos <span class="math inline">\(p\)</span>.</p></li>
<li><p><span class="math inline">\(\beta_n\)</span>, es la beta del activo <span class="math inline">\(n\)</span>.</p></li>
</ul>
<p>La Beta de una cartera es el nivel de relación que existe entre el rendimiento de nuestra cartera y el mercado, expresado en un índice. Para el caso de las acciones, en España, se podría tomar como ejemplo el IBEX-35.</p>
<hr>
<ol start="7" type="1">
<li>Un activo se denomina defensivo cuando <strong>su coeficiente beta está entre -1 y 1.</strong></li>
</ol>
<ul>
<li><p>La Beta es un <strong>indicador de riesgo</strong> que refleja la sensibilidad de una acción a las fluctuaciones <strong>del mercado</strong>.</p>
<ul>
<li><p>Con una <strong>beta superior a uno</strong>, la acción tenderá a magnificar (al alza o a la baja) el movimiento del mercado (se suele hablar entonces de “valor <strong>agresivo</strong>”).</p></li>
<li><p>Con una <strong>beta inferior a uno</strong>, la acción tenderá a recoger sólo parcialmente los movimientos del mercado y se habla entonces de “valor <strong>defensivo</strong>”.</p></li>
</ul></li>
</ul>


</div></details></section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copiado");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copiado");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./caso-practicos_19.html" class="pagination-link">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text">Casos prácticos 2019</span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
  </div>
</nav>
</div> <!-- /content -->



</body></html>