<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="es" xml:lang="es"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.2.269">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Certificación European Financial Advisor - EFA™  Asociación Europea de Planificación Financiera - EFPA™ - Casos prácticos 2019</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1.6em;
  vertical-align: middle;
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./caso-practicos_18.html" rel="next">
<link href="./caso-practicos_20.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 20,
  "language": {
    "search-no-results-text": "Sin resultados",
    "search-matching-documents-text": "documentos encontrados",
    "search-copy-link-title": "Copiar el enlace en la búsqueda",
    "search-hide-matches-text": "Ocultar resultados adicionales",
    "search-more-match-text": "resultado adicional en este documento",
    "search-more-matches-text": "resultados adicionales en este documento",
    "search-clear-button-title": "Borrar",
    "search-detached-cancel-button-title": "Cancelar",
    "search-submit-button-title": "Enviar"
  }
}</script>

  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<link rel="stylesheet" href="styles.css">
</head>

<body class="nav-sidebar floating">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
    <div class="container-fluid d-flex justify-content-between">
      <h1 class="quarto-secondary-nav-title">Casos prácticos 2019</h1>
      <button type="button" class="quarto-btn-toggle btn" aria-label="Show secondary navigation">
        <i class="bi bi-chevron-right"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Certificación European Financial Advisor - EFA™ <br> Asociación Europea de Planificación Financiera - EFPA™</a> 
    </div>
      </div>
      <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
      </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link"><span class="smallcaps">INTRODUCCIÓN</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./preguntas-frecuentes.html" class="sidebar-item-text sidebar-link">Preguntas frecuentes</a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="true">EJERCICIOS RESUELTOS</a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="true">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./M1-test.html" class="sidebar-item-text sidebar-link">Módulo 1</a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./M2-test.html" class="sidebar-item-text sidebar-link">Módulo 2</a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./M3-test.html" class="sidebar-item-text sidebar-link">Módulo 3</a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./M4-test.html" class="sidebar-item-text sidebar-link">Módulo 4</a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./M5-test.html" class="sidebar-item-text sidebar-link">Módulo 5</a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./M6-test.html" class="sidebar-item-text sidebar-link">Módulo 6</a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./M7-test.html" class="sidebar-item-text sidebar-link">Módulo 7</a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./M8-test.html" class="sidebar-item-text sidebar-link">Módulo 8</a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./M9-test.html" class="sidebar-item-text sidebar-link">Módulo 9</a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./M10-test.html" class="sidebar-item-text sidebar-link">Módulo 10</a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" aria-expanded="true">EXÁMENES TEST</a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" aria-expanded="true">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./ano_2021.html" class="sidebar-item-text sidebar-link">Año 2021</a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./ano_2020.html" class="sidebar-item-text sidebar-link">Año 2020</a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./ano_2019.html" class="sidebar-item-text sidebar-link">Año 2019</a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./ano_2018.html" class="sidebar-item-text sidebar-link">Año 2018</a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./ano_2017.html" class="sidebar-item-text sidebar-link">Año 2017</a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./ano_2016.html" class="sidebar-item-text sidebar-link">Año 2016</a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" aria-expanded="true">EXÁMENES PRÁCTICA</a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" aria-expanded="true">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./caso-practicos_21.html" class="sidebar-item-text sidebar-link">Casos prácticos 2021</a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./caso-practicos_20.html" class="sidebar-item-text sidebar-link">Casos prácticos 2020</a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./caso-practicos_19.html" class="sidebar-item-text sidebar-link active">Casos prácticos 2019</a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./caso-practicos_18.html" class="sidebar-item-text sidebar-link">Casos prácticos 2018</a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Tabla de contenidos</h2>
   
  <ul>
  <li><a href="#cobertura-con-opciones" id="toc-cobertura-con-opciones" class="nav-link active" data-scroll-target="#cobertura-con-opciones">Cobertura con opciones</a></li>
  <li><a href="#características-de-renta-fija" id="toc-características-de-renta-fija" class="nav-link" data-scroll-target="#características-de-renta-fija">Características de renta Fija</a></li>
  <li><a href="#especulación-con-futuros" id="toc-especulación-con-futuros" class="nav-link" data-scroll-target="#especulación-con-futuros">Especulación con futuros</a></li>
  <li><a href="#cobertura-con-futuros-euro-stoxx-50" id="toc-cobertura-con-futuros-euro-stoxx-50" class="nav-link" data-scroll-target="#cobertura-con-futuros-euro-stoxx-50">Cobertura con futuros (Euro Stoxx 50)</a></li>
  <li><a href="#características-de-una-cartera-ii" id="toc-características-de-una-cartera-ii" class="nav-link" data-scroll-target="#características-de-una-cartera-ii">Características de una cartera (II)</a></li>
  <li><a href="#ratios-bursátiles-ii" id="toc-ratios-bursátiles-ii" class="nav-link" data-scroll-target="#ratios-bursátiles-ii">Ratios bursátiles (II)</a></li>
  <li><a href="#ratio-de-sharpe" id="toc-ratio-de-sharpe" class="nav-link" data-scroll-target="#ratio-de-sharpe">Ratio de Sharpe</a></li>
  <li><a href="#cartera-de-renta-fija" id="toc-cartera-de-renta-fija" class="nav-link" data-scroll-target="#cartera-de-renta-fija">Cartera de Renta Fija</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title d-none d-lg-block">Casos prácticos 2019</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  

</header>

<section id="cobertura-con-opciones" class="level2">
<h2 class="anchored" data-anchor-id="cobertura-con-opciones">Cobertura con opciones</h2>
<p>Un inversor decide proteger su cartera comprada de renta variable indexada al IBEX-35 ya que estima que éste último puede registrar caídas en los próximos días. El valor efectivo de la cartera en el momento de la cobertura es de 10.560.000€.</p>
<p>Las <strong>cotizaciones</strong> que observa actualmente en mercado son las siguientes:</p>
<ul>
<li><p>Cotización del IBEX-35: 8.396,4 puntos</p></li>
<li><p>Cotización del Contrato del Futuro del IBEX: 8.386 puntos</p></li>
<li><p>Cotización del Contrato del Futuro sobre el Mini-IBEX: 8.380 puntos</p></li>
</ul>
<p><strong>Datos</strong> a tener en cuenta (datos correspondientes a los últimos 3 meses):</p>
<ul>
<li><p>Coeficiente de correlación entre el IBEX y la cartera de contado: 0,8565</p></li>
<li><p>Volatilidad anualizada de la rentabilidad IBEX: 28,32%</p></li>
<li><p>Volatilidad anualizada de la rentabilidad de la cartera comprada: 24,33%</p></li>
<li><p>Multiplicador del Futuro del IBEX: 10€</p></li>
<li><p>Multiplicador del Futuro del Mini-IBEX: 1€</p></li>
<li><p>Subyacente de las opciones sobre IBEX: Futuro del Mini-IBEX</p></li>
<li><p>Delta de las opciones call sobre IBEX: 0,5625</p></li>
<li><p>Precio de las opciones call vendidas (a 3 meses a vencimiento ATM): 415,13€</p></li>
</ul>
<ol type="1">
<li><strong>Explique y cuantifique el proceso de cobertura de un 25% de la cartera mediante venta</strong></li>
</ol>
<details>
<summary>
</summary>
<div class="FOO callout-tip callout callout-style-simple">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-body-container">
<p>Hay que calcular el número de opciones call a vender mediante el cálculo del ratio de cobertura:</p>
<p><span class="math display">\[RC=-\frac{Valor\ efectivo\ de\ la\ cartera\cdot\ \beta_{cartera}}{Nominal\ del\ contrato\cdot \Delta}\]</span> donde,</p>
<ul>
<li><p><span class="math inline">\(\beta_{cartera}\)</span>, Beta entre cartera y benchmark (índice)</p></li>
<li><p><span class="math inline">\(\Delta\)</span>, Delta venta de call [-1, 0]</p></li>
<li><p><strong>Valor Efectivo cartera = 10.560.000€</strong></p></li>
<li><p><strong>Beta</strong>:</p></li>
</ul>
<p>La beta de la podemos expresar como,</p>
<p><span class="math display">\[\beta_{A}=\frac{Cov(R_A,R_B)}{\sigma^2_m}=\rho_{A,m}\cdot\frac{\sigma_A}{\sigma_m}\]</span> o, también como:</p>
<p><span class="math display">\[\beta_{A,m}=\rho_{A,m}\cdot\frac{\sigma_A}{\sigma_m}\]</span> en este caso <strong>empleamos la segunda fórmula</strong> ya que es la única de estas dos que se adapta a los datos que nos dan en el enunciado. Donde,</p>
<ul>
<li><p><span class="math inline">\(\beta_{p}\)</span>, es la beta de la cartera p con el mercado</p></li>
<li><p><span class="math inline">\(\rho_{p,m}\)</span> es el coeficiente de correlacion de la cartera p con el mercado</p></li>
<li><p><span class="math inline">\(\sigma_{p}\)</span>, es la desviación típica de la cartera p</p></li>
<li><p><span class="math inline">\(\sigma_{m}\)</span>, desviación típica del ibex (mercado o benchmark)</p></li>
</ul>
<p><span class="math display">\[\beta_{p}=0,8565\cdot\frac{24,33\%}{28,32\%}= 0,73583\]</span></p>
<ul>
<li><p><strong>Nominal del contrato = Precio del Mini-Ibex · multiplicador = 8.380·1= 8.380€</strong></p></li>
<li><p><strong>Delta call vendida = -0,5625</strong></p></li>
</ul>
<p>Luego <strong>para cubrir el 100% de la cartera</strong></p>
<p><span class="math display">\[RC=-\frac{10.560.000\cdot\ 0,73583}{8.380\cdot -0,5625}=-1.648\ call\]</span> necesitamos <strong>vender 1.648 call</strong>.</p>
<p>YPor consiguiente si queremos cubrir el 25% de cartera necesitaremos vender:</p>
<p><span class="math display">\[25\%^s/1.648=412\ call\]</span></p>
<div class="rmdwarning">
<p>Este tipo de caso práctico es muy recurrente en los exámenes de N II y EFA de EFPA. Recordemos que <strong>las opciones sobre IBEX-35 tienen como subyacente al futuro del mini-IBEX y no al futuro del IBEX</strong>.</p>
</div>
</div>
</div>
</div>
</details>
<hr>
</section>
<section id="características-de-renta-fija" class="level2">
<h2 class="anchored" data-anchor-id="características-de-renta-fija">Características de renta Fija</h2>
<p>Una empresa emite una serie de bonos corporativos (sin derivados) en el emercado a diez años con un cupón del 10% y amortización a la par.</p>
<ol type="1">
<li><p>¿Es un producto que les son aplicables la normativa MiFID II a partir de 2018? ¿Es complejo o no complejo?</p></li>
<li><p>Si los tipos de mercado en el momento de la emisión están al 10% para el mismo plazo, ¿cuál es su precio?</p></li>
<li><p>¿Cuál sería el precio del bono en el caso de que el tipo de mercado suba al 12%? Razone la respuesta.</p></li>
<li><p>¿Cuál sería el precio del bono en el caso de que el tipo de mercado baje al 8%? Razone la respuesta.</p></li>
</ol>
<details>
<summary>
</summary>
<div class="FOO callout-tip callout callout-style-simple">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-body-container">
<ol type="1">
<li>Tipología del producto</li>
</ol>
<p>Es un producto que les sería de aplicación la normativa MiFID II desde el el 3 de enero de 2018, y al tratarse de bonos corporativos (sin que lleven aparejado un derivado), se encuadrán dentro de los productos no complejos automáticamente.</p>
<ol start="2" type="1">
<li>Precio de un bono con los tipos al 10%</li>
</ol>
<p>Calculamos como una renta constante de diez términos los cupones y despues le sumamos el descuento del nominal,</p>
<p><span class="math display">\[P_0=C\cdot\frac{1-\left(1+i\right)^{-n}}{i}+\frac{N}{(1+i)^n}\]</span> que al sustituir y calcular tenemos,</p>
<p><span class="math display">\[P_0=10\cdot\frac{1-\left(1+0,10\right)^{-10}}{0,10}+\frac{100}{(1+0,10)^{10}}=100\]</span></p>
<p>que el <strong>precio entero del bono expresado como porcentaje del nominal es de 100%</strong>.</p>
<ol start="3" type="1">
<li>Precio del bono con los tipos al 12%</li>
</ol>
<p><span class="math display">\[P_0=10\cdot\frac{1-\left(1+0,12\right)^{-12}}{0,10}+\frac{100}{(1+0,12)^{10}}=88,7\]</span> donde el <strong>precio entero del bono expresado como porcentaje del nominal es de 88,7%, esto es una caida en el precio de 11,30</strong>.</p>
<p><strong>Logica de mercado</strong>:</p>
<p>Si un inversor no tuviera inmovilizada su inversión en el bono, podría obtener una rentabilidad superior adquiriendo otros bonos qu en ese momento ofrecen un interés del 12%. El precio del bono debe ser menor, de modo que al pagar un precio menor, la contraprestación recibida se ajuste a la rentabilidad del mercado, esto es 12%.</p>
<ol start="4" type="1">
<li>Precio del bono con los tipos al 8%</li>
</ol>
<p><span class="math display">\[P_0=10\cdot\frac{1-\left(1+0,08\right)^{-12}}{0,08}+\frac{100}{(1+0,08)^{10}}=113,42\]</span></p>
<p>donde el <strong>precio entero del bono expresado como porcentaje del nominal es de 113,42%, esto es una subida en el precio de 13,42</strong>.</p>
<p><strong>Logica de mercado</strong>:</p>
<p>El título se debe <strong>revalorizar</strong> ya que ofrece una mayor rentabilidad que el mercado. Por otro lado se observa que <strong>el cambio</strong> de valor por una subida y bajada de los tipos <strong>no es proporcional</strong>.</p>
<p>La repercusión en el precio de un bono suele indicar puntos básicos ( <em>basic points</em>, o en la terminología española d elos mercados “pipos”“), correspondiendo cada punto a una centésima parte de un punto porcentual. Si un bono sube su precio de 93,50 a 93,65 se dirá que subió 15 puntos básicos; es decir, un 0,15%.</p>
<p>Por otro lado, el efecto de una variación de tipos sobre el precio de un bonoserá mayor cuando mayor sea la vida que le quede al bono para amortizarse.</p>
<p>Con el paso del tiempo, se acorta la vida del bono y el precio de éste se irá acercando al precio de reembolso.</p>
</div>
</div>
</div>
</details>
<hr>
</section>
<section id="especulación-con-futuros" class="level2">
<h2 class="anchored" data-anchor-id="especulación-con-futuros">Especulación con futuros</h2>
<p>Responsable de la empresa GENCOIN pretende decidir si compra una cartera de acciones que replique un índice o si directamente compra un futuro especulativo (rentabilidad) con el Ibex a 11.200. si transcurridos 25 días el Ibex está situado en los 11.800 puntos.</p>
<ol type="1">
<li><p>¿Qué rentabilidad obtendría si se compra la cartera de acciones, desembolsando 112.000 € o en el caso de comprar contrato de futuro sobre el Ibex 35 a 11.200 puntos (10.000 € de garantía)? ¿Cuál sería el efecto apalancamiento?</p></li>
<li><p>En el caso del futuro del Ibex 35 (cada punto = 10 euros), si se exigen garantías diarias de 10.000 € por contrato. ¿Qué liquidaciones se realizarán cada día en las siguientes situaciones?</p>
<p>2.1 Día 1: Compra 20 futuros a 9.480 puntos. Comisión 16,50 € por contrato. Precio de Liquidación Diario (PLD) al cierre=9.460 puntos.</p>
<p>2.2 Día 2: PLD al cierre = 9.510 puntos.</p>
<p>2.3 Día 3: Venta de 5 futuros a 9.500. Cierre PLD = 9.485. Comisión = 16,50 €</p>
<p>2.4 Día 4: Venta de 15 futuros a 9.530. Vto del futuro PLD = 9.5830 Comisión = 16,50 €</p></li>
<li><p>¿Las acciones y el futuro son productos que les son aplicables la normativa MiFID II a partir de enero de 2018? ¿son complejos o no complejos?</p></li>
</ol>
<details>
<summary>
</summary>
<div class="FOO callout-tip callout callout-style-simple">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-body-container">
<ol type="1">
<li>Se compra la cartera de acciones, desembolsando 112.000 € VS compra del contrato de futuro sobre el Ibex 35 a 11.200 puntos -&gt; 10.000 € (garantía)</li>
</ol>
<p><strong>Posición contado. Comprando Ibex 35</strong>:</p>
<p><span class="math display">\[R_C=\frac{118.000-112.000}{112.000}\cdot 100=5,357\%\]</span> <strong>Posición de Futuro</strong>:</p>
<p><span class="math display">\[R_F=\frac{118.000-112.000}{10.000}\cdot 100=60\%\]</span> <strong>Efecto apalancamiento</strong>:</p>
<p><span class="math display">\[A=\frac{112.000}{10.000}=11,20\]</span></p>
<ol start="2" type="1">
<li>Cuadro <strong>resumen liquidaciones</strong>:</li>
</ol>
<p>![](images/nn.png)</p>
<pre><code></code></pre>
<p><strong>Acciones</strong>: quedan encuadradas dentro de MiFIDII y, por tanto, le son de aplicación la normativa a partir de su entrada en vigor el pasado 3 de enero de 2018, y al tratarse de acciones ordinarias de sociedades admitidas a cotización en mercados regulados o equivalentes de terceros países (y NO acciones convertibles privilegiadas convertibles) son suministro NO complejos automáticamente.</p>
<p><strong>Futuro</strong>: quedan encuadradas dentro de MiFIDII y, por tanto, le son de aplicación la normativa a partir de su entrada en vigor el pasado 3 de enero de 2018, y al tratarse de una tipología de derivado, en concreto un futuro especulativo, siempre tiene la calificación de producto complejo.</p>
</div>
</div>
</div>
</details>
<hr>
</section>
<section id="cobertura-con-futuros-euro-stoxx-50" class="level2">
<h2 class="anchored" data-anchor-id="cobertura-con-futuros-euro-stoxx-50">Cobertura con futuros (Euro Stoxx 50)</h2>
<p>El 8/1/2007 un inversor posee la cartera de acciones, que figura detallada en el cuadro 1, y teme que se produzca una importante e inmediata caída de las cotizaciones bursátiles de las acciones. Por ello, decide efectuar una operación de cobertura con contratos de futuros sobre Euro Stoxx 50 con vencimiento en enero de 2007 según los datos que aparecen en el cuadro 2.</p>
<ul>
<li><strong>Situación de los mercados al 8/1/2007</strong></li>
</ul>
<p><strong>Cuadro 1 (cartera de valores)</strong></p>
<table class="table">
<thead>
<tr class="header">
<th style="text-align: center;"><strong>Valores</strong></th>
<th style="text-align: center;"><strong>Nº Valores</strong></th>
<th style="text-align: center;"><strong>Precio (€)</strong></th>
<th style="text-align: left;"><strong>Beta</strong></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">AAA</td>
<td style="text-align: center;">2.000</td>
<td style="text-align: center;">22,00</td>
<td style="text-align: left;">1,15</td>
</tr>
<tr class="even">
<td style="text-align: center;">BBB</td>
<td style="text-align: center;">5.000</td>
<td style="text-align: center;">14,00</td>
<td style="text-align: left;">0,80</td>
</tr>
<tr class="odd">
<td style="text-align: center;">CCC</td>
<td style="text-align: center;">8.000</td>
<td style="text-align: center;">13,00</td>
<td style="text-align: left;">1,04</td>
</tr>
<tr class="even">
<td style="text-align: center;">DDD</td>
<td style="text-align: center;">2.000</td>
<td style="text-align: center;">40,00</td>
<td style="text-align: left;">0,90</td>
</tr>
<tr class="odd">
<td style="text-align: center;">EEE</td>
<td style="text-align: center;">7.000</td>
<td style="text-align: center;">24,00</td>
<td style="text-align: left;">0,70</td>
</tr>
</tbody>
</table>
<p><strong>Cuadro 2 (Futuro Euro Stoxx 50, vencimiento enero 2007)</strong></p>
<table class="table">
<thead>
<tr class="header">
<th style="text-align: center;"><strong>Compra</strong></th>
<th style="text-align: center;"><strong>Volumen</strong></th>
<th style="text-align: center;"><strong>Venta</strong></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">-</td>
<td style="text-align: center;">20</td>
<td style="text-align: center;">4.218</td>
</tr>
<tr class="even">
<td style="text-align: center;">-</td>
<td style="text-align: center;">4</td>
<td style="text-align: center;">4.216</td>
</tr>
<tr class="odd">
<td style="text-align: center;">4.215</td>
<td style="text-align: center;">5</td>
<td style="text-align: center;">-</td>
</tr>
<tr class="even">
<td style="text-align: center;">4.213</td>
<td style="text-align: center;">16</td>
<td style="text-align: center;">-</td>
</tr>
</tbody>
</table>
<p><strong>Euro Estoxx 50 al contado: 4.205,40</strong></p>
<p>El 16/1/2007 decide cancelar la operación de cobertura después de mantener intacta la cartera de acciones, según la información que se desprende de los cuadros 3 y 4:</p>
<ul>
<li><strong>Situación de los mercados al 16/1/2007</strong></li>
</ul>
<p><strong>Cuadro 3 (cartera de valores)</strong></p>
<table class="table">
<thead>
<tr class="header">
<th style="text-align: center;"><strong>Valores</strong></th>
<th style="text-align: center;"><strong>Nº Valores</strong></th>
<th style="text-align: center;"><strong>Precio (€)</strong></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">AAA</td>
<td style="text-align: center;">2.000</td>
<td style="text-align: center;">20,00</td>
</tr>
<tr class="even">
<td style="text-align: center;">BBB</td>
<td style="text-align: center;">5.000</td>
<td style="text-align: center;">13,00</td>
</tr>
<tr class="odd">
<td style="text-align: center;">CCC</td>
<td style="text-align: center;">8.000</td>
<td style="text-align: center;">12,00</td>
</tr>
<tr class="even">
<td style="text-align: center;">DDD</td>
<td style="text-align: center;">2.000</td>
<td style="text-align: center;">36,00</td>
</tr>
<tr class="odd">
<td style="text-align: center;">EEE</td>
<td style="text-align: center;">7.000</td>
<td style="text-align: center;">23,00</td>
</tr>
</tbody>
</table>
<p><strong>Cuadro 4 (Futuro Euro Stoxx 50, vencimiento enero 2007)</strong></p>
<table class="table">
<thead>
<tr class="header">
<th style="text-align: center;"><strong>Compra</strong></th>
<th style="text-align: center;"><strong>Volumen</strong></th>
<th style="text-align: center;"><strong>Venta</strong></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">-</td>
<td style="text-align: center;">9</td>
<td style="text-align: center;">3.952</td>
</tr>
<tr class="even">
<td style="text-align: center;">-</td>
<td style="text-align: center;">5</td>
<td style="text-align: center;">3.950</td>
</tr>
<tr class="odd">
<td style="text-align: center;">4.215</td>
<td style="text-align: center;">2</td>
<td style="text-align: center;">-</td>
</tr>
<tr class="even">
<td style="text-align: center;">4.213</td>
<td style="text-align: center;">10</td>
<td style="text-align: center;">-</td>
</tr>
</tbody>
</table>
<p><strong>Euro Estoxx 50 al contado: 3.950,00</strong></p>
<ul>
<li><strong>Notas de interés</strong>:</li>
</ul>
<ol type="1">
<li><p>Las comisiones de compra y venta de futuros ascienden a 3 euros por cada contrato en compra, venta o vencimiento.</p></li>
<li><p>Los depósitos de garantía se remuneran exactamente igual que la liquidez que posee el titular, en una cuenta, en el miembro de mercado, remunerada a tipos de mercado monetario en repos a un día.</p></li>
<li><p>Ninguna de las 50 acciones integrantes del índice Euro Stoxx 50 va a pagar dividendos o ampliar capital entre la fecha de inicio de la cobertura y la fecha de vencimiento del contrato de futuros Euro Stoxx 50 con vencimiento en enero de 2007.</p></li>
<li><p>El valor del tick o multiplicador para futuros Euro Stoxx 50 es 10 euros.</p></li>
</ol>
<p><strong>SE PIDE</strong>:</p>
<p>Determinar los resultados combinados de la operación de cobertura con futuros en términos absolutos.</p>
<details>
<summary>
</summary>
<div class="FOO callout-tip callout callout-style-simple">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-body-container">
<p><strong>Apartado a</strong></p>
<ul>
<li>Con fecha 8/1/2007 la posición en futuros será vendida, esto es, <strong>vender contratos de fututro sobre el Euro Estoxx 50</strong></li>
</ul>
<p><strong>Apartado b</strong></p>
<ul>
<li>Calculamos el Ratio de Cobertura (RC) con la siguiente fórmula:</li>
</ul>
<p><span class="math display">\[RC=-\frac{Valor\ efectivo\ de\ la\ cartera\cdot\ \beta_{cartera}}{Indice\ al\ contado\cdot multiplicador}\]</span></p>
<ul>
<li>Luego, necesitamos primeramente hallar el valor de efectivo de la cartera (valor de mercado) y su beta (a partir de las betas individuales de los valores del cuador 1). Resumimos los resultados de estos calculos en la tabla siguiente:</li>
</ul>
<table class="table">
<colgroup>
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: center;"><strong>Valor</strong></th>
<th style="text-align: center;"><strong>Acciones</strong></th>
<th style="text-align: center;"><strong>Precio(€)</strong></th>
<th style="text-align: center;"><strong>Beta</strong></th>
<th style="text-align: center;"><strong>Efectivo(€)</strong></th>
<th style="text-align: center;"><strong>Peso</strong></th>
<th style="text-align: center;"><strong>Beta</strong>(<span class="math inline">\(\beta_c\)</span>)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;"></td>
<td style="text-align: center;">a</td>
<td style="text-align: center;">P</td>
<td style="text-align: center;">B</td>
<td style="text-align: center;"><span class="math inline">\(E=a\cdot P\)</span></td>
<td style="text-align: center;"><span class="math inline">\(w=E\cdot VC\)</span></td>
<td style="text-align: center;"><span class="math inline">\(w\cdot B\)</span></td>
</tr>
<tr class="even">
<td style="text-align: center;">AAA</td>
<td style="text-align: center;">2.000</td>
<td style="text-align: center;">22,00</td>
<td style="text-align: center;">1,15</td>
<td style="text-align: center;">44.000</td>
<td style="text-align: center;">0,09442</td>
<td style="text-align: center;">0,108583</td>
</tr>
<tr class="odd">
<td style="text-align: center;">BBB</td>
<td style="text-align: center;">5.000</td>
<td style="text-align: center;">14,00</td>
<td style="text-align: center;">0,80</td>
<td style="text-align: center;">70.000</td>
<td style="text-align: center;">0,15021</td>
<td style="text-align: center;">0,120168</td>
</tr>
<tr class="even">
<td style="text-align: center;">CCC</td>
<td style="text-align: center;">8.000</td>
<td style="text-align: center;">13,00</td>
<td style="text-align: center;">1,04</td>
<td style="text-align: center;">104.000</td>
<td style="text-align: center;">0,22318</td>
<td style="text-align: center;">0,232107</td>
</tr>
<tr class="odd">
<td style="text-align: center;">DDD</td>
<td style="text-align: center;">2.000</td>
<td style="text-align: center;">40,00</td>
<td style="text-align: center;">0,90</td>
<td style="text-align: center;">80.00</td>
<td style="text-align: center;">0,17167</td>
<td style="text-align: center;">0,154503</td>
</tr>
<tr class="even">
<td style="text-align: center;">EEE</td>
<td style="text-align: center;">7.000</td>
<td style="text-align: center;">24,00</td>
<td style="text-align: center;">0,70</td>
<td style="text-align: center;">168.000</td>
<td style="text-align: center;">0,36052</td>
<td style="text-align: center;">0,252364</td>
</tr>
<tr class="odd">
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;">VC=466.000</td>
<td style="text-align: center;">1</td>
<td style="text-align: center;"><span class="math inline">\(\beta_c=0,8677\)</span></td>
</tr>
</tbody>
</table>
<ul>
<li>sabemos también que, el futuro <strong>Euro Estoxx 50 al contado = 4.205,40</strong> y el <strong>multiplicador = 10</strong>. Ahora bastará con sustituir los valores en la fórmula del RC:</li>
</ul>
<p><span class="math display">\[RC=-\frac{466.000\cdot0,8677}{4.205,40\cdot 10}=9,615 \approx 10\ contratos\]</span></p>
<ul>
<li>así tendremos <strong>5 contratos a 4.215 y 5 a 4.213</strong> (cuadro 2), a un <strong>precio medio de 4.214</strong> ((4.215+4.213)/2).</li>
</ul>
<p><strong>Apartado c</strong></p>
<ul>
<li>Como resultado de la cobertura, tenemos 10 contratos de futuros sobre el Euro Estoxx 50 al precio indicado en el cuadro 4. Esto es, 5 contratos a 3.950 y, 5 contratos a 3.952 y a un <strong>precio medio de 3.951</strong> ((3.950+3.952)/2). La tabla siguiente resume los resultados:</li>
</ul>
<table class="table">
<colgroup>
<col style="width: 15%">
<col style="width: 13%">
<col style="width: 58%">
<col style="width: 12%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: center;"></th>
<th style="text-align: center;"><strong>Inicio</strong></th>
<th style="text-align: center;"><strong>Final</strong></th>
<th style="text-align: center;"><strong>Total</strong></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;"><strong>Cartera</strong></td>
<td style="text-align: center;">466.000</td>
<td style="text-align: center;">434.000(cuadro 4)</td>
<td style="text-align: center;">-32.000</td>
</tr>
<tr class="even">
<td style="text-align: center;"><strong>Futuro</strong></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"><span class="math inline">\((4.214-3.951)\cdot 10\cdot 10-10\cdot 3\cdot 2\)</span></td>
<td style="text-align: center;">26.240</td>
</tr>
</tbody>
</table>
<ul>
<li><strong>Como resultado neto de la operación tenemos que, combinando acciones y futuros, la pérdida ha sido de - 5.760</strong> (-32.000+26.240).</li>
</ul>
<p><strong>NOTA</strong>: hay que tener en cuenta los gastos, esto es: “las <strong>comisiones</strong> de compra y venta de futuros ascienden a 3 euros por cada contrato en compra, venta o vencimiento”. Luego, en este caso el importe de las comisiones será de 60€ (<strong>10 contratos x 3€ x 2 operaciones</strong>).</p>
</div>
</div>
</div>
</details>
<hr>
</section>
<section id="características-de-una-cartera-ii" class="level2">
<h2 class="anchored" data-anchor-id="características-de-una-cartera-ii">Características de una cartera (II)</h2>
<p>Se dispone de la siguiente información relativa a dos acciones, A y B:</p>
<table class="table">
<colgroup>
<col style="width: 21%">
<col style="width: 29%">
<col style="width: 21%">
<col style="width: 27%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: center;"><strong>Activo</strong></th>
<th style="text-align: center;"><strong>Rentabilidad Esperada (%)</strong></th>
<th style="text-align: center;"><strong>Volatilidad (%)</strong></th>
<th style="text-align: center;"><strong>Coef. Correlación (A,B)</strong></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">A</td>
<td style="text-align: center;">9%</td>
<td style="text-align: center;">16%</td>
<td style="text-align: center;">0,40</td>
</tr>
<tr class="even">
<td style="text-align: center;">B</td>
<td style="text-align: center;">14%</td>
<td style="text-align: center;">24%</td>
<td style="text-align: center;"></td>
</tr>
</tbody>
</table>
<p>Si del presupuesto destinado a la inversión bursátil se invierte el 40% en el título A y el 60% restante en el B, auxiliándose con los resultados aportados por Markowitz, se pide:</p>
<ol type="1">
<li><p>Rentabilidad media que se espera obtener con la cartera así construida.</p></li>
<li><p>Volatilidad de la cartera.</p></li>
<li><p>Determinar cuál sería la combinación de cartera de mínimo riesgo.</p></li>
<li><p>En caso de que los importes a invertir se destinaran un 50% al título A y un 50% en un activo libre de riesgo que ofreciera una rentabilidad del 2,5%, ¿cuál sería entonces la rentabilidad y la volatilidad de la cartera?</p></li>
<li><p>¿Cuál de las tres carteras alternativas resulta preferible?</p></li>
</ol>
<details>
<summary>
</summary>
<div class="FOO callout-tip callout callout-style-simple">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-body-container">
<p><strong>Apartado 1</strong></p>
<ul>
<li>Calculamos la <strong>rentabilidad esperada de la cartera</strong> (<span class="math inline">\(E_p\)</span>) como:</li>
</ul>
<p><span class="math display">\[E_p= w_A \cdot E_A + w_B \cdot E_B\]</span></p>
<ul>
<li>donde al sustituir y calcular, tenemos que:</li>
</ul>
<p><span class="math display">\[E_p= 0,40 \cdot 9\% + 0,60 \cdot 14\%=12\%\]</span></p>
<p><strong>Apartado 2</strong></p>
<ul>
<li>Calculamos la <strong>volatilidad esperada de la cartera</strong> (<span class="math inline">\(\sigma_p\)</span>) como:</li>
</ul>
<p><strong>Volatilidad de una cartera en función del coeficiente de correlación</strong></p>
<p><span class="math display">\[\sigma_p=\sqrt{w_{A}^2\cdot\sigma_A^2+w_B^2\cdot\sigma_B^2+2\cdot w_A\cdot w_B\cdot\rho_{A,B}\cdot\sigma_{A}\cdot\sigma_{B}}\]</span></p>
<p>Donde,</p>
<ul>
<li><p><span class="math inline">\(\sigma_p\)</span>, es la volatilidad (riesgo) de la cartera <span class="math inline">\(p\)</span>.</p></li>
<li><p><span class="math inline">\(w_A\)</span>, es la ponderación (o proporción) del activo <span class="math inline">\(A\)</span> dentro de la cartera <span class="math inline">\(p\)</span>.</p></li>
<li><p><span class="math inline">\(\sigma_A\)</span>, es la varianza del título <span class="math inline">\(A\)</span>.</p></li>
<li><p><span class="math inline">\(w_B\)</span>, es la ponderación (o proporción) del activo <span class="math inline">\(B\)</span> dentro de la cartera <span class="math inline">\(p\)</span>.</p></li>
<li><p><span class="math inline">\(\sigma_B\)</span>, es la varianza del título <span class="math inline">\(B\)</span>.</p></li>
<li><p><span class="math inline">\(\rho_{A,B}\)</span>, es el coeficiente de correlación entre los activos A y B.</p></li>
<li><p>donde al sustituir y calcular, obtenemos el siguiente resultado:</p></li>
</ul>
<p><span class="math display">\[\sigma_p= \sqrt{0,40^2 \cdot 16^2 +0,60^2 \cdot 24^2+2\cdot 0,40\cdot w_2\cdot 0,4\cdot 16\cdot24}=17,95\%\]</span></p>
<p><strong>Apartado 3</strong></p>
<ul>
<li>Se trata de calcular los pesos para cada activo que hacen que la volatilidad de la cartera sea la mínima posible, dados unos niveles de volatilidad y correlación para los 2 activos que forman la cartera. Luego calculamos la <strong>composición de la cartera de mínimo riesgo</strong> empleando la siguiente expresión:</li>
</ul>
<p><strong>Composición de la cartera de mínimo riesgo</strong></p>
<p><span class="math display">\[{ { w }_{ A }^{ * }=\frac { { \sigma  }_{ B }^{ 2 }-{ \rho  }_{ 1,2 }{ \sigma  }_{ A }{ \sigma  }_{ B } }{ { \sigma  }_{ A }^{ 2 }+{ \sigma  }_{ B }^{ 2 }-2{ \rho  }_{ 1,2 }{ \sigma  }_{ A }{ \sigma  }_{ B } }  }\]</span></p>
<p>y,</p>
<p><span class="math display">\[w_{ B }^{ * }=(1-w_{ A }^{ * })\]</span></p>
<p>Donde,</p>
<ul>
<li><p><span class="math inline">\({ w }_{ A }^{ * }\)</span>, es la ponderación (o proporción) del activo <span class="math inline">\(A\)</span> dentro de la cartera de mínimo riesgo.</p></li>
<li><p><span class="math inline">\({ w }_{ B }^{ * }\)</span>, es la ponderación (o proporción) del activo <span class="math inline">\(B\)</span> dentro de la cartera de mínimo riesgo.</p></li>
<li><p><span class="math inline">\(\sigma_A\)</span>, es la varianza del título <span class="math inline">\(A\)</span>.</p></li>
<li><p><span class="math inline">\(\sigma_B\)</span>, es la varianza del título <span class="math inline">\(B\)</span>.</p></li>
<li><p><span class="math inline">\(\rho_{A,B}\)</span>, es el coeficiente de correlación entre los activos A y B.</p></li>
<li><p>Así, al susutituir y calcular tenemos que</p></li>
</ul>
<p><span class="math display">\[w_{ A }^{ * }=\frac{0,24^2-0,4\cdot16\cdot24}{0,16^2+24^2-2\cdot0,4\cdot16\cdot24}=0,8049(80,49\%)\]</span></p>
<p><span class="math display">\[{ w }_{ B }^{ * }=(1-w_{ A }^{ * })=(1-0,8049)=0,1951(19,51\%)\]</span></p>
<ul>
<li>Donde la cartera mínima varianza estará compuesta por un <strong>80,49% del Activo A y por un 19,51% del Activo B</strong>.</li>
</ul>
<p><strong>Apartado 4</strong></p>
<ul>
<li>En caso de que los importes a invertir se destinaran un 50% al título A y un 50% en un activo libre de riesgo que ofreciera una rentabilidad del 2,5%, entonces la <strong>rentabilidad de la cartera</strong> sería de:</li>
</ul>
<p><span class="math display">\[E_p*= 0,50 \cdot 9\% + 0,50 \cdot 2,5\%=5,75\%\]</span></p>
<ul>
<li>y la <strong>volatilidad de la cartera</strong> (en este caso solamente contendrá el riesgo del activo A, puesto que se trata del único activo arriesgado) será de:</li>
</ul>
<p><span class="math display">\[\sigma_p*=w_A*\cdot \sigma_A=0,50\cdot 16=8\%\]</span></p>
<p><strong>Apartado 4</strong></p>
<ul>
<li><p>En este caso tenemos que determinar cúal de las tres carteras se prefiere, para ello <strong>calculamos su ratio de Sharpe</strong> (este ratio nos indica la rentabilidad de la cartera ajustada por unidad de riesgo asumido) de forma que <strong>la cartera que presente un mayor ratio de sharpe será la cartera que ofrece una mayor rentabilidad para un mismo nivel de riesgo</strong>. Luego:</p></li>
<li><p>la <strong>cartera inicial (apartados 1 y 2)</strong> presenta el siguiente ratio de Sharpe</p></li>
</ul>
<p><span class="math display">\[S_p^1=\frac{E_p-R_f}{\sigma_p}=\frac{12-2,5}{19,75}=0,52925\]</span></p>
<ul>
<li><p>para la <strong>cartera de mínimo riesgo (apartado 3)</strong> realizamos los siguientes <strong>cálculos para poder hallar el ratio de Sharpe</strong></p></li>
<li><p><strong>Rentabilidad</strong> de la catera de mínimo riesgo <span class="math inline">\(E_p'\)</span></p></li>
</ul>
<p><span class="math display">\[E_p'= w_A'  \cdot E_A' + w_B' \cdot E_B\]</span></p>
<p><span class="math display">\[E_p'=0,08049\cdot 9+ 0,1951\cdot 14=9,9755\%\]</span></p>
<ul>
<li><strong>Volatilidad</strong> catera de mínimo riesgo <span class="math inline">\(E_p'\)</span></li>
</ul>
<p><span class="math display">\[\sigma_p'=\sqrt{w_{A}'^2\cdot\sigma_A'^2+w_B'^2\cdot\sigma_B'^2+2\cdot w_A'\cdot w_B'\cdot\rho_{A,B}\cdot\sigma_{A}'\cdot\sigma_{B}'}\]</span></p>
<p><span class="math display">\[\sigma_p'= \sqrt{0,8049^2 \cdot 16^2 +0,1951^2 \cdot 24^2+2\cdot 0,8049\cdot 0,1951\cdot 0,4\cdot 16\cdot24}=15,36\%\]</span></p>
<ul>
<li>finalmente, podemos calcular el <strong>ratio de Sharpe</strong> como</li>
</ul>
<p><span class="math display">\[S_p^2=\frac{E_p-R_f}{\sigma_p}=\frac{9,9755-2,5}{15,36}=0,4867\]</span></p>
<ul>
<li>Por último, calculamos el ratio de Sharpe de la <strong>cartera del apartado 4</strong>, que queda como sigue</li>
</ul>
<p><span class="math display">\[S_p^3=\frac{E_p-R_f}{\sigma_p}=\frac{5,75-2,5}{8}=0,40625\]</span></p>
<ul>
<li>Si establecemos la comparación de los tes ratios tenemos que:</li>
</ul>
<p><span class="math display">\[S_p^1&gt;S_p^2&gt;S_p^3\]</span></p>
<ul>
<li>ya que</li>
</ul>
<p><span class="math display">\[0,52925&gt;0,4867&gt;0,40625\]</span></p>
<ul>
<li>Luego, podemos afirmar que <strong>la cartera que presenta mayor ratio de sharpe es la cartera inicial, y por tanto es la cartera que ofrece una mayor rentabilidad por unidad de riesgo asumido</strong>.</li>
</ul>
</div>
</div>
</div>
</details>
<hr>
</section>
<section id="ratios-bursátiles-ii" class="level2">
<h2 class="anchored" data-anchor-id="ratios-bursátiles-ii">Ratios bursátiles (II)</h2>
<p>Considerando los siguientes datos sobre la previsible evolución de la empresa BBL (las cifras referentes a unidades monetarias se expresan en millones de euros)</p>
<p><img src="images/mod1ejercicioP5.3.png" class="img-fluid"> <img src="images/mod1ejercicioP5.3a.png" class="img-fluid"></p>
<p>A partir de los estados anteriores, y sabiendo que BBL tiene un precio de 6,22 euros por acción, con un total de 100 millones de acciones y un pay out del 80%, se pide:</p>
<ol type="a">
<li><p>Calcular el PER, el Precio Cash Flow (PCF), el Precio sobre Ventas (PSR Price to Sales Ratio) y el Precio Dividendo (PD) de BBL correspondiente al ejercicio 2014.</p></li>
<li><p>Margen EBITDA en 2014 y previsible evolución.</p></li>
<li><p>Fondo de Maniobra, Rotación de Activo Total y Ratio de Endeudamiento correspondiente al ejercicio 2014.</p></li>
<li><p>ROA y ROE correspondiente al ejercicio 2014.</p></li>
<li><p>Siendo el coste de los recursos propios del 9,5% y considerando un horizonte temporal de 3 años, proyectando después al infinito a una tasa de crecimiento del 5%, estimar por el método de Gordon-Shapiro el precio teórico de la acción.</p></li>
</ol>
<details>
<summary>
</summary>
<div class="FOO callout-tip callout callout-style-simple">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-body-container">
<p><strong>Apartado a</strong></p>
<ul>
<li><p>Calcular el PER, el Precio Cash Flow (PCF), el Precio sobre Ventas (PSR Price to Sales Ratio) y el Precio Dividendo (PD) de BBL correspondiente al ejercicio 2014:</p></li>
<li><p><span class="math inline">\(PER_{2014}=\frac{Cap. \ Bursatil}{BDI}=\frac{P_0}{BPA}\)</span></p></li>
<li><p><span class="math inline">\(PER_{2014}=\frac{6,22}{(20,8/100)}=29,90x\)</span></p></li>
<li><p><span class="math inline">\(PCFR_{2014}=\frac{Cap. \ Bursatil}{CF}=\frac{622}{95,8}=6,49x\)</span></p></li>
</ul>
<p>nota: el calculo del <strong>Cash Flow</strong> es el resultado de sumarle al Beneficio Neto las Amortizaciones y las Provisiones. En este caso, como no tenemos Provisiones el Cash Flow será de <strong>95,80 (CF=20,8+75)</strong>.</p>
<ul>
<li><p><span class="math inline">\(PSR_{2014}=\frac{Cap. \ Bursatil}{Ventas}=\frac{622}{1.000}=0,622x\)</span></p></li>
<li><p><span class="math inline">\(DY_{2014}=\frac{DPA}{P}\)</span></p></li>
</ul>
<p>donde el</p>
<p><span class="math display">\[Dividendos_{2014} = BDI_{2014} \cdot pay out=20,8 \cdot 0,8=16,64\]</span></p>
<p><span class="math display">\[Dividendos_{2015} = BDI_{2015} \cdot pay out=39,6 \cdot 0,8=31,68\]</span></p>
<p><span class="math display">\[Dividendos_{2016} = BDI_{2016} \cdot pay out=84,5 \cdot 0,8=67,6\]</span></p>
<p>luego,</p>
<p><span class="math display">\[DPA_{2014}=\frac{16,64}{100}=0,1664\]</span> <span class="math display">\[DPA_{2015}=\frac{31,68}{100}=0,3168\]</span></p>
<p><span class="math display">\[DPA_{2016}=\frac{67,6}{100}=0,676\]</span></p>
<p>y, el dividend yield o rentabilidad por dividendo es de</p>
<p><span class="math display">\[DY_{2014}=\frac{DPA}{P}=\frac{0,1664}{6,22}=0,026=2,6\%\]</span></p>
<ul>
<li>para obtener el <strong>Precio Dividendo (PD)</strong> hacemos la <strong>inversa del Dividend Yield</strong></li>
</ul>
<p><span class="math display">\[PD_{2014}=\frac{1}{DY_{2014}}=\frac{1}{0,026}=38,46x\]</span></p>
<p><strong>Apartado b</strong></p>
<ul>
<li>Margen EBITDA en 2014</li>
</ul>
<p><span class="math display">\[M.\ EBITDA_{2014}=\frac{EBITDA}{Ventas}=\frac{112}{1.000}=0,112=11,2\%\]</span></p>
<ul>
<li>y previsible evolución</li>
</ul>
<p><span class="math display">\[M.\ EBITDA_{2015}=13,33\%\]</span></p>
<p><span class="math display">\[M.\ EBITDA_{2016}=17,295\%\]</span></p>
<p><span class="math display">\[M.\ EBITDA_{2017}=18,13\%\]</span></p>
<p><strong>Apartado c</strong></p>
<ul>
<li><strong>Fondo de Maniobra (FM)</strong> correspondiente al ejercicio 2014</li>
</ul>
<p><span class="math display">\[FM_{2014}=AC_{2014}-PC_{2014}=400-305=95\ M.\ euros\]</span></p>
<ul>
<li><strong>Rotación de Activo Total (RAT)</strong> correspondiente al ejercicio 2014</li>
</ul>
<p><span class="math display">\[RAT_{2014}=\frac{Ventas}{AT}=\frac{1.000}{735}=1,36=136\%\]</span></p>
<ul>
<li><strong>Ratio de Endeudamiento (RE)</strong> correspondiente al ejercicio 2014</li>
</ul>
<p><span class="math display">\[RE_{2014}=\frac{Recursos\ Ajenos\ c/p\ y\ l/p}{Patrimonio\ Neto}=\frac{305+100}{330}=122,73\%\]</span></p>
<p><strong>Apartado d</strong></p>
<ul>
<li><strong>ROA</strong> correspondiente al ejercicio 2014</li>
</ul>
<p><span class="math display">\[ROA_{2014}=\frac{EBIT}{AT}=\frac{37}{735}=5,03\%\]</span></p>
<ul>
<li><strong>ROE</strong> correspondiente al ejercicio 2014</li>
</ul>
<p><span class="math display">\[ROA_{2014}=\frac{BDI}{FFPP}=\frac{20,8}{330}=6,03\%\]</span></p>
<p><strong>Apartado e</strong></p>
<ul>
<li>En este apartado vamos a estimar por el precio teórico de la acción por el método de Gordon-Shapiro para un coste de los recursos propios del 9,5%, un horizonte temporal de 3 años. Una vez finalizado este periodo se proyectará hasta el infinito a una tasa de crecimiento del 5%. Entendemos que se reparte el 80% de los beneficios vía dividendos (pay out), de modo que el dívidendo vendrá dado para el 2014 como D1, 2015 como D2 y 2016 como D3. Luego la expresión que hay que calcular sería la siguiente:</li>
</ul>
<p><span class="math display">\[P_0=\frac{D_1}{(1+K_e)}+\frac{D_2}{(1+K_e)^2}+\frac{D_3}{(K_e-g)}\cdot(1+K_e)^{-2}\]</span> como tenemos calculado del apartado a los dividendos por acción,</p>
<p><span class="math display">\[DPA_{2014}=\frac{16,64}{100}=0,1664\]</span></p>
<p><span class="math display">\[DPA_{2015}=\frac{31,68}{100}=0,3168\]</span></p>
<p><span class="math display">\[DPA_{2016}=\frac{67,6}{100}=0,676\]</span></p>
<ul>
<li>bastará sustitur los valores y calcular su resultado:</li>
</ul>
<p><span class="math display">\[P_0=\frac{0,1}{(1+0,095)}+\frac{0,3}{(1+0,095)^2}+\frac{0,6}{(0,095-0,05)}\cdot(1+0,095)^{-2}=11,46\ euros\]</span></p>
</div>
</div>
</div>
</details>
<hr>
</section>
<section id="ratio-de-sharpe" class="level2">
<h2 class="anchored" data-anchor-id="ratio-de-sharpe">Ratio de Sharpe</h2>
<p>De dos títulos A y B con rentabilidades independientes entre si se espera que obtengan las rentabilidades esperadas y riesgos expresados en el siguiente cuadro:</p>
<p><img src="images/mod1ejercicioP6.png" class="img-fluid"></p>
<p>El activo libre de riesgo ofrece una rentabilidad del 1,5% y la rentabilidad esperada del índice de mercado es del 12%.</p>
<p>Se pide:</p>
<ol type="a">
<li><p>Calcular la rentabilidad esperada y la volatilidad de una cartera formada por un 40% del título A y un 60% del título B.</p></li>
<li><p>¿Es posible formar con los títulos anteriores una cartera con riesgo nulo? En caso afirmativo encontrar su composición, y en caso negativo encontrar la composición de la cartera con mínimo riesgo.</p></li>
<li><p>Calcular y comparar el ratio de Sharpe de las dos carteras.</p></li>
</ol>
<details>
<summary>
</summary>
<div class="FOO callout-tip callout callout-style-simple">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-body-container">
<p><img src="images/mod1ejercicioP6.1.png" class="img-fluid"></p>
<p><img src="images/mod1ejercicioP6.1a.png" class="img-fluid"></p>
</div>
</div>
</div>
</details>
<hr>
</section>
<section id="cartera-de-renta-fija" class="level2">
<h2 class="anchored" data-anchor-id="cartera-de-renta-fija">Cartera de Renta Fija</h2>
<p>Un cliente de un family office tiene la siguiente cartera de bonos:</p>
<table class="table">
<colgroup>
<col style="width: 11%">
<col style="width: 11%">
<col style="width: 11%">
<col style="width: 11%">
<col style="width: 11%">
<col style="width: 11%">
<col style="width: 11%">
<col style="width: 11%">
<col style="width: 11%">
</colgroup>
<thead>
<tr class="header">
<th>Bono</th>
<th>Emisión</th>
<th>Venc.</th>
<th><strong>Cupón</strong></th>
<th><strong>Nominal</strong></th>
<th><strong>Cotización</strong></th>
<th><strong>D. Mod</strong></th>
<th><strong>TIR</strong></th>
<th><strong>Cant.</strong></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>A</strong></td>
<td>14/07/2009</td>
<td>14/07/2014</td>
<td>4,75%</td>
<td>1.000€</td>
<td>105,959%</td>
<td>2,051</td>
<td>1,975%</td>
<td>215</td>
</tr>
<tr class="even">
<td><strong>B</strong></td>
<td>23/10/2009</td>
<td>23/10/2016</td>
<td>4,463%</td>
<td>50.000€</td>
<td>110,330%</td>
<td>4,030</td>
<td>2,032%</td>
<td>4</td>
</tr>
<tr class="odd">
<td><strong>C</strong></td>
<td>06/08/2003</td>
<td>06/08/2018</td>
<td>5%</td>
<td>1.000€</td>
<td>114,980%</td>
<td>5.311</td>
<td>2,400%</td>
<td>280</td>
</tr>
</tbody>
</table>
<p>Tenga en cuenta que la información es del día 20/04/2012 y la fecha de liquidación (fecha valor) correspondiente es el 25/04/2012</p>
<p><strong>SE PIDE</strong>:</p>
<ol type="a">
<li><p>Hallar el Valor de la Cartera</p></li>
<li><p>Calcular la Duración de la Cartera</p></li>
<li><p>Si el horizonte temporal del cliente es de 3 años indicar si la cartera está inmunizada. Razonar la respuesta.</p></li>
<li><p>Calcular la Duración Modificada de la Cartera y determinar el cambio porcentual de la misma ante una subida de 50 pb en los tipos de interés.</p></li>
</ol>
<details>
<summary>
</summary>
<div class="FOO callout-tip callout callout-style-simple">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-body-container">
<p><strong>Apartado a</strong></p>
<ul>
<li>En primer lugar tenemos que calcular el cupón corrido de cada bono a partir de su precio de cotización (precio excupón):</li>
</ul>
<div class="rmdimportant">
<p>Fórmula del cupón corrido:</p>
<p><span class="math display">\[CC=\frac{D_c}{D_t}\cdot C\]</span></p>
<p>donde,</p>
<ul>
<li><p><span class="math inline">\(CC\)</span>, es el cupón corrido.</p></li>
<li><p><span class="math inline">\(D_{c}\)</span>,es el tiempo transcurrido desde el pago del último cupón.</p></li>
<li><p><span class="math inline">\(D_{t}\)</span>, es el tiempo que transcurre entre el pago de dos cupones consecutivos</p></li>
<li><p><span class="math inline">\(C\)</span>, es el importe del cupón que se paga periódicamente.</p></li>
</ul>
</div>
<ul>
<li>Sustituimos los valores para cada uno de los bonos en la igualdad y calculamos,</li>
</ul>
<p><span class="math display">\[CC_A=\frac{286}{365}\cdot 4,75=3,711748\%\]</span> <span class="math display">\[CC_B=\frac{185}{365}\cdot 4,463=2,255888\%\]</span></p>
<p><span class="math display">\[CC_C=\frac{263}{365}\cdot 5=3,592896\%\]</span></p>
<ul>
<li>En segundo lugar calcularemos los precios pero en este caso, teniendo en cuenta el cupón corrido. En otras palabras calculamos el precio entero (o también conocido como precio sucio):</li>
</ul>
<div class="rmdnote">
<p>Recordemos que:</p>
<p><span class="math display">\[Precio\,entero = Precio\,excupón + cupón\,corrido\]</span></p>
<p>Por tanto,</p>
<p><span class="math display">\[Precio\,excupón = Precio\,entero - cupón\,corrido\]</span></p>
</div>
<p><span class="math display">\[Precio\ entero_A = 105,959\% + 3,711748\%=109,671\%=1.096,71\ euros \]</span></p>
<p><span class="math display">\[Precio\ entero_B =  110,330\%+ 2,255888\%=112,586\%=56.293\ euros\]</span></p>
<p><span class="math display">\[Precio\ entero_C = 114,980\% + 3,592896\%=118,573\%=1.185,73\%\]</span></p>
<ul>
<li>Luego para conocer el <strong>valor de la cartera</strong> bastará con multiplicar cantidad por precio, de forma que:</li>
</ul>
<p><span class="math display">\[P_{cartera}=P_A\cdot C_A+P_B\cdot C_B+P_C\cdot C_C\]</span> <span class="math display">\[P_{cartera}=1.096,71\cdot215+56.293\cdot 4+1.185,73\cdot 280=792.969,05\ euros\]</span></p>
<p><strong>Apartado b</strong></p>
<ul>
<li>Para calcular la Duración de la cartera, primero calculamos la Duración de cada uno de los bonos. Para ello hemos de <strong>transformar la Duración Modificada (también conocida como Duración Corregida) en Duración de Macaulay</strong> (la que se conoce también como Duración simplemente).</li>
</ul>
<div class="rmdnote">
<p>Por definición la Duración Corregida es, como podemos ver en su fórmula, la Duración de Macaulay dividida entre 1 + la TIR del bono:</p>
<p><span class="math display">\[D_{corregida}=\frac{Duracion\,de\, Macaulay}{\left(1+TIR\right)}=\frac{D}{\left(1+TIR\right)} \]</span> luego,</p>
<p><span class="math display">\[Duracion\,de\, Macaulay= D \cdot \left(1+TIR\right) \]</span></p>
<p><a href="https://www.albertobernat.com/1488-2/">Mas información aquí</a></p>
</div>
<p><span class="math display">\[D_A=DM_A\cdot (1+TIR_A)= 2,051\cdot (1+0,01975)=2,0915\]</span> <span class="math display">\[D_B=DM_B\cdot (1+TIR_B)=4,030\cdot (1+0,02032)=4,1119\]</span></p>
<p><span class="math display">\[D_C=DM_C\cdot (1+TIR_C)=5,311\cdot (1+0,02400)=5,4385\]</span></p>
<ul>
<li>A continuación tenemos que hallar las ponderaciones de los bonos dentro de la cartera (que denotaremos con el subíndice p, del inglés: <em>portfolio</em>).</li>
</ul>
<p><span class="math display">\[W_A=\frac{215}{1.096,71}\cdot792.969,05=29,74\%\]</span> <span class="math display">\[W_B=\frac{4}{56293}\cdot 792.969,05=28,40\%\]</span></p>
<p><span class="math display">\[W_C=\frac{280}{1.185,43}\cdot792.969,05=41,86\%\]</span></p>
<ul>
<li>Finalmente <strong>hallamos la Duración de la cartera como la suma ponderada de las Duraciones de cada uno de los bonos que la componen</strong>:</li>
</ul>
<p><span class="math display">\[D_P= W_A \cdot D_A + W_B \cdot D_B + W_C \cdot D_C\]</span></p>
<ul>
<li>donde al sustituir y calcular tenemos que:</li>
</ul>
<p><span class="math display">\[D_P= 0,2974 \cdot 2,0915 + 0,2840 \cdot 4,1119+0,4186\cdot 5,4385=4,066\]</span></p>
<p><strong>Apartado c</strong></p>
<ul>
<li>En este caso tenemos que indicar si la cartera “p” se encuentra inmunizada. Para ello <strong>aplicamos el teorema de inmunización</strong>:</li>
</ul>
<div class="rmdimportant">
<p>Según el <strong>teorema de inmunización</strong> de Fisher y Weil (1971) <strong>una cartera de bonos está inmunizada del riesgo de tipo de interés si la duración de la cartera es igual al horizonte temporal</strong> deseado de inversión.</p>
<p><a href="https://es.wikipedia.org/wiki/Inmunizaci%C3%B3n_(finanzas)">Más información aquí</a></p>
</div>
<ul>
<li>En este caso tenemos que la Duración de la cartera “Dp” es mayor que su horizonte temporal “HT”,</li>
</ul>
<p><span class="math display">\[D_P&gt;HT_P\]</span></p>
<p><span class="math display">\[4,066&gt;3\]</span></p>
<ul>
<li>luego tenemos que el <strong>Riesgo de precio será mayor que el Riesgo de Reinversión</strong>. Por lo tanto, cabe esperar que frente a incrementos en los tipos de interés, la rentabilidad de la cartera bajará y, frente a las bajadas de tipos la rentabilidad de la cartera aumentará.</li>
</ul>
<div class="rmdimportant">
<p>El riesgo de interés tiene dos componentes</p>
<p>– Riesgo de reinversión</p>
<p>– Riesgo de valor de mercado</p>
<p>Cuando el tipo de interés cambia, estos elementos de riesgo tienen un comportamiento contrario</p>
<p>– Un aumento de la rentabilidad mejora el valor de recuperación (el valor final de los pagos), pero empeora el precio</p>
<p>La cartera de “p”” estará inmunizada frente al riesgo de interés cuando su vencimiento (horizonte temporal) es igual a D (Duración)</p>
<p>– Entonces, su valor final es el mismo con independencia del comportamiento de los tipos de interés</p>
</div>
<p><strong>Apartado d</strong> * En primer lugar tenemos que <strong>calcular la Duración Modificada de la caretra</strong>, para ello bastará con hacer la <strong>suma ponderada de las duraciones modificadas</strong> de cada bono que compone la cartera “p”. De forma que:</p>
<p><span class="math display">\[DC_P= W_A \cdot DC_A + W_B \cdot DC_B + W_C \cdot DC_C\]</span></p>
<ul>
<li>donde al sustituir y calcular tenemos que:</li>
</ul>
<p><span class="math display">\[D_P= 0,2974 \cdot 2,051 + 0,2840 \cdot 4,030+0,4186\cdot 5,311=3,977\]</span></p>
<ul>
<li>Y, en último lugar, calculamos la variación en el precio ante un aumento de la TIR de 50 p.b.(recordad, cada punto porcentual contiene 100 puntos básicos):</li>
</ul>
<p><span class="math display">\[\frac{\Delta\ P}{P}=-D_{corregida}\cdot\Delta TIR=-3,977\cdot (+0.50\%)=-1,9885\% \]</span></p>
<ul>
<li>luego, podemos decir que <strong>la variación en el precio ante un aumento de la TIR de 50 p.b. será de -1,9885%</strong>.</li>
</ul>
</div>
</div>
</div>
</details>
<hr>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copiado");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copiado");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./caso-practicos_20.html" class="pagination-link">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text">Casos prácticos 2020</span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./caso-practicos_18.html" class="pagination-link">
        <span class="nav-page-text">Casos prácticos 2018</span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->



</body></html>