<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="es" xml:lang="es"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.2.269">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Certificación European Financial Advisor - EFA™  Asociación Europea de Planificación Financiera - EFPA™ - Casos prácticos 2021</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1.6em;
  vertical-align: middle;
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./caso-practicos_20.html" rel="next">
<link href="./ano_2016.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 20,
  "language": {
    "search-no-results-text": "Sin resultados",
    "search-matching-documents-text": "documentos encontrados",
    "search-copy-link-title": "Copiar el enlace en la búsqueda",
    "search-hide-matches-text": "Ocultar resultados adicionales",
    "search-more-match-text": "resultado adicional en este documento",
    "search-more-matches-text": "resultados adicionales en este documento",
    "search-clear-button-title": "Borrar",
    "search-detached-cancel-button-title": "Cancelar",
    "search-submit-button-title": "Enviar"
  }
}</script>

  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<link rel="stylesheet" href="styles.css">
</head>

<body class="nav-sidebar floating">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
    <div class="container-fluid d-flex justify-content-between">
      <h1 class="quarto-secondary-nav-title">Casos prácticos 2021</h1>
      <button type="button" class="quarto-btn-toggle btn" aria-label="Show secondary navigation">
        <i class="bi bi-chevron-right"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Certificación European Financial Advisor - EFA™ <br> Asociación Europea de Planificación Financiera - EFPA™</a> 
    </div>
      </div>
      <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
      </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link"><span class="smallcaps">INTRODUCCIÓN</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./preguntas-frecuentes.html" class="sidebar-item-text sidebar-link">Preguntas frecuentes</a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="true">EJERCICIOS RESUELTOS</a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="true">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./M1-test.html" class="sidebar-item-text sidebar-link">Módulo 1</a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./M2-test.html" class="sidebar-item-text sidebar-link">Módulo 2</a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./M3-test.html" class="sidebar-item-text sidebar-link">Módulo 3</a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./M4-test.html" class="sidebar-item-text sidebar-link">Módulo 4</a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./M5-test.html" class="sidebar-item-text sidebar-link">Módulo 5</a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./M6-test.html" class="sidebar-item-text sidebar-link">Módulo 6</a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./M7-test.html" class="sidebar-item-text sidebar-link">Módulo 7</a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./M8-test.html" class="sidebar-item-text sidebar-link">Módulo 8</a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./M9-test.html" class="sidebar-item-text sidebar-link">Módulo 9</a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./M10-test.html" class="sidebar-item-text sidebar-link">Módulo 10</a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" aria-expanded="true">EXÁMENES TEST</a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" aria-expanded="true">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./ano_2021.html" class="sidebar-item-text sidebar-link">Año 2021</a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./ano_2020.html" class="sidebar-item-text sidebar-link">Año 2020</a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./ano_2019.html" class="sidebar-item-text sidebar-link">Año 2019</a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./ano_2018.html" class="sidebar-item-text sidebar-link">Año 2018</a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./ano_2017.html" class="sidebar-item-text sidebar-link">Año 2017</a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./ano_2016.html" class="sidebar-item-text sidebar-link">Año 2016</a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" aria-expanded="true">EXÁMENES PRÁCTICA</a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" aria-expanded="true">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./caso-practicos_21.html" class="sidebar-item-text sidebar-link active">Casos prácticos 2021</a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./caso-practicos_20.html" class="sidebar-item-text sidebar-link">Casos prácticos 2020</a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./caso-practicos_19.html" class="sidebar-item-text sidebar-link">Casos prácticos 2019</a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./caso-practicos_18.html" class="sidebar-item-text sidebar-link">Casos prácticos 2018</a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Tabla de contenidos</h2>
   
  <ul>
  <li><a href="#renta-fija-valoración-dic-2021" id="toc-renta-fija-valoración-dic-2021" class="nav-link active" data-scroll-target="#renta-fija-valoración-dic-2021">Renta Fija (valoración) dic (2021)</a></li>
  <li><a href="#cobertura-con-futuros-dic-2021" id="toc-cobertura-con-futuros-dic-2021" class="nav-link" data-scroll-target="#cobertura-con-futuros-dic-2021">Cobertura con Futuros dic (2021)</a></li>
  <li><a href="#renta-variable-dic-2021" id="toc-renta-variable-dic-2021" class="nav-link" data-scroll-target="#renta-variable-dic-2021">Renta variable dic (2021)</a></li>
  <li><a href="#gestión-de-carteras-dic-2021" id="toc-gestión-de-carteras-dic-2021" class="nav-link" data-scroll-target="#gestión-de-carteras-dic-2021">Gestión de carteras dic (2021)</a></li>
  <li><a href="#fiscalidad-2021" id="toc-fiscalidad-2021" class="nav-link" data-scroll-target="#fiscalidad-2021">Fiscalidad (2021)</a></li>
  <li><a href="#renta-fija-2021" id="toc-renta-fija-2021" class="nav-link" data-scroll-target="#renta-fija-2021">Renta Fija (2021)</a></li>
  <li><a href="#performance-2021" id="toc-performance-2021" class="nav-link" data-scroll-target="#performance-2021">Performance 2021</a></li>
  <li><a href="#gestión-de-carteras-2021" id="toc-gestión-de-carteras-2021" class="nav-link" data-scroll-target="#gestión-de-carteras-2021">Gestión de carteras 2021</a></li>
  <li><a href="#renta-variable-nuevo" id="toc-renta-variable-nuevo" class="nav-link" data-scroll-target="#renta-variable-nuevo">Renta Variable (nuevo)</a></li>
  <li><a href="#performance-de-fondos-nuevo" id="toc-performance-de-fondos-nuevo" class="nav-link" data-scroll-target="#performance-de-fondos-nuevo">Performance de fondos (nuevo)</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title d-none d-lg-block">Casos prácticos 2021</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  

</header>

<section id="renta-fija-valoración-dic-2021" class="level2">
<h2 class="anchored" data-anchor-id="renta-fija-valoración-dic-2021">Renta Fija (valoración) dic (2021)</h2>
<p>Se dispone de la siguiente información relativa a un bono de la empresa ABC:</p>
<ul>
<li>Fecha Valor: 5/12/2021</li>
<li>Fecha de Vencimiento: 15/09/2025</li>
<li>Cupón anual: 2,25%</li>
<li>TIR: 3,25%</li>
<li>Nominal: 5.000 euros</li>
</ul>
<ol type="1">
<li>Hallar el precio del bono a 05-12-2021</li>
</ol>
<!-- -->
<ol type="a">
<li>4.971,75€</li>
<li>4.849,55€</li>
<li>4.696.90€</li>
</ol>
<!-- -->
<ol start="3" type="1">
<li>Calcule el importe que deberá integrarse en la base imponible de un contribuyente del IRPF que hubiese suscrito 10 bonos, como consecuencia de los siguientes hechos acaecidos en el Año X:</li>
</ol>
<ul>
<li>45-09-Año X: cobro del cupón anual</li>
<li>16-09-Año X: venta de los 10 bonos por 24.500 / bono</li>
<li>28-12-Año X: compra de 5 bonos de la misma emisión</li>
</ul>
<ol type="a">
<li>Base imponible = 3.125 - 5.000 = - 1.875</li>
<li>Base imponible = 3.125 - 2.500 = 625</li>
<li>Base imponible = 3.125</li>
</ol>
</section>
<section id="cobertura-con-futuros-dic-2021" class="level2">
<h2 class="anchored" data-anchor-id="cobertura-con-futuros-dic-2021">Cobertura con Futuros dic (2021)</h2>
<p>Un cliente a 30 de noviembre de 2021 mantenía una cartera de acciones de la bolsa española por valor de 2.535.327 euros. Ante la incierta situación de los mercados, decide hoy, 5 de diciembre del 2021, reducir el riesgo sistemático o de mercado de su cartera a cero, utilizando para ello contratos de futuros sobre el IBEX-35. El cliente desará su posición en la fecha de vencimiento del futuro, 18 de marzo. La situación de los mercados es la siguiente:</p>
<p>Al iniciar la operativa:</p>
<ul>
<li><p>IBEX-35 al contado: 8.241,70</p></li>
<li><p>Beta de la cartera 1,12</p></li>
<li><p>Futuro IBEX-35 vencimiento 17/12/2022 8.200</p></li>
<li><p>Futuro IBEX-35 vencimiento 18/03/2022 8.250</p></li>
</ul>
<p>(El tick del contrato es 1 punto y su valor monetario unitario es de 10 euros)</p>
<p>Al momento de cerrar su posición la situación del mercado era la siguiente (T= 18 de marzo):</p>
<ul>
<li>Valor efectivo de la cartera 1.950.324 euros</li>
<li>IBEX-35 al contado 6.557,34</li>
<li>Futuro IBEX35 mismo vencimiento que el contratado 6.560</li>
</ul>
<ol type="1">
<li>Determinar la ratio de cobertura.</li>
</ol>
<!-- -->
<ol type="a">
<li>Vender 30 contratos</li>
<li>Comprar 35 contratos</li>
<li>Vender 35 contratos</li>
</ol>
<details>
<summary>
</summary>
<div class="FOO callout-tip callout callout-style-simple">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-body-container">
<p>La respuesta <strong>correcta es la b</strong>.</p>
<p><span class="math display">\[RC=\frac{2535327\cdot 1.12}{8241.70\cdot 10}=34.45364\dots \:\approx 35\:\:\:\]</span></p>
</div>
</div>
</div>
</details>
<hr>
<ol start="2" type="1">
<li>Determinar el resultado bruto de la operación de cobertura con futuros (contado + cobertura),</li>
</ol>
<!-- -->
<ol type="a">
<li>Pérdida de 78.003 euros</li>
<li>Beneficio de 6.497 euros</li>
<li>Beneficio de 1.231 euros</li>
</ol>
<details>
<summary>
</summary>
<div class="FOO callout-tip callout callout-style-simple">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-body-container">
<p>La respuesta <strong>correcta es la b</strong>.</p>
<p>Con la venta de los contratos ingresa:</p>
<p><span class="math display">\[\left(8250-6560\right)\cdot \:35\cdot \:10=591500\]</span> Mientras que por la caída del precio de la cartera, pierde:</p>
<p><span class="math display">\[1950324-2535327=-585003\]</span> Así, el resultado bruto de la operación de cobertura con futuros (contado + cobertura) arroja un valor positivo de la operación iagual a:</p>
<p><span class="math display">\[591500-585003=6497\]</span></p>
</div>
</div>
</div>
</details>
<hr>
<ol start="3" type="1">
<li>Obtener la rentabilidad efectiva anualizada de la operación (contado-futuro) a la fecha de vencimiento.</li>
</ol>
<!-- -->
<ol type="a">
<li>0,23%</li>
<li>1,03%</li>
<li>1,34%</li>
</ol>
<details>
<summary>
</summary>
<div class="FOO callout-tip callout callout-style-simple">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-body-container">
<p>La respuesta <strong>correcta es la b</strong>.</p>
<p>La rentabilidad obtenida en los 97 días de la operación (un trimestre aproximadamente)</p>
<p><img src="images/paste-590A3F8C.png" width="288" height="149"></p>
<p>será de:</p>
<p><span class="math display">\[r_t=\frac{\left(2535327+6497\right)-2535327}{2535327}=0.002562(0.2562\%)\]</span></p>
<p>Que, igualmente podíamos haber obtenido el mismo resultado, simplemente poniendo en relación (cociente) lo que obtenemos, entre lo que desembolsamos inicialmente:</p>
<p><span class="math display">\[r_t=\frac{6497}{2535327}=0.002562(0.2562\%)\]</span></p>
<p>Para anualizar en capitalización compuesta, planteamos la siguiente equivalencia financiera:</p>
<p><span class="math display">\[\left(1+i\right)=\left(1+0.002562\right)^{4\:}=0.01028\left(\approx 1.03\%\right)\]</span></p>
</div>
</div>
</div>
</details>
<hr>
</section>
<section id="renta-variable-dic-2021" class="level2">
<h2 class="anchored" data-anchor-id="renta-variable-dic-2021">Renta variable dic (2021)</h2>
<p>Disponemos de los siguientes datos del balance de la compañía BETA, S.L.: (cifras en euros)</p>
<table class="table">
<thead>
<tr class="header">
<th>ACTIVO</th>
<th>AXO X</th>
<th>AXO X-1</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Inmuebles</td>
<td>2.700.000,00</td>
<td>2.145.000,00</td>
</tr>
<tr class="even">
<td>Equipos</td>
<td>975.000,00</td>
<td>754.000,00</td>
</tr>
<tr class="odd">
<td><strong>Activo Fijo</strong></td>
<td>3.675.000,00</td>
<td>2.899.000,00</td>
</tr>
<tr class="even">
<td>Inventario</td>
<td>975.000,00</td>
<td>806.000,00</td>
</tr>
<tr class="odd">
<td>Cuentas por cobrar</td>
<td>600.000,00</td>
<td>500.500.00</td>
</tr>
<tr class="even">
<td>Tesorería</td>
<td>1.125.000,00</td>
<td>806.000,00</td>
</tr>
<tr class="odd">
<td><strong>Activo corriente</strong></td>
<td>2.700.000,00</td>
<td>2.112.500,00</td>
</tr>
<tr class="even">
<td>TOTAL ACTIVO</td>
<td>6.375.000,00</td>
<td>5.011.500,00</td>
</tr>
<tr class="odd">
<td></td>
<td></td>
<td></td>
</tr>
<tr class="even">
<td>PASIVO</td>
<td>AXO X</td>
<td>AXO X-1</td>
</tr>
<tr class="odd">
<td>Capital Social</td>
<td>600.000,00</td>
<td>520.000,00</td>
</tr>
<tr class="even">
<td>Reservas</td>
<td>2 .700.000,00</td>
<td>2.223.000,00</td>
</tr>
<tr class="odd">
<td><strong>Fondos Propios</strong></td>
<td>3.300.000,00</td>
<td>2.743.000,00</td>
</tr>
<tr class="even">
<td>Deuda financiera</td>
<td>2.700.000,00</td>
<td>1.982.500,00</td>
</tr>
<tr class="odd">
<td>Acreedores C/P</td>
<td>375.000,00</td>
<td>286.000,00</td>
</tr>
<tr class="even">
<td>TOTAL PASIVO</td>
<td>6.375.000,00</td>
<td>5.011.500,00</td>
</tr>
</tbody>
</table>
<p>Adicionalmente, se conoce la siguiente información:</p>
<ul>
<li>El balance ha sido revisado, obteniéndose un informe favorable del auditor.</li>
<li>El Beneficio Neto para el Año X ha ascendido a 850.000 euros.</li>
<li>El pay-out de la empresa es del 60%.</li>
<li>La empresa BETA S.L. tiene 2.200.000 acciones en circulación.</li>
<li>El precio de la acción a fecha de hoy es de 6,50 euros/acción.</li>
<li>La rentabilidad de la renta fija (Obligaciones del Estado a 10 años) es del 0,75%.</li>
<li>La Sra. González es una accionista de la compañía que posee el 25% del capital social. Además, ejerce el cargo de directora general, percibiendo por ello una retribución que representa la totalidad de los rendimientos del Tiempo restante 1:09:17 en el IRPF.</li>
</ul>
<ol type="1">
<li>¿Cuál de las siguientes secuencias de ratios es a correcta?</li>
</ol>
<table class="table">
<thead>
<tr class="header">
<th></th>
<th style="text-align: center;">PER</th>
<th style="text-align: center;">PVC</th>
<th style="text-align: center;">EYG</th>
<th style="text-align: center;">DY</th>
<th style="text-align: center;">ROE</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>a</td>
<td style="text-align: center;">16,82</td>
<td style="text-align: center;">4,64</td>
<td style="text-align: center;">0,13</td>
<td style="text-align: center;">3,57%</td>
<td style="text-align: center;">27,60%</td>
</tr>
<tr class="even">
<td>b</td>
<td style="text-align: center;">16,82</td>
<td style="text-align: center;">0,22</td>
<td style="text-align: center;">0,13</td>
<td style="text-align: center;">5.94%</td>
<td style="text-align: center;">16,56%</td>
</tr>
<tr class="odd">
<td>c</td>
<td style="text-align: center;">28,04</td>
<td style="text-align: center;">4,64</td>
<td style="text-align: center;">0,04</td>
<td style="text-align: center;">3,57%</td>
<td style="text-align: center;">16,56%</td>
</tr>
</tbody>
</table>
<ol type="a">
<li><p>Secuencia a.</p></li>
<li><p>Secuencia b.</p></li>
<li><p>Secuencia c.</p></li>
</ol>
<details>
<summary>
</summary>
<div class="FOO callout-tip callout callout-style-simple">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-body-container">
<p>La respuesta <strong>correcta es la</strong> .</p>
</div>
</div>
</div>
</details>
<hr>
<ol start="2" type="1">
<li>Basándose en los resultados obtenidos, y teniendo en cuenta que los siguientes datos corresponden a la media del sector, determinar, con base en la información suministrada, si es compañía. adecuado invertir en acciones de esta</li>
</ol>
<p>Datos del sector:</p>
<ul>
<li>PER = 17,00</li>
<li>Precio sobre valor contable (PVC) = 5,50</li>
<li>Rentabilidad sobre fondos propios (ROE) 25,00%</li>
</ul>
<ol type="a">
<li><p>Es adecuado</p></li>
<li><p>No es adecuado</p></li>
<li><p>Es indiferente</p></li>
</ol>
<details>
<summary>
</summary>
<div class="FOO callout-tip callout callout-style-simple">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-body-container">
<p>La respuesta <strong>correcta es la</strong> .</p>
</div>
</div>
</div>
</details>
<hr>
<ol start="3" type="1">
<li>Indique cuál de las siguientes afirmaciones es correcta en relación con la declaración de las acciones de la Sra. González en el Impuesto sobre el Patrimonio correspondiente al Año X:</li>
</ol>
<!-- -->
<ol type="a">
<li>La Sra. González NO puede aplicar sobre las acciones que posee en la compañía BETA S.L. la exención prevista por el artículo 4.0cho.Dos de la Ley 19/1991, de 6 de junio, del Impuesto sobre el Patrimonio.</li>
</ol>
<ul>
<li>Valor sujeto a gravamen: 825.000 euros</li>
</ul>
<ol start="2" type="a">
<li>La Sra. González puede aplicar sobre las acciones que posee en la compañía BETA S.L. la exención prevista por el artículo 4.0cho.Dos de la Ley 19/1991, de 6 de junio, del Impuesto sobre el Patrimonio en los siguientes términos:</li>
</ol>
<ul>
<li>Valor exento de gravamen: 825.000 euros</li>
</ul>
<ol start="3" type="a">
<li>La Sra. González puede aplicar sobre las acciones que posee en a compañía BETA S.L. la exención prevista por el artículo 4.0cho. Dos de la Ley 19/1991, de 6 de junio, del Impuesto sobre el Patrimonio en los siguientes términos:</li>
</ol>
<ul>
<li>Valor exento de gravamen: 618.750 euros</li>
<li>Valor sujeto a gravamen: 206.250 euros</li>
</ul>
<details>
<summary>
</summary>
<div class="FOO callout-tip callout callout-style-simple">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-body-container">
<p>La respuesta <strong>correcta es la</strong> .</p>
</div>
</div>
</div>
</details>
<hr>
</section>
<section id="gestión-de-carteras-dic-2021" class="level2">
<h2 class="anchored" data-anchor-id="gestión-de-carteras-dic-2021">Gestión de carteras dic (2021)</h2>
<p>Una vez establecido el horizonte temporal del cliente y su propensión al riesgo, usted ha decido crearle una cartera con la siguiente distribución: 60% renta variable y 40% renta fija.</p>
<p>Después de un riguroso proceso de análisis de fondos de inversión, ha decidido por un fondo de renta variable global y un fondo de renta fija a largo plazo cuyas estadísticas para los últimos tres años son las siguientes:</p>
<table class="table">
<colgroup>
<col style="width: 31%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 16%">
</colgroup>
<thead>
<tr class="header">
<th></th>
<th>Rentabilidad acumulada</th>
<th>Volatilidad anualizada</th>
<th>Beta</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Fondo RV Eurozona</td>
<td>27%</td>
<td>15%</td>
<td>0,9</td>
</tr>
<tr class="even">
<td>Indice de RV Eurozona</td>
<td>25%</td>
<td>12%</td>
<td></td>
</tr>
<tr class="odd">
<td>Fondo RF Europa largo plazo</td>
<td>5%</td>
<td>5% 5% 0,7</td>
<td>0,7</td>
</tr>
<tr class="even">
<td>indice RF Europa largo plazo</td>
<td>3%</td>
<td>3%</td>
<td></td>
</tr>
</tbody>
</table>
<ol type="1">
<li>Si para el próximo año la rentabilidad esperada del mercado de renta variable es del 20% y del de renta fija es del 7%; ¿cuál será la rentabilidad esperada de la cartera?</li>
</ol>
<!-- -->
<ol type="a">
<li>12,20%</li>
<li>14,80%</li>
<li>5,92%</li>
</ol>
<details>
<summary>
</summary>
<div class="FOO callout-tip callout callout-style-simple">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-body-container">
<p>La respuesta <strong>correcta es la</strong> .</p>
</div>
</div>
</div>
</details>
<hr>
<ol start="2" type="1">
<li>Si esperamos que la volatilidad se mantenga constante y e coeficiente de correlación entre los fondos escogidos es del 0,40, ¿cuál será la volatilidad de la cartera para el próximo año?</li>
</ol>
<!-- -->
<ol type="a">
<li>7,71%</li>
<li>0,99%</li>
<li>9,97%</li>
</ol>
<details>
<summary>
</summary>
<div class="FOO callout-tip callout callout-style-simple">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-body-container">
<p>La respuesta <strong>correcta es la</strong> .</p>
</div>
</div>
</div>
</details>
<hr>
<ol start="3" type="1">
<li>Su cliente está interesado en adquirir 250.000 euros de un ETF de futuros del Bitcoin y no dispone de la suficiente liquidez para su compra. Para ello, acude a su entidad bancaria en busca de financiación. La propuesta que le hace la entidad bancaria es la siguiente:</li>
</ol>
<ul>
<li>Préstamo de 150.000 euros</li>
<li>Período a 48 meses</li>
<li>Tipo de interés nominal 2,5%</li>
<li>Comisión de apertura : 0,20%</li>
</ul>
<p>¿Cuál es la TAE de la operación de financiación que la entidad Bancaria le ofrece a su cliente?</p>
<ol type="a">
<li>2,70%</li>
<li>2,63%</li>
<li>2,55%</li>
</ol>
<details>
<summary>
</summary>
<div class="FOO callout-tip callout callout-style-simple">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-body-container">
<p>La respuesta <strong>correcta es la</strong> .</p>
</div>
</div>
</div>
</details>
<hr>
</section>
<section id="fiscalidad-2021" class="level2">
<h2 class="anchored" data-anchor-id="fiscalidad-2021">Fiscalidad (2021)</h2>
<p>A comienzos del ejercicio 2021 el Sr.&nbsp;García, un contribuyente del IRPF, es titular de las siguientes inversiones:</p>
<ul>
<li><p>10.000 acciones de la Empresa “A”, que fueron adquiridas en el año 2018 a un precio de 10 euros acción.</p></li>
<li><p>1.000.000 de acciones de la Empresa “B”, que fueron adquiridas en la herencia de su madre, y que se que se valoraron a efectos del Impuesto sobre Sucesiones y Donaciones por 2.500.000 euros.</p></li>
</ul>
<p>En relación con la inversión mantenida en la Empresa “A”, se sabe que dicha empresa ha llevado a cabo en el año 2021 una ampliación de capital mediante la entrega de acciones liberadas, ofreciendo 1 acción nueva por cada 4 antiguas.</p>
<p><strong>Preguntas</strong></p>
<ol type="1">
<li>Si el Sr.&nbsp;García decidiera no acudir a la ampliación liberada ya que la cotización de las acciones de la Empresa “A” está bajando mucho y optase por vender sus 10.000 derechos de suscripción por importe de 0,20 euros cada uno, ¿cuál sería el tratamiento fiscal aplicable?</li>
</ol>
<!-- -->
<ol type="a">
<li><p>El Sr.&nbsp;García obtendría una ganancia patrimonial por importe de 2.000 euros, importe que integrar en la base imponible general del IRPF, ya que los derechos de suscripción permanecen en su patrimonio menos de un año.</p></li>
<li><p>El Sr.&nbsp;García obtendría una ganancia patrimonial por importe de 2.000 euros, que debería integrar en la base imponible del ahorro del IRPF.</p></li>
<li><p>La venta de derechos de suscripción minoraría el coste de adquisición de las acciones de las que proceden los derechos transmitidos.</p></li>
</ol>
<details>
<summary>
</summary>
<div class="FOO callout-tip callout callout-style-simple">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-body-container">
<p>La respuesta <strong>correcta es la b</strong>.</p>
<h5 class="anchored">
<strong>¿Qué consecuencias fiscales tengo en una ampliación de capital con mis acciones?</strong>
</h5>
<p>En caso de una ampliación de capital, se pueden dar tres situaciones.</p>
<ul>
<li><p>La <strong>primera</strong> es que el contribuyente acuda a la misma y obtenga acciones totalmente liberadas de tal modo que la adquisición de nuevas acciones no afectaría a su declaración de IRPF, en tanto no las transmita.</p></li>
<li><p>La <strong>segunda</strong> es que no acuda a la ampliación ni venda los derechos de suscripción, de tal modo que si la empresa que amplía capital compra a un precio fijo los derechos que no se ejerciten, renunciando a ampliar capital por los derechos adquiridos, la compensación que recibirá el contribuyente se calificaría como dividendo y tendrá la consideración de rendimiento del capital mobiliario.</p></li>
<li><p>Por <strong>último</strong>, si <strong>el contribuyente no acude a la ampliación de capital y vende en el mercado los derechos de suscripción, dicha transmisión generará una ganancia patrimonial que también tributará en la base del ahorro a los tipos señalados más abajo.</strong></p></li>
</ul>
<h5 class="anchored">
<strong>Tipos de gravamen del ahorro en el IRPF</strong>
</h5>
<p>Con efectos desde 1 de enero de 2021, se modifica la escala que se aplica a la parte de la base liquidable del ahorro para determinar la cuota íntegra estatal añadiéndose un nuevo tramo a la parte de la base liquidable del ahorro que exceda de 200.000 <strong>euros al que se aplicará un tipo del 26,00%</strong></p>
<p>Así, en este caso, la escala aplicable a la base liquidable del ahorro del Sr.&nbsp;García será la siguiente:</p>
<table class="table">
<colgroup>
<col style="width: 28%">
<col style="width: 16%">
<col style="width: 33%">
<col style="width: 19%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: center;"><p><strong>Base l iquidable del ahorro</strong></p>
<p><strong>Hasta euros</strong></p></th>
<th style="text-align: center;"><p><strong>Cuota íntegra</strong></p>
<p><strong>Euros</strong></p></th>
<th style="text-align: center;"><p><strong>Resto base l iquidable del ahorro</strong></p>
<p><strong>Hasta euros</strong></p></th>
<th style="text-align: center;"><p><strong>Tipo a p licable</strong></p>
<ul>
<li></li>
</ul>
<p>*Po r c e ntaje**</p></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">0</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">6.000</td>
<td style="text-align: center;">19</td>
</tr>
<tr class="even">
<td style="text-align: center;">6.000,00</td>
<td style="text-align: center;">1.140</td>
<td style="text-align: center;">44.000</td>
<td style="text-align: center;">21</td>
</tr>
<tr class="odd">
<td style="text-align: center;">50.000,00</td>
<td style="text-align: center;">10.380</td>
<td style="text-align: center;">150.000</td>
<td style="text-align: center;">23</td>
</tr>
<tr class="even">
<td style="text-align: center;">2 00.000,00</td>
<td style="text-align: center;">44.880</td>
<td style="text-align: center;">En adelante</td>
<td style="text-align: center;">26</td>
</tr>
</tbody>
</table>
<p>(Se modifican los artículos 66 y 76 de la LIRPF por el artículo 59 de la LPGE para 2021).</p>
<p><a href="https://novedades-fiscalidad-2021.netlify.app">Novedades fiscales 2021 (acreditaciones oficiales de EFPA España)</a></p>
</div>
</div>
</div>
</details>
<hr>
<ol start="2" type="1">
<li>Si el Sr.&nbsp;García decidiera acudir a la ampliación liberada y posteriormente vendiera todas sus acciones de la Empresa “A” a 12 euros/acción, ¿a cuánto ascendería la ganancia patrimonial obtenida?</li>
</ol>
<!-- -->
<ol type="a">
<li><p>10.000 x (12 - 8) = 40.000</p></li>
<li><p>10.000 X (12 - 10) = 20.000</p></li>
<li><p>12.500 X (12 - 8) = 50.000</p></li>
</ol>
<details>
<summary>
</summary>
<div class="FOO callout-tip callout callout-style-simple">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-body-container">
<p>La respuesta <strong>correcta es la c</strong>.</p>
<p>Ahora tenemos que recordar que tras la ampliación de capital que se llevado a cabo en el año 2021 (entrega de acciones liberadas, ofreciendo 1 acción nueva por cada 4 antiguas), el Sr.&nbsp;García tendrá en su patrimonio un total de acciones de la Empresa “A” de:</p>
<p><span class="math display">\[
N_{acciones}=10000+\frac{10000}{4}=12500
\]</span></p>
<p>12.500 acciones. Y, cuyo precio unitario resultante tras la operación será de:</p>
<p><span class="math display">\[
P=\frac{10000\cdot \:10}{12500}=8
\]</span></p>
<p>De forma que, si vende las 12.500 acciones que posee a un precio de 12 euros/acción, la ganancia patrimonial obtenida, y que por lo tanto que debería integrar en la base imponible del ahorro del IRPF ascendería a un importe total de 50.000 euros:</p>
<p><span class="math display">\[BIA=12500 \cdot (12 - 8) = 50.000\]</span> Donde de nuevo, la escala aplicable a la base liquidable del ahorro del Sr.&nbsp;García, para la referida BIA de 50.000 euros sería la siguiente:</p>
<table class="table">
<colgroup>
<col style="width: 28%">
<col style="width: 16%">
<col style="width: 33%">
<col style="width: 19%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: center;"><p><strong>Base l iquidable del ahorro</strong></p>
<p><strong>Hasta euros</strong></p></th>
<th style="text-align: center;"><p><strong>Cuota íntegra</strong></p>
<p><strong>Euros</strong></p></th>
<th style="text-align: center;"><p><strong>Resto base l iquidable del ahorro</strong></p>
<p><strong>Hasta euros</strong></p></th>
<th style="text-align: center;"><p><strong>Tipo a p licable</strong></p>
<ul>
<li></li>
</ul>
<p>*Po r c e ntaje**</p></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">0</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">6.000</td>
<td style="text-align: center;">19</td>
</tr>
<tr class="even">
<td style="text-align: center;">6.000,00</td>
<td style="text-align: center;">1.140</td>
<td style="text-align: center;">44.000</td>
<td style="text-align: center;">21</td>
</tr>
<tr class="odd">
<td style="text-align: center;">50.000,00</td>
<td style="text-align: center;">10.380</td>
<td style="text-align: center;">150.000</td>
<td style="text-align: center;">23</td>
</tr>
<tr class="even">
<td style="text-align: center;">2 00.000,00</td>
<td style="text-align: center;">44.880</td>
<td style="text-align: center;">En adelante</td>
<td style="text-align: center;">26</td>
</tr>
</tbody>
</table>
<p>Donde se aprecia que el tipo máximo al que tributará será el 21%, y siendo por tanto su cuota integra de 1.140 (por el tramos del 19%) + 10.380 (por el tramos del 21%)</p>
<p><a href="https://novedades-fiscalidad-2021.netlify.app">Novedades fiscales 2021 (acreditaciones oficiales de EFPA España)</a></p>
</div>
</div>
</div>
</details>
<hr>
<ol start="3" type="1">
<li>¿Qué coste fiscal correspondería en el IRPF del año 2021 del Sr.&nbsp;García si la Empresa “B” distribuyera un dividendo de 100.000 euros?</li>
</ol>
<!-- -->
<ol type="a">
<li><p>100.000 x 23% = 23.000 euros</p></li>
<li><p>Base liquidable = 100.000;</p>
<p>Hasta 50.000 euros = 10.380 euros;</p>
<p>Resto, 50.000 euros al 23% = 11.500 euros;</p>
<p>Suma: 21.880 euros</p></li>
<li><p>Los dividendos procedentes de acciones adquiridas por herencia están exentos.</p></li>
</ol>
<details>
<summary>
</summary>
<div class="FOO callout-tip callout callout-style-simple">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-body-container">
<p>La respuesta <strong>correcta es la b</strong>.</p>
<p>En este caso tenemos que para una base liquidable de 100.000 en el ejercicio fiscal 2021, se aplican los siguientes tramos de la base imponible del ahorro</p>
<table class="table">
<colgroup>
<col style="width: 28%">
<col style="width: 16%">
<col style="width: 33%">
<col style="width: 19%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: center;"><p><strong>Base l iquidable del ahorro</strong></p>
<p><strong>Hasta euros</strong></p></th>
<th style="text-align: center;"><p><strong>Cuota íntegra</strong></p>
<p><strong>Euros</strong></p></th>
<th style="text-align: center;"><p><strong>Resto base l iquidable del ahorro</strong></p>
<p><strong>Hasta euros</strong></p></th>
<th style="text-align: center;"><p><strong>Tipo a p licable</strong></p>
<ul>
<li></li>
</ul>
<p>*Po r c e ntaje**</p></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">0</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">6.000</td>
<td style="text-align: center;">19</td>
</tr>
<tr class="even">
<td style="text-align: center;">6.000,00</td>
<td style="text-align: center;">1.140</td>
<td style="text-align: center;">44.000</td>
<td style="text-align: center;">21</td>
</tr>
<tr class="odd">
<td style="text-align: center;">50.000,00</td>
<td style="text-align: center;">10.380</td>
<td style="text-align: center;">150.000</td>
<td style="text-align: center;">23</td>
</tr>
<tr class="even">
<td style="text-align: center;">2 00.000,00</td>
<td style="text-align: center;">44.880</td>
<td style="text-align: center;">En adelante</td>
<td style="text-align: center;">26</td>
</tr>
</tbody>
</table>
<p>que aplicados a nuestro caso, quedaría del siguiente modo:</p>
<p>Base liquidable = 100.000;</p>
<ul>
<li><p>Hasta 6.000 euros 1.140 euros;</p></li>
<li><p>Hasta 44.000 euros = 9.240 euros;</p></li>
<li><p>Resto, 50.000 euros al 23% = 11.500 euros;</p></li>
<li><p><strong>Suma: 21.880 euros</strong></p></li>
</ul>
<p><strong>Normativa: Art. 46 Ley IRPF</strong></p>
<p>Las ganancias y pérdidas patrimoniales que se pongan de manifiesto con ocasión de transmisiones de elementos patrimoniales integran la base imponible del ahorro.</p>
<p><strong>Normativa: Art. 49, disposición adicional trigésimo novena.1; y disposición transitoria séptima.5 Ley IRPF</strong></p>
<p>La integración y compensación de rentas en la base imponible del ahorro se realiza, en dos fases: la primera tiene por objeto determinar la base imponible del ahorro obtenida en el propio período impositivo y, la segunda compensación con el saldo positivo, en su caso, obtenido, las partidas negativas hechos de ejercicios anteriores que están pendientes de compensación.</p>
<p><a href="https://novedades-fiscalidad-2021.netlify.app">Novedades fiscales 2021 (acreditaciones oficiales de EFPA España)</a></p>
</div>
</div>
</div>
</details>
<hr>
<ol start="4" type="1">
<li>¿Qué ganancia de patrimonio tendría que declarar el Sr.&nbsp;García si decidiese vender las acciones de la Empresa “B” por 3.000.000 de euros?</li>
</ol>
<!-- -->
<ol type="a">
<li>500.000 euros</li>
<li>1.000.000 de euros</li>
<li>12.500 x (12 - 8) = 50.000</li>
</ol>
<details>
<summary>
</summary>
<div class="FOO callout-tip callout callout-style-simple">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-body-container">
<p>La respuesta <strong>correcta es la a</strong>.</p>
<p>La venta de acciones tributa en la base del ahorro como una ganancia o pérdida patrimonial,</p>
<p>PLUSVALÍA = VALOR DE TRASMISIÓN – VALOR DE ADQUISICIÓN</p>
<p>El <strong>valor de trasmisión</strong> se computa con el precio de venta (3.000.000) menos los gastos que hayamos asumido (en este caso no nos dicen que haya comisiones, canon de bolsa, etc) para realizar dicha trasmisión.</p>
<p>El <strong>valor de adquisición</strong> se computa con el precio de compra (2.500.000 euros) y se suman los gastos (no nos dicen que haya gastos de venta):</p>
<p><span class="math display">\[BIA=3.000.000-2.500.000= 500.000\]</span></p>
<p><a href="https://novedades-fiscalidad-2021.netlify.app">Novedades fiscales 2021 (acreditaciones oficiales de EFPA España)</a></p>
</div>
</div>
</div>
</details>
<hr>
</section>
<section id="renta-fija-2021" class="level2">
<h2 class="anchored" data-anchor-id="renta-fija-2021">Renta Fija (2021)</h2>
<p>Disponemos de la siguiente información relativa a un bono de la empresa DELTA</p>
<ul>
<li>NOMINAL 100.000 EUR</li>
<li>CUPON ANUAL 4,50</li>
<li>TIR A VENCIMIENTO 5%</li>
<li>FECHA VALOR 1-08-2021</li>
<li>FECHA VENCMIENTO 31-12-2024</li>
</ul>
<ol type="1">
<li>Hallar el precio del bono a 1-08-2021</li>
</ol>
<!-- -->
<ol type="a">
<li><p>101063,9461</p></li>
<li><p>100660,8685</p></li>
<li><p>102432,2342</p></li>
</ol>
<details>
<summary>
</summary>
<div class="FOO callout-tip callout callout-style-simple">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-body-container">
<p>La respuesta <strong>correcta es la a</strong>.</p>
<p>En primer lugar tenemos que calcular el precio entero de este bono. Para ello utilizaremos la siguiente metodología de cálculo:</p>
<p><span class="math display">\[P_0=\sum_{ t=1}^{ n}\frac{F_t}{(1+r)^{t}}\]</span></p>
<p>donde,</p>
<ul>
<li><p><span class="math inline">\(P_0\)</span>, es el precio entero de un bono o valor actual del mismo (<span class="math inline">\(V_0\)</span>).</p></li>
<li><p><span class="math inline">\(F_t\)</span>, Flujos a percibir por la tenencia de un bono (cupón y principal).</p></li>
<li><p><span class="math inline">\(r\)</span>, es la TIR.</p></li>
<li><p><span class="math inline">\(t\)</span>, es el tiempo.</p></li>
</ul>
<p>Donde si sustituimos por los datos del problema y calculamos, tenemos que el precio actual (a fecha 1-08-2021) del bono es de:</p>
<p><span class="math display">\[P_{(1-08-21)}=\frac{4500}{\left(1+0.05\right)^{\frac{152}{365}}}+\frac{4500}{\left(1+0.05\right)^{1+\frac{152}{365}}}+\frac{4500}{\left(1+0.05\right)^{2+\frac{152}{365}}}+\frac{104500}{\left(1+0.05\right)^{3+\frac{152}{365}}}\]</span> <span class="math display">\[P_{(1-08-21)}=101063.94618\]</span></p>
</div>
</div>
</div>
</details>
<hr>
<ol start="2" type="1">
<li>Calcular la duración del bono</li>
</ol>
<!-- -->
<ol type="a">
<li><p>3,16286</p></li>
<li><p>3,85122</p></li>
<li><p>4,02241</p></li>
</ol>
<details>
<summary>
</summary>
<div class="FOO callout-tip callout callout-style-simple">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-body-container">
<p>La respuesta <strong>correcta es la a</strong>.</p>
<p>En este caso para calcular la Duración de Macaulay (o simplemente, la “Duración”), vamos a realizar el siguiente cálculo:</p>
<p><span class="math display">\[D=\frac{\sum_{t=1}^{n}\frac{F_t\cdot t}{\left(1+r\right)^t}}{P}\]</span></p>
<p>donde,</p>
<ul>
<li><p><span class="math inline">\(D\)</span>, Duración de Macaulay.</p></li>
<li><p><span class="math inline">\(F_t\)</span>, Flujos a percibir por la tenencia de un bono (cupón y principal).</p></li>
<li><p><span class="math inline">\(P\)</span>, es el precio entero de un bono o valor actual del mismo (<span class="math inline">\(V_0\)</span>).</p></li>
<li><p><span class="math inline">\(r\)</span>, es la TIR.</p></li>
<li><p><span class="math inline">\(t\)</span>, es el tiempo.</p></li>
</ul>
<p>De manera que si sustituimos por los datos del problema y calculamos, tenemos que la Duración del bono es de:</p>
<p><span class="math display">\[D=\frac{\left(\frac{152}{365}\right)\frac{4500}{\left(1+0.05\right)^{\frac{152}{365}}}+\left(1+\frac{152}{365}\right)\frac{4500}{\left(1+0.05\right)^{1+\frac{152}{365}}}+\left(2+\frac{152}{365}\right)\frac{4500}{\left(1+0.05\right)^{2+\frac{152}{365}}}+\left(3+\frac{152}{365}\right)\frac{104500}{\left(1+0.05\right)^{3+\frac{152}{365}}}}{101063.94618}\]</span></p>
<p><span class="math display">\[D=3.162\]</span></p>
</div>
</div>
</div>
</details>
<hr>
<ol start="3" type="1">
<li>Si la TIR sube 40 p.b. calcular el nuevo precio del bono</li>
</ol>
<!-- -->
<ol type="a">
<li><p>99142,747</p></li>
<li><p>101025,372</p></li>
<li><p>99846.562</p></li>
</ol>
<details>
<summary>
</summary>
<div class="FOO callout-tip callout callout-style-simple">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-body-container">
<p>La respuesta <strong>correcta es la c</strong>.</p>
<p>En primer lugar calculamos la duración corregida a partir de la duración que hemos calculado en el apartado anterior:</p>
<p><span class="math display">\[D_{corregida}=\frac{Duracion\,de\, Macaulay}{\left(1+TIR\right)}=\frac{D}{\left(1+TIR\right)} \]</span> De forma que nuestra duración corregida será:</p>
<p><span class="math display">\[D_{corregida}=\frac{3.162}{1+0.05}=3.01142\]</span> Para estimar la variación del precio ante variaciones en la TIR emplearemos la siguiente expresión,</p>
<p><span class="math display">\[P_1\simeq P_0\cdot\left[1+((-D_{corregida})\cdot\Delta TIR)\right]\]</span></p>
<p>donde,</p>
<ul>
<li><p><span class="math inline">\(P_1\)</span>, es el precio estimado del bono ante una variación de la TIR.</p></li>
<li><p><span class="math inline">\(P_0\)</span>, es el precio actual del bono .</p></li>
<li><p><span class="math inline">\(D_{corregida}\)</span>, es la duración corregida.</p></li>
</ul>
<p>Si sustituimos por los datos del problema y calculamos, tenemos que el nuevo precio del bono ante una subida de la TIR sube de 40 p.b. será de:</p>
<p><span class="math display">\[P_1\simeq 101063.94618\left(1+\left(\left(-3.01142\right)\cdot \:0.004\right)\right)=99846.56222\]</span></p>
</div>
</div>
</div>
</details>
<hr>
</section>
<section id="performance-2021" class="level2">
<h2 class="anchored" data-anchor-id="performance-2021">Performance 2021</h2>
<p>Un cliente está considerando realizar una inversión en fondos de Renta Variable Americana. El cliente desea saber su opinión de en cuál de los dos siguientes fondos debería invertir.</p>
<table class="table">
<colgroup>
<col style="width: 17%">
<col style="width: 13%">
<col style="width: 13%">
<col style="width: 22%">
<col style="width: 30%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: center;"></th>
<th style="text-align: center;"><strong>Fondo A</strong></th>
<th style="text-align: center;"><strong>Fondo B</strong></th>
<th style="text-align: center;"><strong>Índice de Mercado</strong></th>
<th style="text-align: center;"><strong>Activo libre de riesgo</strong> *</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">Re ntabilidad *</td>
<td style="text-align: center;">19,50</td>
<td style="text-align: center;">16,60</td>
<td style="text-align: center;">15,00</td>
<td style="text-align: center;">1,25</td>
</tr>
<tr class="even">
<td style="text-align: center;">V olatilidad *</td>
<td style="text-align: center;">10,15</td>
<td style="text-align: center;">11,20</td>
<td style="text-align: center;">10,30</td>
<td style="text-align: center;">0,00</td>
</tr>
<tr class="odd">
<td style="text-align: center;">Beta</td>
<td style="text-align: center;">0,75</td>
<td style="text-align: center;">0,95</td>
<td style="text-align: center;">1,00</td>
<td style="text-align: center;">0,00</td>
</tr>
</tbody>
</table>
<p>*<em>Rentabilidad anualizada a 3 años</em></p>
<p>*<em>Rentabilidad del bono EE.UU a 10 años</em></p>
<p>Se pide:</p>
<ol type="1">
<li>Calculara el Ratio de Sharpe para cada uno de los fondos.</li>
</ol>
<!-- -->
<ol type="a">
<li><p>Fondo A = 1,74 y Fondo B = 1,20</p></li>
<li><p>Fondo A : 0,24 y Fondo B = 0,16</p></li>
<li><p>Fondo A = 1,80 y Fondo B = 1,37</p></li>
</ol>
<details>
<summary>
</summary>
<div class="FOO callout-tip callout callout-style-simple">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-body-container">
<p>La respuesta <strong>correcta es la c</strong>.</p>
<p>Nos piden calcular el ratio de Sharpe,</p>
<p><span class="math display">\[S_p=\frac{E_p-R_f}{\ \sigma_p}\]</span></p>
<p>Donde,</p>
<ul>
<li><p><span class="math inline">\(S_p\)</span>, es ratio de Sharpe.</p></li>
<li><p><span class="math inline">\(E_p\)</span>, es la rentabilidad esperada de la cartera <span class="math inline">\(p\)</span>.</p></li>
<li><p><span class="math inline">\(R_f\)</span>, es la rentabilidad del activo sin riego.</p></li>
<li><p><span class="math inline">\(\sigma_p\)</span>, es la volatilidad (riesgo) de la cartera <span class="math inline">\(p\)</span>.</p></li>
</ul>
<p>De forma que sustituimos los datos y calculamos:</p>
<p><span class="math display">\[S_A=\frac{0.195-0.0125}{0.1015}=1.7980\]</span> <span class="math display">\[S_A=\frac{0.166-0.0125}{0.1120}=1.3705\]</span></p>
<p>Del valor numérico del ratio de Sharpe podemos extraer algunas conclusiones. En términos de rentabilidad, mientras mayor sea el índice de Sharpe, mejor es la rentabilidad del fondo comparado directamente a la cantidad de riesgo que se ha asumido en la inversion. Si el índice o ratio de Sharpe es negativo, indica un rendimiento inferior a la rentabilidad sin riesgo. Todo ratio de Sharpe inferior a uno significa que el rendimiento del activo es inferior al riesgo que estamos asumiendo al invertir en un activo determinado. Cuando la volatilidad del fondo de inversión es grande, asumimos más riesgo y por ende el ratio de Sharpe será menor, a no ser que el rendimiento del fondo en concreto compense esa mayor rentabilidad.</p>
</div>
</div>
</div>
</details>
<hr>
<ol start="2" type="1">
<li>Calcular el Ratio de Información para cada uno de los fondos.</li>
</ol>
<!-- -->
<ol type="a">
<li><p>Fondo A = 1,10 y Fondo B = 0,50</p></li>
<li><p>Fondo A = 1,25 y Fondo B = 0,43</p></li>
<li><p>Fondo A = 0,52 y Fondo B 1,35</p></li>
</ol>
<details>
<summary>
</summary>
<div class="FOO callout-tip callout callout-style-simple">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-body-container">
<p>La respuesta <strong>correcta es la b</strong>.</p>
<p><span class="math display">\[RI=\frac{\alpha_p}{\sigma_{\alpha,p}}=\frac{E_p-\beta _p\:\cdot \:E_m}{\sqrt{\sigma _p^2-\beta _p^2\cdot \:\sigma _m^2}}\]</span></p>
<p>Donde,</p>
<ul>
<li><p><span class="math inline">\(\alpha_p\)</span>, es el alfa de la cartera <span class="math inline">\(p\)</span>.</p></li>
<li><p><span class="math inline">\(\sigma_{\alpha,p}\)</span>, es la desviación típica (volatilidad o riesgo) del alfa respecto de la cartera <span class="math inline">\(p\)</span>.</p></li>
</ul>
<p>De forma que sus sustituimos y calculamos obtenemos que el rating información para el fondo a es de:</p>
<p><span class="math display">\[RI_A=\frac{0.195-0.75\cdot \:0.15}{\sqrt{0.1015^2-0.75^2\cdot \:0.103^2}}=1.25306\dots \]</span></p>
<p><span class="math display">\[RI_B=\frac{0.166-0.95\cdot \:0.15}{\sqrt{0.112^2-0.95^2\cdot \:0.103^2}}=0.43125\dots \]</span></p>
<p>El resultado del Information Ratio refleja cuanta rentabilidad de más obtiene el fondo o cartera (respecto a su índice de referencia) por una unidad de riesgo de desviación del índice de referencia (que es el Tracking Error). Cuanto mayor sea este Ratio mejor.</p>
</div>
</div>
</div>
</details>
<hr>
<ol start="3" type="1">
<li>Calcular el Alfa de Jensen para cada uno de los fondos.</li>
</ol>
<!-- -->
<ol type="a">
<li><p>Fondo A = 3,29 y Fondo B = 7,94</p></li>
<li><p>Fondo A = 3,25 y Fondo B = -0,50</p></li>
<li><p>Fondo A = 7,94 y Fondo B = 2,29</p></li>
</ol>
<details>
<summary>
</summary>
<div class="FOO callout-tip callout callout-style-simple">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-body-container">
<p>La respuesta <strong>correcta es la c</strong>.</p>
<p>Tenemos que calcular el alfa de Jensen con la siguiente expresión:</p>
<p><span class="math display">\[\alpha_J=R_p-\left[R_f+\left(E_m-R_f\right)\cdot\beta_p\right]\]</span> Donde,</p>
<ul>
<li><p><span class="math inline">\(\alpha_J\)</span>, es el alpha de Jensen.</p></li>
<li><p><span class="math inline">\(R_p\)</span>, es la rentabilidad obtenida de la cartera <span class="math inline">\(p\)</span>.</p></li>
<li><p><span class="math inline">\(R_f\)</span>, es la rentabilidad del activo sin riego.</p></li>
<li><p><span class="math inline">\(\beta_p\)</span>, es la beta (sensibilidad a los movimientos del mercado) de la cartera <span class="math inline">\(p\)</span>.</p></li>
</ul>
<p>De forma que, para el fondo A tenemos tenemos que</p>
<p><span class="math display">\[\alpha_J^{A}=0.195-\left(0.0125+\left(0.15-0.0125\right)\cdot \:0.75\right)=0.079375\]</span> y para el fondo B,</p>
<p><span class="math display">\[\alpha_J^{B}=0.166-\left(0.0125+\left(0.15-0.0125\right)\cdot \:0.95\right)=0.022875\]</span></p>
<p>El Alpha de Jensen representa, en términos absolutos, la diferencia entre la rentabilidad obtenida por una cartera y la que debería obtener en función del nivel de beta asumido según la SML:</p>
<p>Comparando varias carteras de activos para <span class="math inline">\(\alpha&gt;0\)</span> la cartera está infravalorada y representa una oportunidad de inversión; para <span class="math inline">\(\alpha&lt;0\)</span> la cartera está sobrevalorada y por tantnto no ofrece suficiente renrtabilidad a los inversores racionales para aceptar su nivel de riesgo sistemático.</p>
<p>De forma que este alfa se obtinen de igualar a cero la ecuación del CAPM (SML):</p>
<p><span class="math display">\[R_p=\left[R_f+\left(E_m-R_f\right)\cdot\beta_p\right]\]</span></p>
<p><span class="math display">\[0=E_p-\left[R_f+\left(E_m-R_f\right)\cdot\beta_p\right]\]</span></p>
<p><span class="math display">\[\alpha_J=R_p-\left[R_f+\left(E_m-R_f\right)\cdot\beta_p\right]\]</span></p>
</div>
</div>
</div>
</details>
<hr>
</section>
<section id="gestión-de-carteras-2021" class="level2">
<h2 class="anchored" data-anchor-id="gestión-de-carteras-2021">Gestión de carteras 2021</h2>
<table class="table">
<colgroup>
<col style="width: 27%">
<col style="width: 25%">
<col style="width: 22%">
<col style="width: 22%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: center;">Acciones</th>
<th style="text-align: center;">Rentabilidad</th>
<th style="text-align: center;">Volatilidad</th>
<th style="text-align: center;">Covarianza</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;"><pre><code>ABC</code></pre></td>
<td style="text-align: center;">7,50%</td>
<td style="text-align: center;">8,00%</td>
<td style="text-align: center;">0,00576</td>
</tr>
<tr class="even">
<td style="text-align: center;">GHI</td>
<td style="text-align: center;">16,25%</td>
<td style="text-align: center;">20,00%</td>
<td style="text-align: center;">0,0204</td>
</tr>
<tr class="odd">
<td style="text-align: center;">Índice de Mercado</td>
<td style="text-align: center;">12,00%</td>
<td style="text-align: center;">12,00%</td>
<td style="text-align: center;"></td>
</tr>
<tr class="even">
<td style="text-align: center;">Activo sin riesgo</td>
<td style="text-align: center;">4,00%</td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
</tr>
</tbody>
</table>
<p>Se pide:</p>
<ol type="1">
<li>Calcular la rentabilidad esperada y la volatilidad de una cartera compuesta por el 75% de acciones ABC y el acciones GHI, sabiendo que la correlación entre ambas acciones es de 0,50</li>
</ol>
<!-- -->
<ol type="a">
<li><p>Rentabilidad = 10,09% y Volatilidad = 10,02%</p></li>
<li><p>Rentabilidad = 9,70% y Volatilidad = 9,54%</p></li>
<li><p>Rentabilidad = 9,25% y Volatilidad = 9,50%</p></li>
</ol>
<details>
<summary>
</summary>
<div class="FOO callout-tip callout callout-style-simple">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-body-container">
<p>La respuesta <strong>correcta es la b</strong>.</p>
<p>En primer lugar vamos a calcular la rentabilidad esperada de una cartera con la siguiente fórmula:</p>
<p><span class="math display">\[E_p=w_1\cdot E_1+w_2\cdot E_2+...+w_n\cdot E_n\]</span></p>
<p>Donde,</p>
<ul>
<li><p><span class="math inline">\(E_p\)</span>, es la rentabilidad esperada de la cartera.</p></li>
<li><p><span class="math inline">\(w_n\)</span>, es la ponderación (o proporción) del activo <span class="math inline">\(n\)</span> dentro de la cartera.</p></li>
<li><p><span class="math inline">\(E_n\)</span>, es rentabilidad esperada del activo <span class="math inline">\(n\)</span>.</p></li>
</ul>
<p>Así, si sustituimos los valores del enunciado en la fórmula anterior tenemos que:</p>
<p><span class="math display">\[E_p=0.75\cdot \:0.075+0.25\cdot \:0.1625=0.096875(9.70\%)\]</span> Para calcular el riesgo (Volatilidad) de la cartera tenemos que escribir la volatilidad de la cartera en <strong>función del coeficiente de correlación</strong> que nos dice el enunciado que es del (<span class="math inline">\(\rho=0.5\)</span>):</p>
<p><span class="math display">\[\sigma_p=\sqrt{w_{1}^2\cdot\sigma_1^2+w_2^2\cdot\sigma_2^2+2\cdot w_1\cdot w_2\cdot\rho_{1,2}\cdot\sigma_{1}\cdot\sigma_{2}}\]</span></p>
<p>Donde,</p>
<ul>
<li><p><span class="math inline">\(\sigma_p\)</span>, es la volatilidad (riesgo) de la cartera <span class="math inline">\(p\)</span>.</p></li>
<li><p><span class="math inline">\(w_1\)</span>, es la ponderación (o proporción) del activo <span class="math inline">\(1\)</span> dentro de la cartera <span class="math inline">\(p\)</span>.</p></li>
<li><p><span class="math inline">\(\sigma_1\)</span>, es la volatilidad del título <span class="math inline">\(1\)</span>.</p></li>
<li><p><span class="math inline">\(w_2\)</span>, es la ponderación (o proporción) del activo <span class="math inline">\(2\)</span> dentro de la cartera <span class="math inline">\(p\)</span>.</p></li>
<li><p><span class="math inline">\(\sigma_2\)</span>, es la volatilidad del título <span class="math inline">\(2\)</span>.</p></li>
<li><p><span class="math inline">\(\rho_{1,2}\)</span>, es el coeficiente de correlación entre los activos 1 y 2.</p></li>
</ul>
<p>De forma que si ahora sustituimos y calculamos, tenemos que:</p>
<p><span class="math display">\[\sigma_p=\sqrt{0.75^2\cdot \:0.08^2+0.25^2\cdot \:0.2^2+2\cdot \:0.25\cdot \:0.75\cdot \:0.08\cdot \:0.2\cdot \:0.5}\]</span></p>
<p><span class="math display">\[\sigma_p=0.09539(9.54\%) \]</span></p>
</div>
</div>
</div>
</details>
<hr>
<ol start="2" type="1">
<li>Calcular las betas de las acciones ABC y GHI</li>
</ol>
<!-- -->
<ol type="a">
<li><p>Beta ABC = 0,20 y Beta GHI = 1,22</p></li>
<li><p>Beta ABC = 0,30 y Beta GHI = 1,20</p></li>
<li><p>Beta ABC = 0,40 y Beta GHI = 1,42</p></li>
</ol>
<details>
<summary>
</summary>
<div class="FOO callout-tip callout callout-style-simple">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-body-container">
<p>La respuesta <strong>correcta es la c</strong>.</p>
<p>Nos piden calcular la beta de un activo y NO de la cartera:</p>
<p>Tenemos que darnos cuenta de que en este caso la vamos a calcular con laco varianza, y por lo tanto utilizaremos la primera expresión de las dos que tenemos a continuación:</p>
<p><span class="math display">\[\beta_{i,m}=\frac{\sigma_{i,m}}{\sigma_m^2}=\frac{\sigma_i}{\sigma_m}\cdot\rho_{i,m}\]</span></p>
<p>Donde,</p>
<ul>
<li><p><span class="math inline">\(\beta_{i, m}\)</span>, es la beta del activo <span class="math inline">\(i\)</span> respecto del mercado <span class="math inline">\(m\)</span>.</p></li>
<li><p><span class="math inline">\(\sigma_{i,m}\)</span>, es la covarianza entre las rentabilidades del activo <span class="math inline">\(i\)</span> y el mercado <span class="math inline">\(m\)</span>.</p></li>
<li><p><span class="math inline">\(\sigma_m^2\)</span>, es la varianza del mercado <span class="math inline">\(m\)</span>.</p></li>
<li><p><span class="math inline">\(\sigma_i\)</span>, es la volatilidad del activo <span class="math inline">\(i\)</span>.</p></li>
<li><p><span class="math inline">\(\sigma_m\)</span>, es la volatilidad del mercado <span class="math inline">\(m\)</span>.</p></li>
<li><p><span class="math inline">\(\rho_{i,m}\)</span>, es el coeficiente de correlación entre el activo <span class="math inline">\(i\)</span> y el mercado <span class="math inline">\(m\)</span>.</p></li>
</ul>
<p>De forma que si sustituimos y calculamos la <strong>beta de la empresa ABC</strong>:</p>
<p><span class="math display">\[\beta_{ABC, m}=\frac{0.00576}{0.12^2}=0.4\]</span></p>
<p>y para la <strong>empresa GHI</strong>:</p>
<p><span class="math display">\[\beta_{GHI, m}=\frac{0.0204}{0.12^2}=1.416(\approx1.42) \]</span></p>
<p>El coeficiente beta del activo i representa la variación que, por término medio, experimenta la rentabilidad del activo i respecto a una variación unitaria en la rentabilidad del índice de referencia (o mercado).</p>
<table class="table">
<colgroup>
<col style="width: 19%">
<col style="width: 20%">
<col style="width: 59%">
</colgroup>
<thead>
<tr class="header">
<th>Clasificación del activo</th>
<th>Valor de beta</th>
<th>Interpretación</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>DEFENSIVO</td>
<td><span class="math inline">\(-1&lt;\beta&lt;1\)</span></td>
<td>Son activos poco arriesgados, ya que en proporción varían menos que el índice.</td>
</tr>
<tr class="even">
<td>AGRESIVO</td>
<td><span class="math inline">\(\beta&gt;1\ o \ \beta &lt; -1\)</span></td>
<td>Son activos poco arriesgados, ya que en proporción varían menos que el índice.</td>
</tr>
<tr class="odd">
<td>NEUTRO</td>
<td><span class="math inline">\(\beta=1\ o \ \beta=-1\)</span></td>
<td>Son activos poco arriesgados, ya que en proporción varían menos que el índice.</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
</details>
<hr>
</section>
<section id="renta-variable-nuevo" class="level2">
<h2 class="anchored" data-anchor-id="renta-variable-nuevo">Renta Variable (nuevo)</h2>
<p>Dispones del balance de una compañía (cifras en euros):</p>
<p><img src="images/Captura de pantalla 2021-02-19 a las 23.24.43.png" class="img-fluid"></p>
<ul>
<li><p>El Beneficio Neto para el año X ha ascendido a 685.000 euros</p></li>
<li><p>El pay-out de la empresa es del 35%</p></li>
<li><p>La capitalización bursátil es de 6.576.000 euros</p></li>
<li><p>Tiene 1.500.000 acciones en circulación</p></li>
<li><p>EI precio de la acción a fecha de hoy es de 4,38 euros/acciones</p></li>
<li><p>La rentabilidad de la renta fija (Obligaciones del Estado a 10 años) es del 1,31%</p></li>
</ul>
<p>Se pide:</p>
<p>1. Calcular los siguientes ratios bursátiles para el año X:</p>
<ul>
<li><p>Precio sobre valor contable (PVC)</p></li>
<li><p>Earnings yield gap</p></li>
</ul>
<p>a. PVC = 1,54 y EYG = 8,10</p>
<p>b. PVC = 2,29 y EYG = 9,75</p>
<p>c. PVC = 2,99 y EYG = 9,10</p>
<details>
<summary>
</summary>
<p>La respuesta <strong>correcta es la c</strong></p>
<p>En primer lugar el valor contable,</p>
<p>El <strong>valor contable</strong> de una acción es la <strong>cantidad de Patrimonio Neto o Recursos Propios que le corresponde a cada acción.</strong> Para su cálculo simplemente se divide el total del patrimonio neto de la empresa (capital social más reservas o también llamado recursos propios) entre el número de acciones. De forma que si:</p>
<p><span class="math display">\[
V.Contable=\frac{Fondos \ propios}{Nº \ acciones}
\]</span></p>
<p>tenemos que, para el año X,</p>
<p><span class="math display">\[
V.Contable=\frac{2.200.000}{1.500.000}=1,4667
\]</span></p>
<p>Una vez que tenemos calculado el valor contable podemos calcular cuál será el <strong>PVC</strong> (“Price to Book Value” o “P/BV” del inglés). Este ratio bursátil que <strong>mide la relación entre el precio al que cotizan las acciones con el valor de sus fondos propios</strong>, es decir, el valor contable de sus activos menos el valor contable de sus deudas.</p>
<p><span class="math display">\[
PVC=\frac{PPA}{V.Contable}
\]</span></p>
<p>tenemos que, para el año X,</p>
<p><span class="math display">\[
PVC=\frac{4,38}{1,4467}=2,99
\]</span></p>
<p>A continuación vamos a calcular el <strong>PER (acrónimo del inglés de: Price Earning Ratio). Este ratio mide la relación entre el precio en bolsa de una acción y los beneficios que obtiene año tras año.</strong></p>
<p>En este caso en lugar del precio tomaremos la capitalización bursátil, y en lugar del beneficio por acción, utilizaremos el beneficio neto o beneficio después de impuestos. Ya que podemos emplear para hacer estos cálculos tanto, como un valor unitario por acción o como el agregado del total de la empresa:</p>
<p><span class="math display">\[
PER=\frac{C.Bursatil}{BDI}
\]</span></p>
<p>tenemos que, para el año X,</p>
<p><span class="math display">\[
PER=\frac{6.576.000}{685.000}=9.6
\]</span></p>
<p>Conocido el PER podemos calcular <strong>Earnings yield gap (EYG). Esto es un modelo de valoración del mercado bursátil basado en la comparación de dos ratios de rentabilidad: la rentabilidad de los beneficios con la rentabilidad de la renta fija a largo plazo</strong> (Obligaciones del Estado a 10 años, en nuestro caso).</p>
<p>qué será:</p>
<p><span class="math display">\[
EYR=\frac{1}{PER}-R_f
\]</span></p>
<p>así tenemos para el año X,</p>
<p><span class="math display">\[
EYR=\frac{1}{9.6}-0.0131=0.0910(9.10\%)
\]</span></p>
</details>
<hr>
<p>2. Calcular los siguientes ratios bursátiles para el año X:</p>
<ul>
<li><p>Dividend yield</p></li>
<li><p>Rentabilidad sobre fondos propios (ROE)</p></li>
</ul>
<p>a. DY = 3,64 y ROE = 31,13</p>
<p>b. DY = 5,21 y ROE = 32,05</p>
<p>c. DY = 5,21 y ROE = 31,13</p>
<details>
<summary>
</summary>
<div class="FOO callout-tip callout callout-style-simple">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-body-container">
<p>La respuesta <strong>correcta es la a</strong></p>
<p>Nos piden el <strong>Dividend yield, es decir, la rentabilidad por dividendo</strong> (RD). Este ratio relaciona los dividendos anuales estimados por acción (DPA) y el precio de la acción (<span class="math inline">\(P_0\)</span>):</p>
<p><span class="math display">\[
Dividend \ Yield (RD)=\frac{DPA}{P_o}
\]</span></p>
<p>Para ello vamos a <strong>calcular, en primer lugar, el dividendo por acción (DPA),</strong> que es el numerador de la expresión anterior. Para ello bastará multiplicar el pay-out, proporción de beneficios que la compañía reparte a los accionistas en forma de dividendos por el beneficio por acción:</p>
<p><span class="math display">\[
DPA = BPA \cdot pay-out
\]</span></p>
<p><strong>para obtener el DPA</strong>, tenemos <strong>calcular también el beneficio por acción. Lo podemos hacer a través del PER</strong>, de la siguiente manera:</p>
<p><span class="math display">\[
BPA=\frac{P_0}{PER}
\]</span></p>
<p>así, el calculo quedará</p>
<p><span class="math display">\[
BPA=\frac{4.38}{9.6}=0.45625
\]</span></p>
<p><span class="math display">\[
DPA = 0.45625 \cdot 0.35=0.1596
\]</span></p>
<p>finalmente el <strong>Dividend yiel será,</strong></p>
<p><span class="math display">\[
Dividend \ Yield (RD)=\frac{0.1596}{4.38}=0.03644
\]</span></p>
<p>Ahora vamos a calcular el la rentabilidad sobre fondos propios, ROE (del ingés Return on Equity). La rentabilidad sobre fondos propios es el resultado de dividir los beneficios netos después de impuestos (BDI) de la empresa entre el valor de los fondos propios de la empresa:</p>
<p><span class="math display">\[
ROE=\frac{BDI}{FP}
\]</span></p>
<p>donde calculamos,</p>
<p><span class="math display">\[
ROE=\frac{685.000}{2.200.000}=31.13\%
\]</span></p>
</div>
</div>
</div>
</details>
<hr>
<p>3. Basándose en los resultados obtenidos y teniendo en cuenta que los siguientes datos corresponden a la media del sector, determinar, con base a la información suministrada, si es adecuado invertir en acciones de esta compañía.</p>
<p>Datos del sector</p>
<ul>
<li><p>PER = 12,50</p></li>
<li><p>Precio sobre valor contable (PVC) = 3,12</p></li>
<li><p>Rentabilidad sobre fondos propios (ROE) = 28,00%</p></li>
</ul>
<p>a. Si, porque está infravalorado</p>
<p>b. No, porque está sobrevalorado</p>
<p>c. No podemos responder porque nos falta | tasa de crecimiento de los dividendos</p>
<details>
<summary>
</summary>
<div class="FOO callout-tip callout callout-style-simple">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-body-container">
<p>La respuesta <strong>correcta es la a</strong></p>
<p>Con base a la información suministrada, es adecuado invertir en acciones de esta compañía:</p>
<table class="table">
<thead>
<tr class="header">
<th></th>
<th>PER</th>
<th>PVC</th>
<th>ROE</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>SECTOR</td>
<td>12,50</td>
<td>3,12</td>
<td>28,00%</td>
</tr>
<tr class="even">
<td>EMPRESA</td>
<td>9,6</td>
<td>2,99</td>
<td>31,13</td>
</tr>
</tbody>
</table>
<p>Interesa porque el <strong>PER es menor</strong> de forma que tardaré menos años en recuperar mi inversión, también es algo <strong>menor el PVC</strong> (Cuanto más baja sea la ratio, más atractiva nos resultará la empresa) y el <strong>ROE es mayor</strong> (es decir, obtendremos una mayor ROE es la rentabilidad financiera de la empresa que del sector): Claramente interesa invertir en en ella.</p>
</div>
</div>
</div>
</details>
<hr>
</section>
<section id="performance-de-fondos-nuevo" class="level2">
<h2 class="anchored" data-anchor-id="performance-de-fondos-nuevo">Performance de fondos (nuevo)</h2>
<p>Un cliente dispone de una cartera compuesta por tres fondos de inversión en las siguientes proporciones:</p>
<ul>
<li><p>Fondo A: 30%</p></li>
<li><p>Fondo B: 30%</p></li>
<li><p>Fondo C: 40%</p></li>
</ul>
<p>En la siguiente tabla se recogen las rentabilidades anuales que en los últimos cuatro años han ofrecido los tres fondos:</p>
<table class="table">
<thead>
<tr class="header">
<th></th>
<th><em>FI A</em></th>
<th><em>FI B</em></th>
<th><em>FI C</em></th>
<th><em>Índice de mercado</em></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong><em>Año 2007</em></strong></td>
<td>-4%</td>
<td>3%</td>
<td>6%</td>
<td>1,5%</td>
</tr>
<tr class="even">
<td><strong><em>Año 2006</em></strong></td>
<td>2%</td>
<td>3%</td>
<td>5%</td>
<td>3%</td>
</tr>
<tr class="odd">
<td><strong><em>Año 2005</em></strong></td>
<td>7%</td>
<td>-3%</td>
<td>10%</td>
<td>4%</td>
</tr>
<tr class="even">
<td><strong><em>Año 2004</em></strong></td>
<td>10%</td>
<td>2,5%</td>
<td>9%</td>
<td>7%</td>
</tr>
<tr class="odd">
<td><strong><em>Beta</em></strong></td>
<td>0,8</td>
<td>0,7</td>
<td>1,25</td>
<td>1</td>
</tr>
</tbody>
</table>
<p>1. Calcular la rentabilidad obtenida por la cartera de fondos del cliente en los últimos cuatro años, suponiendo que se mantiene la inversión inicial sin ningún tipo de operación</p>
<p>a. 4,25%</p>
<p>b. 4,47%</p>
<p>c. 4,98%</p>
<details>
<summary>
</summary>
<p>La respuesta <strong>correcta es la b</strong></p>
<p><strong>Para calcular la rentabilidad histórica</strong> de una cartera empleamos la siguiente expresión:</p>
<p><span class="math display">\[R_p=w_1\cdot R_1+w_2\cdot R_2+...+w_n\cdot R_n\]</span></p>
<p>donde,</p>
<ul>
<li><p><span class="math inline">\(R_p\)</span>, es la rentabilidad obtenida por la cartera.</p></li>
<li><p><span class="math inline">\(w_n\)</span>, es la ponderación (o proporción) del activo <span class="math inline">\(n\)</span> dentro de la cartera.</p></li>
<li><p><span class="math inline">\(RS_n\)</span>, es rentabilidad simple (o geométrica) del activo <span class="math inline">\(n\)</span>.</p></li>
</ul>
<p>Así que <strong>lo primero que haremos será calcular la rentabilidad</strong></p>
<p><strong>geométrica de cada uno de los tres fondos, a partir de las rentabilidades simples de cada subperiodo, es decir, las rentabilidades simples anuales obtenidas en el pasado por el fondo</strong>:</p>
<p>para el Fondo A,</p>
<p><span class="math display">\[
TGR_A=\sqrt[4]{\left(1-0.04\right)\left(1+0.02\right)\left(1+0.07\right)\left(1+0.1\right)}-1=0.03612(3.62\%)
\]</span></p>
<p>Fondo B,</p>
<p><span class="math display">\[
TGR_B=\sqrt[4]{\left(1+0.03\right)\left(1+0.03\right)\left(1-0.03\right)\left(1+0.025\right)}-1=0.01342(1.342\%)
\]</span></p>
<p>y Fondo C,</p>
<p><span class="math display">\[
TGR_C=\sqrt[4]{\left(1+0.06\right)\left(1+0.05\right)\left(1+0.1\right)\left(1+0.09\right)}-1=0.07480(7,48\%)
\]</span></p>
<p>De forma que si calculamos, con estos datos, la rentabilidad esperada de la cartera (que llamaremos p de forma genérica) tenemos que,</p>
<p><span class="math display">\[
R_p=0.3\cdot0.03612+0.3\cdot 0.01342+0.4\cdot 0.0748=0.044782(4.47\%)
\]</span></p>
<p>Así podemos concluir que la cartera ha logrado una rentabilidad total acumulada, en los últimos cuatro años, y asumiendo que se mantiene la inversión inicial sin ningún otro tipo de operación, del 20% aproximadamente. Es decir, que si invirtió 100 hace 4 años, habrá ganado casi un 20% en ese período, que anualizado es, aproximadamente, del 4,5%.</p>
</details>
<hr>
<p>2. Calcular cuál seria la rentabilidad teórica de la cartera del cliente según el modelo CAPM, teniendo en cuenta que el tipo de interés libre de riesgo es del 0,50%</p>
<p>a. 3,60%</p>
<p>b. 3,81%</p>
<p>c. 3,70%</p>
<details>
<summary>
</summary>
<div class="FOO callout-tip callout callout-style-simple">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-body-container">
<p>La respuesta <strong>correcta es la c</strong></p>
<p>Este caso tenemos que calcular la rentabilidad esperada de la cartera a través de la CML</p>
<p><span class="math display">\[E_p=R_f+(E_m-R_f)\cdot\beta_p\]</span></p>
<p>Donde,</p>
<ul>
<li><p><span class="math inline">\(E_p\)</span>, es la rentabilidad esperada del título <span class="math inline">\(i\)</span>.</p></li>
<li><p><span class="math inline">\(R_f\)</span>, es la rentabilidad del activo sin riego.</p></li>
<li><p><span class="math inline">\(E_m\)</span>, es la rentabilidad esperada de la cartera de mercado.</p></li>
<li><p><span class="math inline">\(\beta_i\)</span>, es la beta del título <span class="math inline">\(i\)</span>.</p></li>
</ul>
<p>En este caso tenemos que calcular en primer lugar la rentabilidad esperada del mercado, de forma análoga a como lo hemos hecho en el apartado anterior:</p>
<p><span class="math display">\[
TGR_m=\sqrt[4]{\left(1+0.015\right)\left(1+0.03\right)\left(1+0.04\right)\left(1+0.07\right)}-1=0.03855(3.855\%)
\]</span></p>
<p>en segundo lugar calcularemos la beta de la cartera. Para ello bastará a hacer la siguiente operación:</p>
<p><span class="math display">\[\beta_p=w_1\cdot\beta_1+w_2\cdot\beta_2+...+w_n\cdot\beta_n\]</span></p>
<p>Donde,</p>
<ul>
<li><p><span class="math inline">\(\beta_p\)</span>, es la beta de la cartera (o fondo) <span class="math inline">\(p\)</span>.</p></li>
<li><p><span class="math inline">\(w_n\)</span>, es la ponderación del activo <span class="math inline">\(n\)</span> dentro de la de cartera de activos <span class="math inline">\(p\)</span>.</p></li>
<li><p><span class="math inline">\(\beta_n\)</span>, es la beta del activo <span class="math inline">\(n\)</span>.</p></li>
</ul>
<p><span class="math display">\[
\beta_p=0.3\cdot \:0.8+0.3\cdot \:0.7+0.4\cdot \:1.25=0.95
\]</span></p>
<p>Una vez que tenemos calculada la beta de la cartera, a partir de la SML, calculamos:</p>
<p><span class="math display">\[
E_p=0.005+\left(0.03855-0.005\right)\cdot \:0.95=0.0368725(3.70\%)
\]</span></p>
</div>
</div>
</div>
</details>
<hr>
<p>3. Con base en las respuestas anteriores, calcular el alfa de Jensen de la cartera de fondos durante el periodo analizado</p>
<p>a. 0,67%</p>
<p>b. 0,80%</p>
<p>c. 0,75%</p>
<details>
<summary>
</summary>
<div class="FOO callout-tip callout callout-style-simple">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-body-container">
<p>La respuesta <strong>correcta es la b</strong></p>
<p><span class="math display">\[
\alpha_J=R_p-\left[R_f+\left(E_m-R_f\right)\cdot\beta_p\right]
\]</span></p>
<p>Donde,</p>
<ul>
<li><p><span class="math inline">\(\alpha_J\)</span>, es el alpha de Jensen.</p></li>
<li><p><span class="math inline">\(R_p\)</span>, es la rentabilidad obtenida de la cartera <span class="math inline">\(p\)</span>.</p></li>
<li><p><span class="math inline">\(R_f\)</span>, es la rentabilidad del activo sin riego.</p></li>
<li><p><span class="math inline">\(\beta_p\)</span>, es la beta (sensibilidad a los movimientos del mercado) de la cartera <span class="math inline">\(p\)</span>.</p></li>
</ul>
<p><span class="math display">\[
\alpha_J=0.044782-\left[0.005+\left(0.03855-0.005\right)\cdot 0.95\right]=0.0079095(0.80\%)
\]</span></p>
</div>
</div>
</div>
</details>
<hr>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copiado");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copiado");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./ano_2016.html" class="pagination-link">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text">Año 2016</span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./caso-practicos_20.html" class="pagination-link">
        <span class="nav-page-text">Casos prácticos 2020</span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->



</body></html>