<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="es" xml:lang="es"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.2.269">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Certificación European Financial Advisor - EFA™  Asociación Europea de Planificación Financiera - EFPA™ - Módulo 8</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1.6em;
  vertical-align: middle;
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./M9-test.html" rel="next">
<link href="./M7-test.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 20,
  "language": {
    "search-no-results-text": "Sin resultados",
    "search-matching-documents-text": "documentos encontrados",
    "search-copy-link-title": "Copiar el enlace en la búsqueda",
    "search-hide-matches-text": "Ocultar resultados adicionales",
    "search-more-match-text": "resultado adicional en este documento",
    "search-more-matches-text": "resultados adicionales en este documento",
    "search-clear-button-title": "Borrar",
    "search-detached-cancel-button-title": "Cancelar",
    "search-submit-button-title": "Enviar"
  }
}</script>

  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<link rel="stylesheet" href="styles.css">
</head>

<body class="nav-sidebar floating">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
    <div class="container-fluid d-flex justify-content-between">
      <h1 class="quarto-secondary-nav-title">Módulo 8</h1>
      <button type="button" class="quarto-btn-toggle btn" aria-label="Show secondary navigation">
        <i class="bi bi-chevron-right"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Certificación European Financial Advisor - EFA™ <br> Asociación Europea de Planificación Financiera - EFPA™</a> 
    </div>
      </div>
      <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
      </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link"><span class="smallcaps">INTRODUCCIÓN</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./preguntas-frecuentes.html" class="sidebar-item-text sidebar-link">Preguntas frecuentes</a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="true">EJERCICIOS RESUELTOS</a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="true">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./M1-test.html" class="sidebar-item-text sidebar-link">Módulo 1</a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./M2-test.html" class="sidebar-item-text sidebar-link">Módulo 2</a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./M3-test.html" class="sidebar-item-text sidebar-link">Módulo 3</a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./M4-test.html" class="sidebar-item-text sidebar-link">Módulo 4</a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./M5-test.html" class="sidebar-item-text sidebar-link">Módulo 5</a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./M6-test.html" class="sidebar-item-text sidebar-link">Módulo 6</a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./M7-test.html" class="sidebar-item-text sidebar-link">Módulo 7</a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./M8-test.html" class="sidebar-item-text sidebar-link active">Módulo 8</a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./M9-test.html" class="sidebar-item-text sidebar-link">Módulo 9</a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./M10-test.html" class="sidebar-item-text sidebar-link">Módulo 10</a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" aria-expanded="true">EXÁMENES TEST</a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" aria-expanded="true">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./dic_22.html" class="sidebar-item-text sidebar-link">Diciembre 2022</a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./sep_22.html" class="sidebar-item-text sidebar-link">Septiembre 2022</a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" aria-expanded="true">EXÁMENES PRÁCTICA</a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" aria-expanded="true">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./caso-dic_22.html" class="sidebar-item-text sidebar-link">Caso diciembre 2022</a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./caso-sep_22.html" class="sidebar-item-text sidebar-link">Caso septiembre 2022</a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Tabla de contenidos</h2>
   
  <ul>
  <li><a href="#fiscalidad" id="toc-fiscalidad" class="nav-link active" data-scroll-target="#fiscalidad">Fiscalidad</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title d-none d-lg-block">Módulo 8</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  

</header>

<section id="fiscalidad" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="fiscalidad">Fiscalidad</h2>
<ol type="1">
<li>¿Cuáles son los tipos mínimo y máximo de la escala progresiva de gravamen del IRPF en su base general?:</li>
</ol>
<!-- -->
<ol type="a">
<li><p>Mínimo 19% y máximo 45%.</p></li>
<li><p>Mínimo 18% y máximo 45%.</p></li>
<li><p>Mínimo 24% y máximo 43%.</p></li>
<li><p>Mínimo 24.75% y máximo 52%.</p></li>
</ol>
<details>
<summary>
</summary>
<div class="FOO callout-tip callout callout-style-simple">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-body-container">
<p>La respuesta <strong>correcta es la a</strong>.</p>
<p>La distribución de las tablas de IRPF para 2016 es la siguiente:</p>
<ul>
<li><p>de 0 a 12.450 € – 19%</p></li>
<li><p>de 12.451 a 20.200 € – 24%</p></li>
<li><p>de 20.201 a 35.200 € – 30%</p></li>
<li><p>de 35.201 a 60.000€ – 37%</p></li>
<li><p>Más de 60.001 € – 45%</p></li>
</ul>
</div>
</div>
</div>
</details>
<hr>
<ol start="2" type="1">
<li>¿Qué nombre reciben las aportaciones realizadas a planes de pensiones, más los rendimientos obtenidos por las inversiones del patrimonio del fondo de pensiones y menos los gastos producidos?</li>
</ol>
<!-- -->
<ol type="a">
<li><p>Acciones o participaciones, según el tipo de inversiones del fondo de pensiones.</p></li>
<li><p>Participaciones del plan de pensiones.</p></li>
<li><p>Derechos consolidados.</p></li>
<li><p>Participaciones preferentes.</p></li>
</ol>
<details>
<summary>
</summary>
<div class="FOO callout-tip callout callout-style-simple">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-body-container">
<p>La respuesta <strong>correcta es la C</strong>.</p>
<p>Podemos definir los derechos consolidados de un plan de pensiones como aquellos derechos económicos pertenecientes al partícipe y que son resultado de las aportaciones realizadas así como de los rendimientos producidos en las mismas y que se derivan del sistema financiero de capitalización.</p>
</div>
</div>
</div>
</details>
<hr>
<ol start="3" type="1">
<li>Indique cuál de las siguientes afirmaciones es correcta:</li>
</ol>
<!-- -->
<ol type="a">
<li><p>El IRPF es un impuesto indirecto que grava la renta cuando la misma se consume por el contribuyente.</p></li>
<li><p>El IRPF es un impuesto directo que grava la renta obtenida por el contribuyente con progresividad.</p></li>
<li><p>El IRPF es un impuesto directo que grava las rentas del ahorro a un tipo fijo, no progresivo.</p></li>
<li><p>Ninguna de las anteriores.</p></li>
</ol>
<details>
<summary>
</summary>
<div class="FOO callout-tip callout callout-style-simple">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-body-container">
<p>La respuesta <strong>correcta es la b</strong>.</p>
<p>Impuesto sobre la Renta de las Personas Físicas (IRPF): Es un impuesto directo que se aplica sobre la obtención de la renta como manifestación inmediata de la capacidad económica de los ciudadanos, atendiendo a los principios de igualdad, generalidad y progresividad y de acuerdo con las circunstancias personales y familiares de las personas.</p>
</div>
</div>
</div>
</details>
<hr>
<ol start="4" type="1">
<li>¿Que régimen fiscal es aplicable a los inversores en los Exchanged Traded Funds (ETF)?:</li>
</ol>
<!-- -->
<ol type="a">
<li><p>Se aplica la misma fiscalidad que los Fondos de Inversión.</p></li>
<li><p>Se aplica la fiscalidad correspondiente a las acciones y no la fiscalidad el de los Fondos de Inversión.</p></li>
<li><p>Se aplica la fiscalidad correspondiente a las acciones, salvo en lo relativo a las plusvalías, las cuales tributan como rendimiento del capital mobiliario.</p></li>
<li><p>Ninguna de las anteriores.</p></li>
</ol>
<details>
<summary>
</summary>
<div class="FOO callout-tip callout callout-style-simple">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-body-container">
<p>La respuesta <strong>correcta es la B</strong>.</p>
<p><strong>El régimen fiscal aplicable a los inversores en ETF es el de las acciones</strong>, no el de los fondos, por lo que las ganancias patrimoniales no están sujetas a retención. Por otra parte, las participaciones en fondos cotizados no pueden ser objeto de traspaso, por lo que no es posible acogerse al régimen que permite a los partícipes en fondos tradicionales reembolsar en un fondo y suscribir en otro con diferimiento de la tributación por las plusvalías.</p>
<p><strong>La diferencia entre el importe obtenido en la venta y el satisfecho en la compra de un ETF, es una ganancia/pérdida patrimonial que se integra en la base imponible del ahorro</strong>. En los ETFs, a diferencia de los fondos de inversión tradicionales, no se aplica retención a cuenta sobre las ganancias patrimoniales derivadas de la transmisión de los mismos.</p>
<p>A este tipo de fondos no se les aplica la exención de tributación por el traspaso de participaciones, del que sí se benefician los fondos tradicionales. Es decir, al traspasar las participaciones de un ETF a otro ETF no hay diferimiento de la tributación por haber evitado su venta/reembolso.</p>
<p>Por su parte, <strong>los dividendos (sujetos a retención del 19%) se ajusta en función del tramo correspondiente por ganancias de capital, ya que son</strong> rendimientos del capital mobiliario como cualquier otro interés cobrado por la tenencia de un activo.</p>
</div>
</div>
</div>
</details>
<hr>
<ol start="5" type="1">
<li>La renta como objeto del Impuesto sobre la Renta de las Personas Físicas (IRPF). Se entiende que está constituida por la totalidad de los rendimientos:</li>
</ol>
<!-- -->
<ol type="a">
<li><p>Del trabajo, de actividades económicas y del capital; y por las ganancias y pérdidas patrimoniales.</p></li>
<li><p>Del trabajo, del capital; y por las ganancias y pérdidas patrimoniales.</p></li>
<li><p>Del trabajo, de los beneficios empresariales y del capital; y por las ganancias y pérdidas patrimoniales.</p></li>
<li><p>Ninguna de las anteriores.</p></li>
</ol>
<details>
<summary>
</summary>
<div class="FOO callout-tip callout callout-style-simple">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-body-container">
<p>La respuesta <strong>correcta es la a</strong>.</p>
<p>Renta: Es el objeto del Impuesto sobre la Renta de las Personas Físicas. Se entiende que está constituida por la totalidad de los rendimientos (del trabajo, de actividades económicas y del capital), y por las ganancias y pérdidas patrimoniales</p>
</div>
</div>
</div>
</details>
<hr>
<ol start="6" type="1">
<li>Marisa contrató hace un mes un seguro de vida que cubre el riesgo de fallecimiento de su esposo. El beneficiario del seguro para caso de fallecimiento es su hija Matilde. ¿Qué tratamiento fiscal corresponderá al cobro de la prestación para caso de fallecimiento por el beneficiario?:</li>
</ol>
<!-- -->
<ol type="a">
<li><p>Tributación por el Impuesto sobre la Renta de las Personas Físicas como rendimiento del capital mobiliario.</p></li>
<li><p>Tributación en el Impuesto Sobre Sucesiones y Donaciones, modalidad “mortis causa”.</p></li>
<li><p>Tributación por el Impuesto sobre Sucesiones y Donaciones, modalidad “inter vivos”.</p></li>
<li><p>Ausencia de tributación en el Impuesto sobre Sucesiones y Donaciones por tratarse de una renta obtenida por un descendiente.</p></li>
</ol>
<details>
<summary>
</summary>
<div class="FOO callout-tip callout callout-style-simple">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-body-container">
<p>La respuesta <strong>correcta es la c</strong>.</p>
<p>Las prestaciones derivadas de un contrato de seguro pueden ser objeto de diferentes impuestos, dependiendo de la contingencia producida y de los elementos personales del mismo.</p>
<p>Cuando el tomador del seguro no es la misma persona que el beneficiario, la tributación corresponde al Impuesto de Sucesiones y Donaciones.</p>
<p>Cuando el tomador del seguro sí es la misma persona que el beneficiario, la tributación corresponde al IRPF.</p>
<p>En este caso, el tratamiento fiscal que corresponderá al beneficiario por el cobro de la prestación (debido al fallecimiento) será la tributación por el Impuesto sobre Sucesiones y Donaciones. La duda puede surgir en la modalidad, pero en este aspecto la ley es clara y dice que las transmisiones se considerarán inter vivos cuando ésta se produce en vida del donante. Y, como Marisa (la donante) sigue en vida el hecho imponible será considerado una adquisición gratuita “inter vivos”.</p>
</div>
</div>
</div>
</details>
<hr>
<ol start="7" type="1">
<li>Las pérdidas patrimoniales que no han podido compensarse en la base imponible del ahorro:</li>
</ol>
<!-- -->
<ol type="a">
<li><p>Podrán compensarse en la base imponible del ahorro durante los 4 años siguientes</p></li>
<li><p>Podrán compensarse en 15 años</p></li>
<li><p>Podrán compensarse en la base imponible general y en la base imponible del ahorro en los 5 años siguientes.</p></li>
<li><p>No pueden compensarse en ejercicios futuros.</p></li>
</ol>
<details>
<summary>
</summary>
<div class="FOO callout-tip callout callout-style-simple">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-body-container">
<p>La respuesta <strong>correcta es la a</strong>.</p>
<p>La integración y compensación en la base imponible del ahorro actualmente es la siguiente:</p>
<ul>
<li><p>Los rendimientos de capital mobiliario que se integran entre sí en la base imponible del ahorro. Si los rendimientos obtenidos son negativos, su importe se compensará con el saldo positivo de las ganancias y pérdidas patrimoniales que se declaren en el otro componente de la base imponible del ahorro con el límite del 25 por ciento de dicho saldo positivo.</p></li>
<li><p>Ganancias y pérdidas patrimoniales que se integran en la base imponible del ahorro. Si el saldo de la integración y compensación de este tipo de rendimientos fuera negativo, su importe se podrá compensar con el saldo positivo del otro componente de la base imponible del ahorro, rendimientos de capital mobiliario, con el límite del 25 por ciento de dicho saldo positivo.</p></li>
<li><p>En ambos casos si tras dichas compensaciones quedase saldo negativo, su importe se compensará en los cuatro años siguientes.</p></li>
</ul>
<p>No obstante, durante los años 2015, 2016 y 2017 el porcentaje de compensación no será del 25%, sino del 10, 15 y 20% respectivamente.</p>
</div>
</div>
</div>
</details>
<hr>
<ol start="8" type="1">
<li>Un contribuyente del IRPF que percibe rentas por el alquiler de un local comercial, disponiendo para ello de un empleado con contrato laboral y a jornada completa, deberá declarar:</li>
</ol>
<!-- -->
<ol type="a">
<li><p>Rendimientos del trabajo personal.</p></li>
<li><p>Rendimientos del capital mobiliario.</p></li>
<li><p>Rendimientos del capital inmobiliario.</p></li>
<li><p>Rendimientos de actividades económicas.</p></li>
</ol>
<details>
<summary>
</summary>
<div class="FOO callout-tip callout callout-style-simple">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-body-container">
<p>La respuesta <strong>correcta es la d</strong>.</p>
<p>Se considera que el arrendamiento de inmuebles se realiza como actividad económica, úni- camente cuando para la ordenación de esta se utilice, al menos, una persona empleada con contrato laboral y a jornada completa.</p>
<p>Importante: en 2015 desaparece como requisito para considerar el arrendamiento de inmuebles como actividad económica el de contar, al menos, con un local exclusivamente destinado a llevar a cabo la gestión de la actividad.</p>
</div>
</div>
</div>
</details>
<hr>
<ol start="9" type="1">
<li>Hace seis años, el Sr.&nbsp;Bernat, residente fiscal en Altea, suscribió con dinero privativo un seguro de vida con una compañía de seguros. De acuerdo con las condiciones del contrato, el seguro garantiza una prestación a favor del cónyuge del Sr.&nbsp;Bernat para caso de fallecimiento de éste último. Si se produjera el fallecimiento del Sr.&nbsp;Bernat, ¿por qué impuesto y en qué concepto habría de tributar su cónyuge?:</li>
</ol>
<!-- -->
<ol type="a">
<li><p>Por el Impuesto sobre la Renta de las Personas Físicas.</p></li>
<li><p>Por el Impuesto sobre Sucesiones y Donaciones, modalidad adquisiciones “inter vivos”.</p></li>
<li><p>Por el Impuesto sobre Sucesiones y Donaciones, modalidad adquisiciones “mortis causa”.</p></li>
<li><p>Por ambos impuestos.</p></li>
</ol>
<details>
<summary>
</summary>
<div class="FOO callout-tip callout callout-style-simple">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-body-container">
<p>La respuesta <strong>correcta es la c</strong>.</p>
<p>El cobro de cantidades provenientes de un seguro puede generar un hecho imponible en el Impuesto sobre la Renta de las Personas Físicas (IRPF) o en el Impuesto sobre Sucesiones y Donaciones (en cualquiera de sus dos modalidades). La determinación de cuál de estos Impuestos es aplicable se realiza atendiendo al siguiente criterio:</p>
<p>Hechos imponibles por supervivencia del asegurado</p>
<p><span class="math display">\[TOMADOR\quad=\quad BENEFICIARIO\quad\Longrightarrow \quad I.R.P.F.\]</span></p>
<p><span class="math display">\[
TOMADOR\quad \neq \quad BENEFICIARIO\quad \quad \Longrightarrow \quad ISD\quad (Donaciones)
\]</span></p>
<p>Hechos imponibles por <strong>fallecimiento del asegurado</strong></p>
<p><span class="math display">\[TOMADOR\quad=\quad BENEFICIARIO\quad\Longrightarrow \quad I.R.P.F.\]</span></p>
<p><span class="math display">\[TOMADOR\quad \neq \quad BENEFICIARIO\quad \quad \Longrightarrow \quad ISD\quad (Sucesiones)\]</span></p>
<p>Por tanto al ser el tomador (Sr.&nbsp;Bernat) distinto de la beneficiaria (conyuge Sr.&nbsp;Bernat), el impuesto que se devenga como consecuencia del cobro de la prestación del seguro será el <strong>Impuesto sobre Sucesiones y Donaciones</strong> en su modalidad de sucesiones (Mortis causa), ya que el acto jurídico se produce por causa de muerte del tomador y asegurado.</p>
<p>Nota: Inter vivos es una expresión latina que se utiliza en derecho para referirse a aquellos actos jurídicos que se producen entre personas vivas. La expresión literalmente significa “entre vivos”. Por el contrario, Mortis causa o causa mortis es también una expresión latina que significa “por causa de muerte” o “a causa de la muerte”. Y que se utiliza para referirse a aquellos actos jurídicos que se producen o tienen efecto a partir del fallecimiento de una persona.</p>
</div>
</div>
</div>
</details>
<hr>
<ol start="10" type="1">
<li>Con la nueva Ley del IRPF las cuantías en concepto de mínimos personal y por descendientes se detraen:</li>
</ol>
<!-- -->
<ol type="a">
<li><p>De la base imponible general y de la base imponible del ahorro.</p></li>
<li><p>De la base imponible general.</p></li>
<li><p>De la cuota íntegra general, previo sometimiento a las mismas de las escalas de gravamen.</p></li>
<li><p>De la base liquidable para gravarse a tipo cero.</p></li>
</ol>
<details>
<summary>
</summary>
<div class="FOO callout-tip callout callout-style-simple">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-body-container">
<p>La respuesta <strong>correcta es la d</strong>.</p>
<p>Para asegurar una misma disminución de la carga tributaria para todos los contribuyentes con igual situación familiar, sea cual sea su nivel de renta, el importe correspondiente al mínimo personal y familiar ya no reduce la renta del período impositivo para determinar la base imponible, sino que pasa a formar parte de la base liquidable para gravarse a tipo cero. De esta forma, los contribuyentes con iguales circunstancias personales y familiares logran el mismo ahorro fiscal, cualquiera que sea su nivel de renta.</p>
</div>
</div>
</div>
</details>
<hr>
<ol start="11" type="1">
<li>¿Cuál es el plazo general para compensar las bases imponibles negativas que hayan sido objeto de liquidación o autoliquidación en el Impuesto sobre Sociedades?:</li>
</ol>
<!-- -->
<ol type="a">
<li><p>Se permite la compensación ilimitada en el tiempo.</p></li>
<li><p>10 años siguientes.</p></li>
<li><p>18 años siguientes.</p></li>
<li><p>5 años siguientes.</p></li>
</ol>
<details>
<summary>
</summary>
<div class="FOO callout-tip callout callout-style-simple">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-body-container">
<p>La respuesta <strong>correcta es la a</strong>.</p>
<p>Las bases imponibles negativas que hayan sido objeto de liquidación o autoliquidación podrán ser compensadas con las rentas positivas de los períodos impositivos siguientes. Por tanto, se permite la compensación ilimitada en el tiempo.</p>
<p>Normativa: Artículo 26 Ley 27/2014, de 27 de noviembre, del Impuesto sobre Sociedades.</p>
</div>
</div>
</div>
</details>
<hr>
<ol start="12" type="1">
<li>Un contribuyente del IRPF que ha percibido 6.500 euros en concepto de dividendos procedentes de una sociedad del IBEX 35 deberá afrontar una carga fiscal por IRPF de:</li>
</ol>
<!-- -->
<ol type="a">
<li><p>1.050 euros.</p></li>
<li><p>1.235 euros.</p></li>
<li><p>950 euros.</p></li>
<li><p>1.245 euros.</p></li>
</ol>
<details>
<summary>
</summary>
<div class="FOO callout-tip callout callout-style-simple">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-body-container">
<p>La respuesta <strong>correcta es la d</strong>.</p>
<p>Los tipos que se pagan por dividendos y demás rendimientos del capital mobiliario en 2016 y 2017 quedan en:</p>
<ul>
<li><p>Entre 0 y 6.000 euros: se paga el 19%.</p></li>
<li><p>Entre 6.000,01 y 50.000 euros: se paga el 21%.</p></li>
<li><p>Más de 50.000 euros: se paga el 23%.</p></li>
</ul>
<p>Por lo tanto el cálculo quedaría como sigue,</p>
<p><span class="math display">\[CF=6000\cdot0.19+500\cdot0.21=1245\]</span></p>
</div>
</div>
</div>
</details>
<hr>
<ol start="13" type="1">
<li>Un contribuyente del IRPF que ha percibido 6.500 euros en concepto de dividendos procedentes de una SICAV deberá afrontar una carga fiscal por IRPF de:</li>
</ol>
<!-- -->
<ol type="a">
<li><p>1.050 euros.</p></li>
<li><p>1.245 euros.</p></li>
<li><p>1.385 euros.</p></li>
<li><p>1.235 euros.</p></li>
</ol>
<details>
<summary>
</summary>
<div class="FOO callout-tip callout callout-style-simple">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-body-container">
<p>La respuesta <strong>correcta es la b</strong>.</p>
<p>Desde las últimas reformas del IRPF (2006 y 2014), todos los inversores (personas físicas) tienen la misma fiscalidad en productos de ahorro: así, los accionistas de las SICAV, al igual que los partícipes de los Fondos de Inversión, al igual que los inversores en depósitos o los asegurados en productos “unit-linked”, o los accionistas de cualquier empresa cotizada o no cotizada, tienen exactamente la misma tributación (en 2016, un 19% si la plusvalía es inferior a 6.000 euros/año; 21% entre 6.000 y 50.000 euros; y 23% a partir de esa cifra). Adicionalmente, al vender las acciones de la SICAV, el accionista vendedor está obligado a realizar una autoliquidación e ingresar a cuenta del incremento de patrimonio obtenido.</p>
<p>Los tipos que se pagan por dividendos y demás rendimientos del capital mobiliario en 2016 y 2017 quedan en:</p>
<ul>
<li><p>Entre 0 y 6.000 euros: se paga el 19%.</p></li>
<li><p>Entre 6.000,01 y 50.000 euros: se paga el 21%.</p></li>
<li><p>Más de 50.000 euros: se paga el 23%.</p></li>
</ul>
<p>Por lo tanto el cálculo quedaría como sigue,</p>
<p><span class="math display">\[6000\cdot0.19+500\cdot0.21=1245\]</span></p>
</div>
</div>
</div>
</details>
<hr>
<ol start="14" type="1">
<li>Señale la/s afirmación/es correcta/s referente a los rendimientos procedentes de la cesión a terceros de capitales propios:</li>
</ol>
<!-- -->
<ol type="a">
<li><p>Tienen esta consideración las contraprestaciones tanto si son dinerarias como si son en especie.</p></li>
<li><p>Tienen esta consideración los intereses de cuentas en toda clase de instituciones financieras.</p></li>
<li><p>Tienen esta consideración los intereses, cupones y otros rendimientos periódicos derivados de valores de renta fija.</p></li>
<li><p>Todas las anteriores.</p></li>
</ol>
<details>
<summary>
</summary>
<div class="FOO callout-tip callout callout-style-simple">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-body-container">
<p>La respuesta <strong>correcta es la d</strong>.</p>
<p>Rendimientos procedentes de la cesión a terceros de capitales propios (Art. 25.2 Ley IRPF)</p>
<p>Tienen esta consideración las contraprestaciones de todo tipo, cualquiera que sea su denomi- nación o naturaleza, tanto si son dinerarias como en especie, obtenidas como retribución por la cesión a terceros de capitales propios, así como las derivadas de la transmisión, reembolso, amortización, canje o conversión de cualquier clase de activos representativos de la captación y utilización de capitales ajenos.</p>
<p>Dentro de esta categoría de rendimientos, pueden distinguirse los <strong>cuatro grupos siguientes</strong>:</p>
<ol type="1">
<li><p>Rendimientos obtenidos por la cesión a terceros de capitales propios.</p></li>
<li><p>Contraprestaciones derivadas de la transmisión, reembolso, amortización, canje o con- versión de cualquier clase de activos financieros, con independencia de la naturaleza del rendimiento que produzcan, implícito, explícito o mixto.</p></li>
<li><p>Rendimientos derivados de determinados préstamos de valores.</p></li>
<li><p>Rendimientos derivados de participaciones preferentes y deuda subordinada.</p></li>
</ol>
</div>
</div>
</div>
</details>
<hr>
<ol start="15" type="1">
<li>Un contribuyente viudo convive con su hija soltera de 21 años y su nieto de 2, sin que estos dos últimos tengan rentas:</li>
</ol>
<!-- -->
<ol type="a">
<li><p>El contribuyente, su hija y su nieto forman una unidad familiar, y el contribuyente no puede aplicar el mínimo por descendientes.</p></li>
<li><p>El contribuyente, su hija y su nieto no forman una unidad familiar, y el contribuyente puede aplicar el mínimo por descendientes.</p></li>
<li><p>El contribuyente, su hija y su nieto forman una unidad familiar, y el contribuyente puede aplicar el mínimo por descendientes.</p></li>
<li><p>El contribuyente, su hija y su nieto no forman una unidad familiar, y el contribuyente no puede aplicar el mínimo por descendientes.</p></li>
</ol>
<details>
<summary>
</summary>
<div class="FOO callout-tip callout callout-style-simple">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-body-container">
<p>La respuesta <strong>correcta es la b</strong>.</p>
<p>A efectos del IRPF, existen dos modalidades de unidad familiar, a saber:</p>
<p><strong>En caso de matrimonio (modalidad 1ª)</strong>:</p>
<p>La integrada por los cónyuges no separados legalmente y, si los hubiere:</p>
<ol type="1">
<li><p>Los hijos menores, con excepción de los que, con el consentimiento de los padres, vivan independientemente de estos.</p></li>
<li><p>Los hijos mayores de edad incapacitados judicialmente sujetos a patria potestad prorrogada o rehabilitada.</p></li>
</ol>
<p>La mayoría de edad se alcanza a los 18 años.</p>
<p><strong>En defecto de matrimonio o en los casos de separación legal (modalidad 2ª)</strong>:</p>
<p>La formada por el padre o la madre y la totalidad de los hijos que convivan con uno u otra y reúnan los requisitos señalados para la modalidad 1ª anterior.</p>
<p>De la regulación legal, a efectos fiscales, de las modalidades de unidad familiar, pueden extraerse las siguientes conclusiones:</p>
<ul>
<li><p>Cualquier otra agrupación familiar distinta de las anteriores no constituye unidad familiar a efectos del IRPF.</p></li>
<li><p>Nadie podrá formar parte de dos unidades familiares al mismo tiempo.</p></li>
<li><p>La determinación de los miembros de la unidad familiar se realizará atendiendo a la situación existente el día 31 de diciembre de cada año.</p></li>
</ul>
<p>Por tanto, si un hijo cumpliera 18 años durante el año, ya no formará parte de la unidad familiar en ese período impositivo.</p>
<p>Únicamente podrá aplicarse el mínimo por los descendientes y asimilados del contribuyente que cumplan todos y cada uno de los siguientes requisitos:</p>
<ul>
<li><p>Que el descendiente sea menor de 25 años a la fecha de devengo del impuesto.</p></li>
<li><p>Que el descendiente conviva con el contribuyente.</p></li>
<li><p>Que el descendiente no haya obtenido en el ejercicio rentas superiores a 8.000 euros anuales, excluidas las rentas exentas del impuesto.</p></li>
<li><p>Que no presenten declaración del IRPF.</p></li>
</ul>
</div>
</div>
</div>
</details>
<hr>
<ol start="16" type="1">
<li>En un seguro de vida en el que el contratante, o tomador, es una persona distinta del beneficiario, el importe cobrado por los beneficiarios tributará:</li>
</ol>
<!-- -->
<ol type="a">
<li><p>A En el IRPF como ganancia patrimonial para el transmisor (“de cuius” o causante).</p></li>
<li><p>En el IRPF como rendimiento del capital mobiliario del beneficiario.</p></li>
<li><p>En el ISD, en la persona del beneficiario.</p></li>
<li><p>En el IRPF en la persona del beneficiario.</p></li>
</ol>
<details>
<summary>
</summary>
<div class="FOO callout-tip callout callout-style-simple">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-body-container">
<p>La respuesta <strong>correcta es la c</strong>.</p>
</div>
</div>
</div>
</details>
<hr>
<ol start="17" type="1">
<li>A la hora de cuantificar la ganancia o pérdida patrimonial procedente de la venta de acciones cotizadas, los corretajes y comisiones de venta que se hayan tenido que pagar en la transmisió:</li>
</ol>
<!-- -->
<ol type="a">
<li><p>Reducirán el valor de adquisición de las acciones.</p></li>
<li><p>Aumentarán el valor de transmisión de las acciones.</p></li>
<li><p>Reducirán el valor de transmisión de las acciones.</p></li>
<li><p>Aumentarán el valor de adquisición de las acciones.</p></li>
</ol>
<details>
<summary>
</summary>
<div class="FOO callout-tip callout callout-style-simple">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-body-container">
<p>La respuesta <strong>correcta es la c</strong>.</p>
</div>
</div>
</div>
</details>
<hr>
<ol start="18" type="1">
<li>Un contribuyente de 54 años de edad ha aportado 12.500 euros a un plan de pensiones del sistema individual. ¿Cuál es la cantidad máxima que en el año 2016 puede reducir de la base imponible general del IRPF si su única fuente de ingresos tributables en la base imponible general son 23.000 euros en concepto de rendimientos del capital inmobiliario procedentes del alquiler de un local comercial?:</li>
</ol>
<!-- -->
<ol type="a">
<li><p>12.500 euros.</p></li>
<li><p>10.000 euros.</p></li>
<li><p>11.500 euros.</p></li>
<li><p>0 euros.</p></li>
</ol>
<details>
<summary>
</summary>
<div class="FOO callout-tip callout callout-style-simple">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-body-container">
<p>La respuesta <strong>correcta es la d</strong>.</p>
<p>En este caso el contribuyente no puede reducir las aportaciones por insuficiencia de base en los rendimientos del trabajo. Ya que el límite porcentual resulta 0.</p>
<p>Recordemos que la cantidad límite es el menor de:</p>
<ul>
<li><p>8.000 euros.</p></li>
<li><p>o el 30% de los rendimientos del trabajo y actividades económicas, independientemente de la edad.</p></li>
</ul>
</div>
</div>
</div>
</details>
<hr>
<ol start="19" type="1">
<li>¿Cómo tributa la transmisión o reembolso de acciones o participaciones de Instituciones de Inversión Colectiva ?</li>
</ol>
<!-- -->
<ol type="a">
<li><p>Como una ganancia o pérdida patrimonial.</p></li>
<li><p>Como un rendimiento del capital mobiliario.</p></li>
<li><p>Como un rendimiento del trabajo.</p></li>
<li><p>Como un rendimiento del capital inmobiliario.</p></li>
</ol>
<details>
<summary>
</summary>
<div class="FOO callout-tip callout callout-style-simple">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-body-container">
<p>La respuesta <strong>correcta es la a</strong>.</p>
<p>Tributará como ganancia o pérdida patrimonial, teniendo en cuenta que cuando existan valores homogéneos se considerará que los transmitidos o reembolsados por el contribuyente son aquellos que adquirió en primer lugar.</p>
</div>
</div>
</div>
</details>
<hr>
<ol start="20" type="1">
<li>¿Cuál será el tratamiento fiscal de las cuantías percibidas en forma de capital derivadas de contratos de seguro de vida a prima única?</li>
</ol>
<!-- -->
<ol type="a">
<li><p>Como una ganancia o pérdida patrimonial.</p></li>
<li><p>Como un rendimiento del capital mobiliario.</p></li>
<li><p>Como un rendimiento del trabajo.</p></li>
<li><p>Como un rendimiento del capital inmobiliario.</p></li>
</ol>
<details>
<summary>
</summary>
<div class="FOO callout-tip callout callout-style-simple">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-body-container">
<p>La respuesta <strong>correcta es la b</strong>.</p>
<p>Tributarán como rendimientos del capital mobiliario por diferencia entre el capital percibido y el importe de las primas satisfechas que hayan generado el capital que se percibe, integrándose en la base imponible del ahorro del Impuesto sobre la Renta de las Personas Físicas, sin que le resulte de aplicación ningún porcentaje de reducción.</p>
</div>
</div>
</div>
</details>
<hr>
<ol start="21" type="1">
<li>¿Qué tratamiento fiscal tienen los planes individuales de ahorro sistemáticos (PIAS)?:</li>
</ol>
<!-- -->
<ol type="a">
<li><p>Como una ganancia o pérdida patrimonial aplicando a cada anualidad unos porcentajes en función de la edad del contribuyente.</p></li>
<li><p>Como un rendimiento del capital mobiliario aplicando a cada anualidad unos porcentajes en función de la edad del contribuyente.</p></li>
<li><p>Como un rendimiento del trabajo aplicando a cada anualidad unos porcentajes en función de la edad del contribuyente.</p></li>
<li><p>Como un rendimiento del capital inmobiliario aplicando a cada anualidad unos porcentajes en función de la edad del contribuyente.</p></li>
</ol>
<details>
<summary>
</summary>
<div class="FOO callout-tip callout callout-style-simple">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-body-container">
<p>La respuesta <strong>correcta es la b</strong>.</p>
<p>Los planes individuales de ahorro sistemático se configuran como contratos celebrados con entidades aseguradoras para constituir con los recursos aportados una renta vitalicia asegurada.</p>
<p>Las rentas que se pongan de manifiesto en el momento de la constitución de la renta vitalicia asegurada estará exenta.</p>
<p>La renta vitalicia que se perciba tributará como rendimiento de capital mobiliario conforme al artículo 25.3 a) 2º, aplicando a cada anualidad los porcentajes siguientes:</p>
<ul>
<li><p>40% cuando el perceptor tenga menos de 40 años.</p></li>
<li><p>35% cuando el perceptor tenga entre 40 y 49 años.</p></li>
<li><p>28% cuando el perceptor tenga entre 50 y 59 años.</p></li>
<li><p>24% cuando el perceptor tenga entre 60 y 65 años.</p></li>
<li><p>20% cuando el perceptor tenga entre 66 y 69 años</p></li>
<li><p>8% cuando el perceptor tenga más de 70 años.</p></li>
</ul>
</div>
</div>
</div>
</details>
<hr>
<ol start="22" type="1">
<li>A efectos de calificar las prestaciones de los seguros de vida o invalidez como rendimientos de capital mobiliario, ¿qué se consideran prestaciones por invalidez?:</li>
</ol>
<!-- -->
<ol type="a">
<li><p>Se entiende por invalidez aquella situación que determine en la persona afectada un grado de discapacidad igual o superior al 33%.</p></li>
<li><p>Se entiende por invalidez aquella situación que determine en la persona afectada un grado de discapacidad igual o superior al 65%</p></li>
<li><p>Se entiende por invalidez cuando se trate de discapacitados cuya incapacidad haya sido declarada judicialmente en el orden civil.</p></li>
<li><p>Ninguna de las anteriores.</p></li>
</ol>
<details>
<summary>
</summary>
<div class="FOO callout-tip callout callout-style-simple">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-body-container">
<p>La respuesta <strong>correcta es la a</strong>.</p>
<p>Son rendimientos de capital mobiliario los procedentes de contratos de vida o invalidez, salvo que deban tributar como rendimientos del trabajo.</p>
<p>A los efectos del Impuesto sobre la Renta, tienen la consideración de discapacitados aquellos contribuyentes que acrediten un grado de discapacidad igual o superior al 33%.</p>
<p>Por tanto, cuando la prestación de un seguro tenga su origen en una situación de invalidez, entendida según lo señalado anteriormente, el rendimiento generado se calificará como rendimiento de capital mobiliario. En caso contrario se calificará como ganancia patrimonial.</p>
</div>
</div>
</div>
</details>
<hr>
<p>23.Un Plan Individual de Ahorro Sistemático (PIAS) es:</p>
<ol type="a">
<li><p>Un seguro de vida.</p></li>
<li><p>Un contrato bancario de depósito que invierte en un subyacente.</p></li>
<li><p>Un plan de pensiones.</p></li>
<li><p>Ninguno de los anteriores.</p></li>
</ol>
<details>
<summary>
</summary>
<div class="FOO callout-tip callout callout-style-simple">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-body-container">
<p>La respuesta <strong>correcta es la a</strong>.</p>
<p>Un Plan Individual de Ahorro Sistemático es un seguro de vida.</p>
</div>
</div>
</div>
</details>
<hr>
<p>¿Qué tratamiento fiscal tienen los planes individuales de ahorro sistemáticos (PIAS)?: a) El importe obtenido tributa como rendimiento del capital mobiliario.</p>
<ol start="2" type="a">
<li><p>El importe obtenido reduce el valor de adquisición de las acciones hasta anularlo y, el exceso, si lo hubiera, tributará como ganancia patrimonial.</p></li>
<li><p>Todo el importe obtenido tributa como rendimiento del capital mobiliario.</p></li>
<li><p>La venta de derechos de suscrición preferente no genera tributación en el IRPF</p></li>
</ol>
<details>
<summary>
</summary>
<div class="FOO callout-tip callout callout-style-simple">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-body-container">
<p>La respuesta <strong>correcta es la b</strong>.</p>
<p>El importe obtenido en la transmisión de derechos de suscripción derivados de esta clase de acciones y participaciones no constituye ganancia patrimonial ni rendimientos del capital mobiliario, sino que dicho importe minorará el valor de adquisición de las acciones de las que proceden a efectos de futuras transmisiones de las mismas. Cuando no se transmita la totalidad de los derechos, se entenderá que los transmitidos corresponden a los valores adquiridos en primer lugar.</p>
<p>No obstante, si el importe obtenido en la transmisión de los derechos de suscripción llegara a ser superior al valor de adquisición de los valores de los cuales procedan tales derechos, la diferencia tiene, en todo caso, la consideración de ganancia patrimonial para el transmitente que deberá imputarse al período impositivo en que se produzca la transmisión.</p>
<p><strong>nota</strong>: a partir de 01.01.2017 el importe de transmisión será ganancia patrimonial y estará sometido a retención del 19%</p>
</div>
</div>
</div>
</details>
<hr>
<ol start="25" type="1">
<li>Las diferencias positivas obtenidas en la conversión de una posición en divisa tributa en el IRPF bajo la calificación fiscal de:</li>
</ol>
<!-- -->
<ol type="a">
<li><p>Rendimiento del capital mobiliario</p></li>
<li><p>Ganancia o pérdida patrimonial</p></li>
<li><p>Rendimiento el capital mobiliario o ganancia o pérdida patrimonial según el tipo de renta que genere el producto financiero que se haya contratado en divisa</p></li>
<li><p>Rendimiento del trabajo personal</p></li>
</ol>
<details>
<summary>
</summary>
<div class="FOO callout-tip callout callout-style-simple">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-body-container">
<p>La respuesta <strong>correcta es la b</strong>.</p>
<p>Cuando se vende un bien denominado en divisas y se recibe una saldo en esta divisa, se imputará como ganancia o pérdida patrimonial el importe de la ganancia o perdida patrimonial obtenida en divisas y convertida a euros al tipo de cambio oficial del día de la transmisión.</p>
</div>
</div>
</div>
</details>
<hr>
<ol start="26" type="1">
<li>¿Cómo tributan los rendimientos derivados de un seguro de vida de rentas vitalicias inmediatas que no hayan sido adquiridas por herencia, legado o cualquier otro título sucesorio en el IRPF?</li>
</ol>
<!-- -->
<ol type="a">
<li><p>Se integran en la base imponible del ahorro.</p></li>
<li><p>Se integran en la base imponible los rendimientos generados aplicando a cada anualidad los porcentajes correspondientes en función de la edad.</p></li>
<li><p>Se integran en la base imponible general.</p></li>
<li><p>Ninguna de las anteriores.</p></li>
</ol>
<details>
<summary>
</summary>
<div class="FOO callout-tip callout callout-style-simple">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-body-container">
<p>La respuesta <strong>correcta es la b</strong>.</p>
<p>En el Impuesto sobre la Renta de la Personas Físicas, los contratos de seguro de renta vitalicia inmediata generan para su perceptor, cuando este coincide con el contratante del seguro, rendimientos del capital mobiliario.</p>
<p>La integración en la base imponible del Impuesto sobre la Renta de las Personas Físicas de los rendimientos generados se realizará aplicando a cada anualidad los porcentajes siguientes:</p>
<p>40 por 100, cuando el perceptor tenga menos de 40 años. 35 por 100, cuando el perceptor tenga entre 40 y 49 años. 28 por 100, cuando el perceptor tenga entre 50 y 59 años. 24 por 100, cuando el perceptor tenga entre 60 y 65 años. 20 por 100, cuando el perceptor tenga entre 66 y 69 años. 8 por 100, cuando el perceptor tenga más de 70 años.</p>
<p>Estos porcentajes serán los correspondientes a la edad del rentista en el momento de la constitución de la renta y permanecerán constantes durante toda su vigencia.</p>
</div>
</div>
</div>
</details>
<hr>
<ol start="27" type="1">
<li>Un contribuyente del IRPF que tiene 54 años de edad ha aportado el importe máximo legalmente permitido a un plan de pensiones. ¿Cuál es el importe máximo que puede reducir de su base imponible en el IRPF si percibe unos rendimientos netos del trabajo personal de 20.000 euros:</li>
</ol>
<!-- -->
<ol type="a">
<li><p>10.000 euros</p></li>
<li><p>12.500 euros</p></li>
<li><p>6.000 euros</p></li>
<li><p>ninguna de las anteriores.</p></li>
</ol>
<details>
<summary>
</summary>
<div class="FOO callout-tip callout callout-style-simple">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-body-container">
<p>La respuesta <strong>correcta es la c</strong>.</p>
<p>Recordemos que la cantidad límite es el menor de:</p>
<ul>
<li><p>8.000 euros.</p></li>
<li><p>o el 30% de los rendimientos del trabajo y actividades económicas, independientemente de la edad.</p></li>
</ul>
<p>Por tanto,</p>
<p><span class="math display">\[20000\cdot0.3=6000\]</span> <span class="math display">\[6000&lt;8000\]</span> Cojemos el menor: 6.000 euros</p>
</div>
</div>
</div>
</details>
<hr>
<ol start="28" type="1">
<li>Un contribuyente recién jubilado:</li>
</ol>
<!-- -->
<ol type="a">
<li><p>Puede seguir haciendo aportaciones para la cobertura de fallecimiento.</p></li>
<li><p>Ya no puede seguir haciendo aportaciones al plan de pensiones.</p></li>
<li><p>Puede seguir haciendo aportaciones para la cobertura de fallecimiento y también para la cobertura de jubilación, siempre y cuando no perciba cantidad alguna de planes de pensiones por la contingencia de jubilación.</p></li>
<li><p>Debe solicitar de la gestora del fondo de pensiones el pago inmediato de sus derechos económicos en el plan de pensiones.</p></li>
</ol>
<details>
<summary>
</summary>
<div class="FOO callout-tip callout callout-style-simple">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-body-container">
<p>La respuesta <strong>correcta es la c</strong>.</p>
<p>Estar jubilado no es impedimiento para seguir ahorrando en los productos de pensiones del sistema privado. La ley permite a las personas retiradas seguir aportando capital a sus productos de ahorro de pensiones, pero con una condición muy clara: no pueden haber iniciado aún el cobro de la prestación por jubilación de ése u otro plan. En caso contrario, esa posibilidad está vetada.</p>
<p>La ley de pensiones impide simultanear la condición de beneficiario y partícipe de un plan de pensiones individual o en razón de la pertenencia a varios planes ante la misma contingencia, de forma que si un ahorrador tiene dos planes de pensiones y en uno de ellos ha iniciado el cobro de la prestación correspondiente por jubilación, ya no podrá seguir realizando aportaciones al otro por el mismo motivo. En general, un jubilado solo podrá seguir realizando aportaciones a cualquiera de sus planes de pensiones siempre que no haya iniciado el cobro de la prestación en ninguno de ellos. “Es incompatible realizar aportaciones y cobrar prestaciones por la misma contingencia simultáneamente”, explican los expertos.</p>
</div>
</div>
</div>
</details>
<hr>
<ol start="29" type="1">
<li>Indique cuál de las siguientes rentas no pertenece a la denominada “renta general” en el IRPF:</li>
</ol>
<!-- -->
<ol type="a">
<li><p>Rendimientos del capital mobiliario.</p></li>
<li><p>Rendimientos del trabajo.</p></li>
<li><p>Rendimientos de actividades económicas.</p></li>
<li><p>Rendimientos del capital inmobiliario.</p></li>
</ol>
<details>
<summary>
</summary>
<div class="FOO callout-tip callout callout-style-simple">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-body-container">
<p>La respuesta <strong>correcta es la a</strong>.</p>
<p>La renta del ahorro queda compuesta por:</p>
<ul>
<li><p>Los rendimientos de capital mobiliario</p></li>
<li><p>Ganancias y pérdidas patrimoniales.</p></li>
</ul>
<p>Mientras que la renta general, se compone de:</p>
<ul>
<li><p>Rendimientos del trabajo.</p></li>
<li><p>Rendimientos de actividades económicas.</p></li>
<li><p>Rendimientos del capital inmobiliario.</p></li>
</ul>
</div>
</div>
</div>
</details>
<hr>
<ol start="30" type="1">
<li>En la actualidad (2017), ¿cuál es el tipo máximo al que pueden llegar a tributar los rendimientos del trabajo personal?:</li>
</ol>
<!-- -->
<ol type="a">
<li><p>Al 45%.</p></li>
<li><p>Al 52%.</p></li>
<li><p>Al 27%.</p></li>
<li><p>Al 42%.</p></li>
</ol>
<details>
<summary>
</summary>
<div class="FOO callout-tip callout callout-style-simple">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-body-container">
<p>La respuesta <strong>correcta es la a</strong>.</p>
<p>Los tipos mínimo y máximo de la escala progresiva de gravamen del IRPF en su base general es:</p>
<ul>
<li><p>Mínimo 19%</p></li>
<li><p>Máximo 45%.</p></li>
</ul>
</div>
</div>
</div>
</details>
<hr>
<ol start="31" type="1">
<li>Si se adquiere un inmueble por 100.000 euros y se vende por 200.000 euros a los 9 años, se produce:</li>
</ol>
<!-- -->
<ol type="a">
<li><p>Una ganancia patrimonial.</p></li>
<li><p>Un rendimiento de capital inmobiliario.</p></li>
<li><p>Un rendimiento de actividad económica.</p></li>
<li><p>Un rendimiento del capital mobiliario.</p></li>
</ol>
<details>
<summary>
</summary>
<div class="FOO callout-tip callout callout-style-simple">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-body-container">
<p>La respuesta <strong>correcta es la a</strong>.</p>
<p>Por la venta del inmueble se produce una ganancia patrimonial. Ésta se calculará, a partir de 2015, restando al valor de transmisión el valor de adquisición según el siguiente esquema:</p>
<ul>
<li><p>(+) Importe real de la adquisición (o valor de adquisición a efectos del Impuesto sobre Sucesiones y Donaciones).</p></li>
<li><p>(+) Inversiones y mejoras efectuadas en los bienes adquiridos.</p></li>
<li><p>(+) Gastos y tributos inherentes a la adquisición (excepto intereses), satisfechos por el adquirente.</p></li>
<li><p>( - ) Amortizaciones (inmuebles o muebles arrendados y derechos sobre los mismos, así como en los supuestos de prestación de asistencia técnica que no constituya actividad económica).</p></li>
</ul>
<p>= <strong>Valor de adquisición</strong></p>
<ul>
<li><p>(+) Importe real de la transmisión (o valor de transmisión a efectos del Impuesto sobre Sucesiones y Donaciones).</p></li>
<li><p>( - ) Gastos y tributos inherentes a la transmisión satisfechos por el transmitente.</p></li>
</ul>
<p>= <strong>Valor de transmisión</strong></p>
</div>
</div>
</div>
</details>
<hr>
<ol start="32" type="1">
<li>Indicar cuál de los siguientes gastos NO son deducibles en los rendimientos de capital mobiliario:</li>
</ol>
<!-- -->
<ol type="a">
<li><p>Los gastos de administración y custodia de valores negociables.</p></li>
<li><p>Los gastos necesarios para la obtención de rendimientos por el alquiler de un vehículo personal</p></li>
<li><p>La amortización por deterioro del bien mueble alquilado.</p></li>
<li><p>Las comisiones por mantenimiento de cuentas corrientes.</p></li>
</ol>
<details>
<summary>
</summary>
<div class="FOO callout-tip callout callout-style-simple">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-body-container">
<p>La respuesta <strong>correcta es la d</strong>.</p>
<p>NO son deducibles en los rendimientos de capital mobiliario las comisiones por mantenimiento de cuentas corrientes.</p>
</div>
</div>
</div>
</details>
<hr>
<ol start="33" type="1">
<li>Indicar de cuál de los siguientes negocios jurídicos derivan rendimientos del capital inmobiliario:</li>
</ol>
<!-- -->
<ol type="a">
<li><p>El alquiler de un bien inmueble.</p></li>
<li><p>La concesión de uso de un bien inmueble por una empresa a un empleado suyo.</p></li>
<li><p>La compra de un bien inmueble.</p></li>
<li><p>La venta de un bien inmueble.</p></li>
</ol>
<details>
<summary>
</summary>
<div class="FOO callout-tip callout callout-style-simple">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-body-container">
<p>La respuesta <strong>correcta es la a</strong>.</p>
</div>
</div>
</div>
</details>
<hr>
<ol start="34" type="1">
<li>Los dividendos obtenidos por Si una persona física derivados de la la titularidad de acciones de una sociedad de capital son:</li>
</ol>
<!-- -->
<ol type="a">
<li><p>Un rendimiento del capital mobiliario en el IRPF.</p></li>
<li><p>Un rendimiento de actividad económica en el IRPF.</p></li>
<li><p>Una ganancia patrimonial en el IRPF.</p></li>
<li><p>Ninguna de las anteriores.</p></li>
</ol>
<details>
<summary>
</summary>
<div class="FOO callout-tip callout callout-style-simple">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-body-container">
<p>La respuesta <strong>correcta es la a</strong>.</p>
<p>Los dividendos obtenidos por la titularidad de acciones de una sociedad de capital serán un rendimiento del capital mobiliario.</p>
</div>
</div>
</div>
</details>
<hr>
<ol start="35" type="1">
<li>Si una persona física recibe una prestación por el rescate de un seguro de vida, se obtiene:</li>
</ol>
<!-- -->
<ol type="a">
<li><p>Una ganancia patrimonial.</p></li>
<li><p>Un rendimiento de actividad económica.</p></li>
<li><p>n rendimiento de capital inmobiliario.</p></li>
<li><p>Un rendimiento del capital mobiliario.</p></li>
</ol>
<details>
<summary>
</summary>
<div class="FOO callout-tip callout callout-style-simple">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-body-container">
<p>La respuesta <strong>correcta es la d</strong>.</p>
<p>Si una persona física recibe una prestación por el rescate de un seguro de vida, se obtiene un rendimiento del capital mobiliario sujeto al IRPF.</p>
</div>
</div>
</div>
</details>
<hr>
<ol start="36" type="1">
<li>Si una persona física vende unas acciones de una sociedad de capital por 3.000 euros cuando se compraron por 2.450 euros se obtiene:</li>
</ol>
<!-- -->
<ol type="a">
<li><p>Una ganancia patrimonial.</p></li>
<li><p>Un rendimiento de capital inmobiliario.</p></li>
<li><p>Un rendimiento del capital mobiliario.</p></li>
<li><p>Ninguna de las anteriores.</p></li>
</ol>
<details>
<summary>
</summary>
<div class="FOO callout-tip callout callout-style-simple">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-body-container">
<p>La respuesta <strong>correcta es la a</strong>.</p>
<p>Las transmisiones onerosas como la venta de acciones, tendrán la consideración de ganancia patrimonial a efectos del IRPF.</p>
</div>
</div>
</div>
</details>
<hr>
<ol start="37" type="1">
<li>Podrá gravarse en algún caso como ganancias o pérdidas patrimoniales las rentas producidas con ocasión de:</li>
</ol>
<!-- -->
<ol type="a">
<li><p>Las transmisiones lucrativas producidas a la muerte del contribuyente.</p></li>
<li><p>Una donación que otorgue derecho a deducción en la cuota.</p></li>
<li><p>La transmisión de la vivienda habitual.</p></li>
<li><p>Ninguna de las anteriores.</p></li>
</ol>
<details>
<summary>
</summary>
<div class="FOO callout-tip callout callout-style-simple">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-body-container">
<p>La respuesta <strong>correcta es la c</strong>.</p>
</div>
</div>
</div>
</details>
<hr>
<ol start="38" type="1">
<li>Los intereses obtenidos por el dinero cedido en préstamo son, por lo general serán:</li>
</ol>
<!-- -->
<ol type="a">
<li><p>Rendimientos de capital mobiliario.</p></li>
<li><p>Ganancias patrimoniales.</p></li>
<li><p>Rendimientos de actividades económicas.</p></li>
<li><p>Ganancias patrimoniales.</p></li>
</ol>
<details>
<summary>
</summary>
<div class="FOO callout-tip callout callout-style-simple">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-body-container">
<p>La respuesta <strong>correcta es la a</strong>.</p>
<p>Los intereses obtenidos por el dinero cedido en préstamo son, por lo general, serán rendimientos de capital mobiliario.</p>
</div>
</div>
</div>
</details>
<hr>
<ol start="39" type="1">
<li>Las plusvalías obtenidas por la venta de acciones, participaciones en fondos de inversión, derivados, ETF’s, inmuebles, etc.los tipos a pagar serán:</li>
</ol>
<!-- -->
<ol type="a">
<li><p>Entre 0 y 6.000 euros: se paga el 19%;entre 6.000,01 y 50.000 euros: se paga el 21%; más de 50.000 euros: se paga el 23%.</p></li>
<li><p>Entre 0 y 3.000 euros: se paga el 18.5%;entre 3.000,01 y 30.000 euros: se paga el 20.5%; más de 30.000 euros: se paga el 22.5%.</p></li>
<li><p>Entre 0 y 9.000 euros: se paga el 20.5%;entre 9.000,01 y 60.000 euros: se paga el 22.5%; más de 60.000 euros: se paga el 25.5%.</p></li>
<li><p>Ninguna de las anteriores.</p></li>
</ol>
<details>
<summary>
</summary>
<div class="FOO callout-tip callout callout-style-simple">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-body-container">
<p>La respuesta <strong>correcta es la a</strong>.</p>
<p>La nueva tabla (ejercicios 2016/2017/2018) de tipos a pagar por las plusvalías obtenidas por la venta de acciones (y fondos de inversión, derivados, ETF’s, inmuebles, etc.) es la siguiente:</p>
<ul>
<li><p>Entre 0 y 6.000 euros: se paga el 19%.</p></li>
<li><p>Entre 6.000,01 y 50.000 euros: se paga el 21%.</p></li>
<li><p>Más de 50.000 euros: se paga el 23%.</p></li>
</ul>
<p>Estos porcentajes se aplican al total de plsuvalías (restando las minusvalías correspondientes) de todos los productos (acciones, fondos de inversión, opciones y futuros, CFD’s, etc).</p>
</div>
</div>
</div>
</details>
<hr>
<ol start="40" type="1">
<li>Referente a la fiscalidad de las personas físicas por la venta de acciones: se han generado unas plusvalías de 5.000 euros con acciones y de otros 3.000 euros con futuros, la suma total son 8.000 euros, ¿Cuánto habrá que pagar a Hacienda en la declaración del IRPF en del ejercicio 2016?:</li>
</ol>
<!-- -->
<ol type="a">
<li><p>El 18.5% de 3.000 euros más el 20.5% de 5.000 euros.</p></li>
<li><p>El 20.5% de 8.000 euros.</p></li>
<li><p>El 19% de 6.000 euros más el 21% de 2.000 euros.</p></li>
<li><p>Ninguna de las anteriores</p></li>
</ol>
<details>
<summary>
</summary>
<div class="FOO callout-tip callout callout-style-simple">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-body-container">
<p>La respuesta <strong>correcta es la c</strong>.</p>
<p>Para unas plusvalías de 5.000 euros con acciones y de otros 3.000 euros con futuros, la suma total son 8.000 euros, y por tanto habrá que pagar a Hacienda el 19.5% de 6.000 euros más el 21.5% de 2.000 euros.</p>
<p>La nueva tabla (ejercicios 2016/2017/2018) de tipos a pagar por las plusvalías obtenidas por la venta de acciones (y fondos de inversión, derivados, ETF’s, inmuebles, etc) es la siguiente:</p>
<ul>
<li><p>Entre 0 y 6.000 euros: se paga el 19%.</p></li>
<li><p>Entre 6.000,01 y 50.000 euros: se paga el 21%.</p></li>
<li><p>Más de 50.000 euros: se paga el 23%.</p></li>
</ul>
<p>Estos porcentajes se aplican al total de plsuvalías (restando las minusvalías correspondientes) de todos los productos (acciones, fondos de inversión, opciones y futuros, CFD’s, etc.).</p>
</div>
</div>
</div>
</details>
<hr>
<ol start="41" type="1">
<li>¿Que tipo de rendimientos generará la transmisión de activos representativos de la cesión a terceros de capitales propios?</li>
</ol>
<!-- -->
<ol type="a">
<li><p>Una ganancia patrimonial.</p></li>
<li><p>Un rendimiento de capital inmobiliario.</p></li>
<li><p>Un rendimiento del capital mobiliario.</p></li>
<li><p>Ninguna de las anteriores.</p></li>
</ol>
<details>
<summary>
</summary>
<div class="FOO callout-tip callout callout-style-simple">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-body-container">
<p>La respuesta <strong>correcta es la c</strong>.</p>
<p>Las rentas derivadas de la transmisión, reembolso, amortización, canje o conversión de activos financieros se califican de rendimientos de capital mobiliario. El rendimiento se computará por diferencia entre el valor de transmisión, y su valor de adquisición o suscripción, computándose los gastos accesorios de adquisición y enajenación en tanto se justifiquen adecuadamente.</p>
</div>
</div>
</div>
</details>
<hr>
<ol start="42" type="1">
<li>¿Cuál será el límite máximo que se podrá reducir un contribuyente individual, en la base imponible general, por las aportaciones a un plan de pensiones?:</li>
</ol>
<!-- -->
<ol type="a">
<li><p>El menor de estas 2 cifras: 30 por 100 de la suma de los rendimientos netos del trabajo y de actividades económicas del ejercicio; 9.000 euros.</p></li>
<li><p>El menor de estas 2 cifras: 30 por 100 de la suma de los rendimientos netos del trabajo y de actividades económicas del ejercicio; 8.000 euros.</p></li>
<li><p>La mayor de estas 2 cifras: 30 por 100 de la suma de los rendimientos netos del trabajo y de actividades económicas del ejercicio; 10.000 euros.</p></li>
<li><p>Ninguna de las anteriores.</p></li>
</ol>
<details>
<summary>
</summary>
<div class="FOO callout-tip callout callout-style-simple">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-body-container">
<p>La respuesta <strong>correcta es la b</strong>.</p>
<p>El límite máximo que se puede reducir la base imponible general será el límite es la menor de estas 2 cifras:</p>
<ul>
<li><p>El 30% de la suma de los rendimientos netos del trabajo y de las actividad económicas.</p></li>
<li><p>8.000 euros.</p></li>
</ul>
</div>
</div>
</div>
</details>
<hr>
<ol start="43" type="1">
<li>En relación a la fiscalidad de depósitos, cuentas corrientes y renta fija, ¿Cuál será la retención aplicable para el ejercicio 2016?:</li>
</ol>
<!-- -->
<ol type="a">
<li><p>19,5%.</p></li>
<li><p>21%.</p></li>
<li><p>19%.</p></li>
<li><p>Ninguna de las anteriores</p></li>
</ol>
<details>
<summary>
</summary>
<div class="FOO callout-tip callout callout-style-simple">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-body-container">
<p>La respuesta <strong>correcta es la c</strong>.</p>
<p>La retención en 2016 y 2017 para los rendimientos de depósitos, cuentas corrientes y renta fija es del 19%</p>
</div>
</div>
</div>
</details>
<hr>
<ol start="44" type="1">
<li>¿En qué supuestos es posible el rescate de un plan de pensiones?:</li>
</ol>
<!-- -->
<ol type="a">
<li><p>Jubilación, fallecimiento, enfermedad grave, paro de larga duración y derechos consolidados que deriven de aportaciones que tengan más de 10 años de antigüedad.</p></li>
<li><p>Jubilación, fallecimiento, enfermedad grave y paro de larga duración.</p></li>
<li><p>Jubilación, fallecimiento y enfermedad grave.</p></li>
<li><p>Ninguna de las anteriores.</p></li>
</ol>
<details>
<summary>
</summary>
<div class="FOO callout-tip callout callout-style-simple">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-body-container">
<p>La respuesta <strong>correcta es la a</strong>.</p>
<p>Además de los casos de jubilación, fallecimiento, enfermedad grave y paro de larga duración, como novedad, se podrán rescatar los derechos consolidados (es decir, lo que se tenga acumulado) que deriven de aportaciones que tengan más de 10 años de antigüedad. Es decir, si se hace una aportación de 1.000 euros y a los 10 años se han convertido en 2.000 euros (por la rentabilidad obtenida), se pueden sacar esos 2.000 euros. Este nuevo supuesto se aplica a las aportaciones realizadas a partir del 1 de enero de 2015, por lo que hasta el 1 de enero de 2025 ninguna aportación cumplirá este nuevo supuesto (y para entonces es muy probable que haya cambiado la ley, incluso varias veces, así que no es aconsejable aportar dinero a planes de pensiones pensando que dentro de 10 años se podrá sacar con total seguridad, ya que podría no ser así).</p>
</div>
</div>
</div>
</details>
<hr>
<ol start="45" type="1">
<li>¿Es posible integrar en la base imponible del IRPF los rendimientos negativos ?</li>
</ol>
<!-- -->
<ol type="a">
<li><p>Sí, se integrarán en la base imponible todos los rendimientos, tanto los positivos como los negativos, con algunas particularidades.</p></li>
<li><p>No se integrarán, en ningún caso, en la base imponible los rendimientos los negativos derivados de la transmisión de activos financieros.</p></li>
<li><p>Sí. Se integrarán en la base imponible todos los rendimientos, tanto los positivos como los negativos, pero sólo cuando contribuyente hubiera adquirido activos financieros homogéneos en los dos meses anteriores o posteriores a aquella transmisión.</p></li>
<li><p>Ninguna de las anteriores.</p></li>
</ol>
<details>
<summary>
</summary>
<div class="FOO callout-tip callout callout-style-simple">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-body-container">
<p>La respuesta <strong>correcta es la a</strong>.</p>
<p>Sí. Se integrarán en la base imponible todos los rendimientos, tanto los positivos como los negativos, pero se establece un supuesto de diferimiento de la integración de rendimientos negativos cuando el contribuyente hubiera adquirido activos financieros homogéneos dentro de los dos meses anteriores o posteriores a aquella transmisión. En este supuesto los rendimientos negativos se integrarán a medida que se enajenen los que permanezcan en su patrimonio.</p>
</div>
</div>
</div>
</details>
<hr>
<ol start="46" type="1">
<li>El Sr.&nbsp;López, contribuyente del IRPF, adquirió 5.000 acciones de una empresa cotizada en la Bolsa a un precio unitario de 100 euros/acción. En el presente ejercicio fiscal ha adquirido 500 nuevas acciones totalmente liberadas en una operación de las denominadas “scrip dividend”. Si, una vez adquiridas las nuevas acciones liberadas, realiza una venta de 1.000 acciones a un precio de cotización de 120 euros/acción, ¿cuál sería la ganancia patrimonial integrable en la base imponible del IRPF?</li>
</ol>
<!-- -->
<ol type="a">
<li><p>29.090 euros.</p></li>
<li><p>20.000 euros.</p></li>
<li><p>120.000 euros.</p></li>
<li><p>No se integra ganancia patrimonial alguna en la base imponible del IRPF porque las acciones transmitidas proceden de un scrip dividend.</p></li>
</ol>
<details>
<summary>
</summary>
<div class="FOO callout-tip callout callout-style-simple">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-body-container">
<p>La respuesta <strong>correcta es la a</strong>.</p>
<p>En realidad, la fiscalidad de los scrips dividends es la misma que la de las ampliaciones de capital liberadas y la de los dividendos (aunque no sean realmente dividendos).</p>
<p>El contribuyente tenía 5.000 acciones compradas por 500,000 euros (50,000 x 100 = 500,000), al recibir las 500 acciones nuevas totalmente liberadas, pasa a tener 5,500 acciones compradas a 90.90909091 euros (500,000 / 5,500 = 90.90909091). Las 5,500 acciones son todas exactamente iguales, no hay diferencia entre ellas ni de precio de compra ni de fecha de compra (que es la de la compra de las 5,000 acciones originales).</p>
<p>El precio de compra del contribuyente ha bajado (antes era 100 y ahora es de 90.90), y cuando vende las acciones tendrá que calcular la plusvalía o minusvalía utilizando como precio de compra los nuevos 90.90 euros, en lugar de los 100 euros originales.</p>
<p>Por tanto,</p>
<p><span class="math inline">\(P _{compra}=90.90909091\)</span></p>
<p><span class="math inline">\(P _{venta}=120\)</span></p>
<p>Plusvalía/Minusvalía (unitaria):</p>
<p><span class="math display">\[ P/M = P _{venta}-P _{compra}=120-90.90909091=29.09090909 \,\, euros\]</span></p>
<p>Ganancia patrimonial integrable en la base imponible del IRPF:</p>
<p><span class="math display">\[1,000\,\, acciones \times 29.09090909\,\, euros/acci\acute { o }n = 29.090 \,\,euros\]</span></p>
</div>
</div>
</div>
</details>
<hr>
<ol start="47" type="1">
<li>En el ejercicio 2016, una pérdida patrimonial generada en más de un año podrá compensarse con:</li>
</ol>
<!-- -->
<ol type="a">
<li><p>Exclusivamente con ganancias patrimoniales generadas en más de un año.</p></li>
<li><p>Exclusivamente con ganancias patrimoniales, tanto si se han generado en más de un año como si no.</p></li>
<li><p>En primer lugar con las ganancias patrimoniales generadas en el ejercicio con independencia de su plazo de generación y, si tras dicha compensación aun resultase un saldo negativo, el mismo podrá compensarse, en su caso, con el saldo positivo de rendimientos del capital mobiliario, si bien con el límite del 15 por 100 de este último saldo positivo.</p></li>
<li><p>Exclusivamente con ganancias patrimoniales generadas en un plazo de un año o menos.</p></li>
</ol>
<details>
<summary>
</summary>
<div class="FOO callout-tip callout callout-style-simple">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-body-container">
<p>La respuesta <strong>correcta es la c</strong>.</p>
<p>Las ganancias y pérdidas patrimoniales se integran en la base imponible del ahorro. Si el saldo de la integración y compensación de este tipo de rendimientos fuera negativo, ahora su importe se podrá compensar con el saldo positivo del otro componente de la base imponible del ahorro, rendimientos de capital mobiliario, con el límite del 25% de dicho saldo positivo, según explica la Agencia Tributaria.</p>
<p>Eso sí, la reforma ha marcado un <strong>periodo transitorio y durante los años 2015, 2016 y 2017 el porcentaje de compensación no será del 25%, sino del 10%, 15% y 20% respectivamente</strong>.</p>
</div>
</div>
</div>
</details>
<hr>
<ol start="48" type="1">
<li>Un contribuyente del IRPF ha percibido 6.000 euros en concepto de dividendos procedentes de una cartera de valores cotizados en bolsa. ¿Qué coste fiscal tendrá la obtención de la citada renta?:</li>
</ol>
<!-- -->
<ol type="a">
<li><p>1.200 euros.</p></li>
<li><p>945 euros.</p></li>
<li><p>1.140 euros.</p></li>
<li><p>1.260 euros.</p></li>
</ol>
<details>
<summary>
</summary>
<div class="FOO callout-tip callout callout-style-simple">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-body-container">
<p>La respuesta <strong>correcta es la c</strong>.</p>
<p>Los tipos que se pagan por dividendos y demás rendimientos del capital mobiliario en 2016 y 2017 quedan en:</p>
<ul>
<li><p>Entre 0 y 6.000 euros: se paga el 19%.</p></li>
<li><p>Entre 6.000,01 y 50.000 euros: se paga el 21%.</p></li>
<li><p>Más de 50.000 euros: se paga el 23%.</p></li>
</ul>
<p>Por lo tanto el cálculo quedaría como sigue,</p>
<p><span class="math display">\[CF=6000\cdot0.19=1140\]</span></p>
</div>
</div>
</div>
</details>
<hr>
<ol start="49" type="1">
<li>¿Cómo ha de incorporarse en el IRPF la tenencia de una vivienda?:</li>
</ol>
<!-- -->
<ol type="a">
<li><p>Como imputación de renta inmobiliaria si no es vivienda habitual y no se alquila.</p></li>
<li><p>Como rendimiento del capital inmobiliario si esta arrendada.</p></li>
<li><p>No se incorpora si se trata de vivienda habitual.</p></li>
<li><p>Todas las respuestas anteriores son correctas.</p></li>
</ol>
<details>
<summary>
</summary>
<div class="FOO callout-tip callout callout-style-simple">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-body-container">
<p>La respuesta <strong>correcta es la d</strong>.</p>
<p>La tenencia de una vivienda hade incorporarse en el IRPF cómo una imputación de renta inmobiliaria si no es vivienda habitual y no se alquila; como rendimiento del capital inmobiliario si esta arrendada; y, en el caso de que se trate de la vivienda habitual del contribuyente, estará sujeta pero exenta del IRPF. Por lo que no se incorporará.</p>
</div>
</div>
</div>
</details>
<hr>
<p>50.Un contribuyente del IRPF que percibe unas rentas del trabajo de 22.000 euros ha aportado 7.500 euros a un plan de pensiones individual. Indique qué importe podrá reducir de la base imponible general del IRPF.</p>
<ol type="a">
<li><p>7.500 euros.</p></li>
<li><p>6.600 euros.</p></li>
<li><p>11.00 euros.</p></li>
<li><p>1.260 euros.</p></li>
</ol>
<details>
<summary>
</summary>
<div class="FOO callout-tip callout callout-style-simple">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-body-container">
<p>La respuesta <strong>correcta es la b</strong>.</p>
<p>Recordemos que, un contribuyente del IRPF, podrá reducir su base imponible general teniendo en cuenta un determinado límite. Siendo esta cantidad la menor de:</p>
<ul>
<li><p>8.000 euros.</p></li>
<li><p>o el 30% de los rendimientos del trabajo y actividades económicas, independientemente de la edad.</p></li>
</ul>
<p>Por lo tanto, en este caso tenemos que:</p>
<p><span class="math display">\[L_1=8000\]</span></p>
<p><span class="math display">\[L_2=RDT\cdot30\%=22000\cdot0.3=6600\]</span> Donde,</p>
<p><span class="math display">\[L_1&lt;L_2\]</span> Nos quedamos con el menor que son 6600.</p>
</div>
</div>
</div>
</details>
<hr>
<ol start="51" type="1">
<li>Antonio ha obtenido unos rendimientos netos del trabajo en el año de 25.000€, un rendimiento negativo de una actividad empresarial de -3.000€ y una pérdida patrimonial de la transmisión de un elemento patrimonial de -2.300€. ¿Cuál sería el resultado de una eventual compensación de rentas en la BIG?</li>
</ol>
<!-- -->
<ol type="a">
<li><p>19.700€.</p></li>
<li><p>25.000€.</p></li>
<li><p>22.000€.</p></li>
<li><p>22.700€.</p></li>
</ol>
<details>
<summary>
</summary>
<div class="FOO callout-tip callout callout-style-simple">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-body-container">
<p>La <strong>respuesta correcta es la c</strong>.</p>
<p>RNTP = 25.000€ → Rendimientos de la RENTA GENERAL</p>
<p>RAE = – 3.000€ → Rendimientos de la RENTA GENERAL</p>
<p>Compensación = 25.000 – 3.000 = 22.000€</p>
<p>GPP = – 2.300€ → GPP de la TEP de la RENTA del AHORRO (a compensar en 4 años ss)</p>
<p>Total BIG = 22.000€</p>
<p>Total BIA = 0</p>
</div>
</div>
</div>
</details>
<hr>
<ol start="52" type="1">
<li>Indicar cuál de los siguientes rendimientos del trabajo personal podría integrarse con una reducción del 30%:</li>
</ol>
<!-- -->
<ol type="a">
<li><p>Indemnización por resolución de mutuo acuerdo de la relación laboral.</p></li>
<li><p>Prima variable de productividad vinculada a los resultados obtenidos por la empresa en los últimos 3 años, cobrada por primera vez.</p></li>
<li><p>Ambos.</p></li>
<li><p>A partir del 1 de enero de 2015 no hay reducciones de los rendimientos .</p></li>
</ol>
<details>
<summary>
</summary>
<div class="FOO callout-tip callout callout-style-simple">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-body-container">
<p>La <strong>respuesta correcta es la c</strong>.</p>
<p>Reducción del 30% sobre los rendimientos con periodo de generación superior a 2 años o que califican de notoriamente irregulares, que se imputen en un único período impositivo (siempre que no se haya tenido un rendimiento reducido fiscalmente en este mismo sentido en los 5 años anteriores).</p>
<p>En el caso de rendimientos derivados de la extinción de una relación laboral, común o especial, se considerará como período de generación, el número de años de servicio del trabajador. En caso de que estos rendimientos se cobren de forma fraccionada, el cómputo del período de generación deberá tener en cuenta el número de años de fraccionamiento, en los términos que reglamentariamente se establezcan.</p>
<p>La resolución de mutuo acuerdo se asimila a la indemnización por ser notoriamente irregular.</p>
</div>
</div>
</div>
</details>
<hr>
<ol start="53" type="1">
<li>¿Qué gastos son deducibles de los rendimientos del trabajo personal?</li>
</ol>
<!-- -->
<ol type="a">
<li><p>Cotizaciones del trabajador a la Seguridad Social.</p></li>
<li><p>Cuotas sindicales.</p></li>
<li><p>Gastos de DEFENSA JURÍDICA, hasta un límite de 300 euros al año.</p></li>
<li><p>Todos los anteriores .</p></li>
</ol>
<details>
<summary>
</summary>
<div class="FOO callout-tip callout callout-style-simple">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-body-container">
<p>La <strong>respuesta correcta es la d</strong>.</p>
<p>Gastos deducibles: Seguridad Social, detracciones por derechos pasivos, cotizaciones a colegios de huérfanos, cuotas sindicales, colegiación obligatoria (límite 500€), defensa jurídica (límite de 300€) y en concepto de otros gastos distintos de los anteriores, 2.000€ anuales (con el límite del rendimiento íntegro del trabajo minorado por el resto de gastos deducibles), que se incrementarán en los siguientes casos:</p>
<ul>
<li><p>Por movilidad geográfica: 2.000€ adicionales.</p></li>
<li><p>Personas con discapacidad: 3.500€ adicionales anualmente, y 7.750€ anuales para las personas con discapacidad que siendo trabajadores activos acrediten necesitar ayuda de terceras personas, o movilidad reducida, o un grado de discapacidad igual o superior al 65%.</p></li>
</ul>
</div>
</div>
</div>
</details>
<hr>
<ol start="54" type="1">
<li>¿Cuál será el rendimiento neto procedente del arrendamiento del siguiente inmueble (no vivienda)?</li>
</ol>
<table class="table">
<tbody>
<tr class="odd">
<td style="text-align: left;">Rentas: 1.000</td>
</tr>
<tr class="even">
<td style="text-align: left;">Intereses: 800</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Reparaciones: 250</td>
</tr>
</tbody>
</table>
<ol type="a">
<li><p>Cero.</p></li>
<li><p>-50</p></li>
<li><p>750 (interés no deducible).</p></li>
<li><p>Ninguna de las anteriores: hay que calcularlo en función de la duración del contrato .</p></li>
</ol>
<details>
<summary>
</summary>
<div class="FOO callout-tip callout callout-style-simple">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-body-container">
<p>La <strong>respuesta correcta es la a</strong>.</p>
<p>INGRESOS: 1.000€</p>
<p>Gastos financiación y reparación: 800€ + 250€ = 1.050€</p>
<p>Pero como NO pueden hacer rendimiento negativo del inmueble =</p>
<p><strong>Gastos financiación y reparación: 1.000€</strong></p>
<p><strong>RCI Neto</strong> = 1.000 – 1.000 Gastos financiación y reparación (límite) = <strong>0</strong></p>
<p>(*) Quedaría pendiente de compensar en los 4 siguientes ejercicios los Gastos financiación y reparación no deducidos por el límite de los ingresos (1.050 – 1.000 = 50€ pendientes)</p>
</div>
</div>
</div>
</details>
<hr>
<ol start="55" type="1">
<li>¿Cuál será el rendimiento neto procedente del arrendamiento del siguiente inmueble (sí vivienda)?</li>
</ol>
<table class="table">
<tbody>
<tr class="odd">
<td style="text-align: left;">Rentas: 2.000</td>
</tr>
<tr class="even">
<td style="text-align: left;">Intereses: 800</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Reparaciones: 250</td>
</tr>
</tbody>
</table>
<ol type="a">
<li><p>Cero.</p></li>
<li><p>950</p></li>
<li><p>380</p></li>
<li><p>-50 (1000 X 50% de reducción -800 -250)</p></li>
</ol>
<details>
<summary>
</summary>
<div class="FOO callout-tip callout callout-style-simple">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-body-container">
<p>La <strong>respuesta correcta es la c</strong>.</p>
<p>INGRESOS: 2.000€</p>
<p>Gastos financiación y reparación: 800€ + 250€ = 1.050€</p>
<p>RCI Neto = 2.000 – 1.050 = 950€</p>
<ul>
<li><p>Reducción del 60% del rendimiento neto positivo <strong>por ser vivienda</strong>:</p>
<ul>
<li><strong>RCI</strong> = 950 x (1 – 0,60) = <strong>380€</strong></li>
</ul></li>
</ul>
</div>
</div>
</div>
</details>
<hr>
<ol start="56" type="1">
<li>Indique cuál de las siguientes afirmaciones es correcta en relación con los Planes de Ahorro a Largo Plazo.</li>
</ol>
<!-- -->
<ol type="a">
<li><p>La rentabilidad obtenida tributa como rendimiento del capital mobiliario derivado de la participación en fondos propios de entidades.</p></li>
<li><p>La rentabilidad obtenida, que se califica como rendimiento del capital mobiliario derivado de la cesión a terceros de capitales propios, se encuentra exceptuada de gravamen a condición de que la misma se perciba en forma de capital a partir del quinto año desde la formalización del Plan, y siempre y cuando durante dicho plazo no se haya efectuado disposición anticipada alguna de la inversión ni se hayan invertido más de 5.000 euros en cada año.</p></li>
<li><p>Las cantidades invertidas en cada año no pueden exceder de 8.000 euros.</p></li>
<li><p>Aunque la cantidad máxima que se puede invertir cada año no puede superar 5.000 euros, sin embargo puede reducirse de la base imponible general.</p></li>
</ol>
<details>
<summary>
</summary>
<div class="FOO callout-tip callout callout-style-simple">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-body-container">
<p>La respuesta <strong>correcta es la b</strong>.</p>
<p>En los Planes de Ahorro a Largo Plazo la rentabilidad obtenida, que se califica como rendimiento del capital mobiliario derivado de la cesión a terceros de capitales propios, se encuentra exceptuada de gravamen a condición de que la misma se perciba en forma de capital a partir del quinto año desde la formalización del Plan, y siempre y cuando durante dicho plazo no se haya efectuado disposición anticipada alguna de la inversión ni se hayan invertido más de 5.000 euros en cada año.</p>
</div>
</div>
</div>
</details>
<hr>
<ol start="57" type="1">
<li>¿Cuál es el límite de la reducción por aportaciones y contribuciones a sistemas de previsión social?</li>
</ol>
<!-- -->
<ol type="a">
<li><p>La menor de las siguientes cantidades: 8.000 euros anuales o 30% de los rendimientos netos del trabajo más los rendimientos de actividades económicas.</p></li>
<li><p>La menor de las siguientes cantidades: 8.000 euros o 20% de los rendimientos netos del trabajo más los rendimientos de actividades económicas.</p></li>
<li><p>La menor de las siguientes cantidades: 8.000 euros por las aportaciones empresariales imputadas al trabajador y 8.000 euros por las aportaciones individuales.</p></li>
<li><p>Ninguna de las anteriores.</p></li>
</ol>
<details>
<summary>
</summary>
<div class="FOO callout-tip callout callout-style-simple">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-body-container">
<p>La <strong>respuesta correcta es la a</strong>.</p>
<p>Límite conjunto de las reducciones por aportaciones y contribuciones a sistemas de previsión social (<strong>Planes de Pensiones, PPA, Planes de Previsión Social Empresarial, Seguros de Dependencia y Mutualidades de Previsión Social</strong>) → la menor de las siguientes cantidades:</p>
<ul>
<li><p>8.000€ anuales.</p></li>
<li><p>30% de los Rendimientos Netos Trabajo (RNT) más los Rendimientos Actividades Económicas (RAE).</p></li>
</ul>
</div>
</div>
</div>
</details>
<hr>
<ol start="58" type="1">
<li>¿Por cuál de los siguientes impuestos tiene que tributar el importe recibido por la viuda de un trabajador del plan de pensiones de empleo correspondiente a su marido?</li>
</ol>
<!-- -->
<ol type="a">
<li><p>Por impuesto de patrimonio.</p></li>
<li><p>Por IRPF.</p></li>
<li><p>Por impuesto de sucesiones y donaciones.</p></li>
<li><p>Por ninguno de ellos por su condición de viuda.</p></li>
</ol>
<details>
<summary>
</summary>
<div class="FOO callout-tip callout callout-style-simple">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-body-container">
<p>La <strong>respuesta correcta es la b</strong>.</p>
<p>Las prestaciones de un Plan de Pensiones tributan, en todo caso, como Rendimiento de Trabajo en el IRPF</p>
</div>
</div>
</div>
</details>
<hr>
<ol start="59" type="1">
<li>¿Cuál de los siguientes productos no influye en el tipo aplicable de la escala de la base general del IRPF?</li>
</ol>
<!-- -->
<ol type="a">
<li><p>Planes de pensiones</p></li>
<li><p>Planes de previsión asegurados</p></li>
<li><p>Planes individuales de ahorro sistemático</p></li>
<li><p>Todos los anteriores influyen</p></li>
</ol>
<details>
<summary>
</summary>
<div class="FOO callout-tip callout callout-style-simple">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-body-container">
<p>La <strong>respuesta correcta es la c</strong>.</p>
<p>La normativa del IRPF establece una serie de rentas concretas que declara como exentas, esto es, que no deben tenerse en cuenta para conformar la base imponible y, en consecuencia, quedan liberadas de tributación.</p>
<p>Entre ellas, se encuentran los rendimientos que se pongan de manifiesto en el momento de la constitución de rentas vitalicias aseguradas resultantes de los planes individuales de ahorro sistemático (PIAS).</p>
</div>
</div>
</div>
</details>
<hr>
<ol start="60" type="1">
<li>¿Cuál será la tributación de la venta del siguiente fondo de inversión siempre que no se hayan realizado transmisiones desde enero de 2015 superiores a 400.000 euros acogidas a los coeficientes de abatimiento?</li>
</ol>
<table class="table">
<tbody>
<tr class="odd">
<td style="text-align: left;">Coste adquisición el 20/11/1988: 100</td>
</tr>
<tr class="even">
<td style="text-align: left;">Valor liquidativo al 31/12/2005: 250</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Valor venta el 21/03/2016: 220</td>
</tr>
</tbody>
</table>
<ol type="a">
<li><p>120</p></li>
<li><p>17,18</p></li>
<li><p>Habrá una minusvalía de 30 para compensar con otras ganancias patrimoniales.</p></li>
<li><p>Cero.</p></li>
</ol>
<details>
<summary>
</summary>
<div class="FOO callout-tip callout callout-style-simple">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-body-container">
<p>La <strong>respuesta correcta es la c</strong>.</p>
<p>La fecha de adquisición es anterior al 31/12/1994 y no se han realizado transmisiones desde enero de 2015 por un valor superior a 400.000€, por tanto, son aplicables los coeficientes de abatimiento a toda la plusvalía:</p>
<ul>
<li><p>Para los fondos de inversión el coeficiente de abatimiento es 14,28%</p></li>
<li><p>El número de años, redondeando por exceso, desde la fecha de adquisición (20/11/1988) hasta 31/12/1994 es 7</p></li>
<li><p>Abatimiento del 14,28% x 7 = 100% de la ganancia generada hasta el 20/01/2006</p></li>
<li><p>Como el Valor IP 2005 = 250 &gt; Valor de Transmisión = 220 se considera que toda la ganancia patrimonial se ha generado con anterioridad a 20 de enero de 2006.</p></li>
</ul>
<p>Por tanto, <strong>la tributación será 0</strong>.</p>
</div>
</div>
</div>
</details>
<hr>
<ol start="61" type="1">
<li>Don Manuel contrata un seguro de prima única de 10.000€. La prestación consiste en una renta anual vitalicia de 2.000€, que empezará a percibirse trascurridos 10 años desde el pago de la prima. La edad del Sr.&nbsp;Don Manuel en el momento de constitución de la renta es de 55 años. La rentabilidad acumulada en el momento de constitución de la renta asciende a 3.000€, ¿qué rendimiento integrará en la base imponible?</li>
</ol>
<!-- -->
<ol type="a">
<li><p>860 euros durante los diez primeros años y el resto, 560 euros.</p></li>
<li><p>560 euros cada año.</p></li>
<li><p>860 euros en el ejercicio, con reducción del 40%, y 560 euros el resto de ejercicios.</p></li>
<li><p>3.000 euros por un porcentaje en función de la duración de la renta.</p></li>
</ol>
<details>
<summary>
</summary>
<div class="FOO callout-tip callout callout-style-simple">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-body-container">
<p>La <strong>respuesta correcta es la a</strong>.</p>
<p><strong>Contrato de seguro individual de renta vitalicia diferida</strong> con una prima única de 10000€. La renta anual vitalicia de 2000€ se empieza a percibir transcurridos 10 años desde el pago de la prima, siendo la edad del rentista 55 años.</p>
<p>La Rentabilidad acumulada = valor actual financiero-actuarial de la renta que se constituye menos el importe de las primas satisfechas = 3000€ (dato)</p>
<p>El RCM a imputar será:</p>
<ul>
<li><p>Durante los 10 primeros años = (28% * 2000€) + (3000€/10) = 860€</p></li>
<li><p>Para el resto = 28% * 2000€ = 560€</p></li>
</ul>
</div>
</div>
</div>
</details>
<hr>
<ol start="62" type="1">
<li>Un Fondo Monetario inscrito en la CNMV, ¿cómo tributa en el Impuesto sobre Sociedades?</li>
</ol>
<!-- -->
<ol type="a">
<li><p>Tributa al tipo del 25% a partir del 1 de enero de 2007.</p></li>
<li><p>Tributa en el Impuesto sobre Sociedades al tipo del 1%.</p></li>
<li><p>No tributan en el Impuesto sobre Sociedades, al no tener personalidad jurídica.</p></li>
<li><p>Tributan en el Impuesto sobre Sociedades al tipo general del 30%.</p></li>
</ol>
<details>
<summary>
</summary>
<div class="FOO callout-tip callout callout-style-simple">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-body-container">
<p>La <strong>respuesta correcta es la b</strong>.</p>
<p>Las SICAVs y los FI mobiliarios tributan en el IS al 1%</p>
</div>
</div>
</div>
</details>
<hr>
<ol start="63" type="1">
<li>La diferencia entre la renta fija y la renta variable es…</li>
</ol>
<!-- -->
<ol type="a">
<li><p>Que la renta variable puede ser negociable pero la renta fija no.</p></li>
<li><p>La única diferencia está en la retención aplicable.</p></li>
<li><p>Que la renta variable retribuye una participación y la renta fija se refiere a una retribución al capital ajeno.</p></li>
<li><p>Ninguna de las anteriores es correcta.</p></li>
</ol>
<details>
<summary>
</summary>
<div class="FOO callout-tip callout callout-style-simple">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-body-container">
<p>La <strong>respuesta correcta es la c</strong>.</p>
<p>La diferencia entre la renta fija y la renta variable es que la renta variable retribuye una participación y la renta fija se refiere a una retribución al capital ajeno.</p>
</div>
</div>
</div>
</details>
<hr>
<ol start="64" type="1">
<li>En los planes de pensiones y a efectos del Impuesto de la Renta de la Personas Físicas (IRPF), existe un régimen transitorio que permite aplicar una reducción del 40% sobre los derechos consolidados:</li>
</ol>
<!-- -->
<ol type="a">
<li><p>Por la parte correspondiente a aportaciones realizadas hasta el 31 de diciembre de 2016.</p></li>
<li><p>Para el caso de prestaciones en forma de renta.</p></li>
<li><p>Exclusivamnete para prestaciones derivadas de contingencias acaecidas antes del 1 de enero de 2007.</p></li>
<li><p>Si la primera aportación tiene una antigüedad de dos años, como mínimo desde que se realizo hasta la fecha de la contingencia.</p></li>
</ol>
<details>
<summary>
</summary>
<div class="FOO callout-tip callout callout-style-simple">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-body-container">
<p><strong>Respueta correcta la d</strong></p>
<p>En los planes de pensiones, y a efectos del Impuesto de la Renta de la Personas Físicas (IRPF), en el caso de prestaciones de forma de capital, existe un <strong>régimen transitorio para prestaciones derivadas de contingencias</strong> acaecidas antes del 1 de enero de 2007, y de aquellas producidas a partir de esa fecha, por la parte correspondiente a aportaciones realizadas hasta el 31 de diciembre de 2006.</p>
<p>En ambos casos, con carácter general, <strong>los beneficiarios podrán aplicar una reducción del 40% sobre los derechos consolidados, si la primera aportación tiene una antigüedad de dos años, como mínimo, desde que se realizó hasta la fecha de la contingencia</strong>.</p>
</div>
</div>
</div>
</details>
<hr>
<ol start="65" type="1">
<li>El reembolso de una IIC´s (que no sea ETF) por parte de un clientese destina a laadquisición o suscripción de otras participaciones en otras IIC´s, ¿qué estatus mantendrán las nuevas participaciones del nuevo fondo contratado?</li>
</ol>
<!-- -->
<ol type="a">
<li><p>El mismo valor y la misma fecha de adquisición de las participaciones reembolsadas (las de la primera IIC).</p></li>
<li><p>El valor de adquisición de las nuevas participaciones, y la misma fecha de adquisición de las participaciones reembolsadas (las de la primera IIC).</p></li>
<li><p>El mismo valor y fecha de adquisición de las participaciones nuevas.</p></li>
<li><p>El valor de adquisición de las nuevas participaciones y la misma fecha de adquisición de las nuevas.</p></li>
</ol>
<details>
<summary>
</summary>
<div class="FOO callout-tip callout callout-style-simple">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-body-container">
<p><strong>Respueta correcta la a</strong></p>
<p>El <strong>tratamiento fiscal</strong> de los fondos de inversión, en lo que a <strong>traspasos de fondos</strong> se refiere, responde a la siguiente regla:</p>
<ul>
<li>Si el reembolso de IIC se destina a la adquisición o suscripción de otras participaciones en IIC, el participe NO computará en su IRPF la ganancia o pérdida obtenida, y <strong>las nuevas participaciones conservan el valor y fecha de adquisición de las participaciones anteriores (las de la primera IIC)</strong>.</li>
</ul>
</div>
</div>
</div>
</details>
<hr>
<ol start="66" type="1">
<li>Una entidad financiera realiza una promoción consistente en la entrega de una vajilla a todos aquellos clientes que realicen una imposición por un importe de 6.000 euros o más y mantengan las cantidades depositadas durante 18 meses. Para beneficiarse de esta promoción, el Sr.&nbsp;Fernández realizó la imposición de 6.000 euros, cumpliendo el requisito de mantenimiento de la inversión. ¿Qué impacto fiscal tendría esta imposición para el Sr.&nbsp;Fernández en en su TIR</li>
</ol>
<!-- -->
<ol type="a">
<li><p>No se genera renta alguna en el IRPF.</p></li>
<li><p>Se generará una ganancia patrimonial que tributará en la base imponible del ahorro aplicando el tipo de gravamen del 19%.</p></li>
<li><p>Se generará un rendimiento del capital mobiliario que tributará en la parte general de la base imponible una vez reducido en un 40%.</p></li>
<li><p>Se generará un rendimiento del capital mobiliario que tributará en la base imponible del ahorro.</p></li>
</ol>
<details>
<summary>
</summary>
<div class="FOO callout-tip callout callout-style-simple">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-body-container">
<p><strong>Respueta correcta la d</strong></p>
<p>Para las personas físicas que tributan en IRPF los depósitos bancarios se consideran una cesión a terceros de capitales propios del sujeto pasivo. Las utilidades o contraprestaciones de todo tipo, dinerarias o en especie, como <strong>los intereses y cualquier otra forma de retribución pactada como remuneración (obsequios, etc.), derivadas de los mismos tributan como rendimientos de capital mobiliario por cesión a terceros de capitales propios</strong>.</p>
<p>Estos rendimientos derivados de la cesión a terceros de capitales propios <strong>pasan a formar parte de la base imponible del ahorro</strong>.</p>
</div>
</div>
</div>
</details>
<hr>
<ol start="67" type="1">
<li>En ISD la deuda por un préstamo:</li>
</ol>
<!-- -->
<ol type="a">
<li><p>Es deducible si se trata de una deuda del causante reconocida en sentencia judicial firme.</p></li>
<li><p>Es deducible si corresponde la misma al causante fallecido, sin excepción.</p></li>
<li><p>Es deducible exclusivamente si se trata de una deuda del causante con un heredero, legatario, cónyuge o pariente.</p></li>
<li><p>No es deducible en una donación si corresponde al donante, aunque esté garantizada con derecho real que recaiga sobre el bien o derecho transmitido y el adquirente haya asumido fehacientemente la obligación de pagarla.</p></li>
</ol>
<details>
<summary>
</summary>
<div class="FOO callout-tip callout callout-style-simple">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-body-container">
<p><strong>Respueta correcta la a</strong></p>
<p>En ISD la deuda por el préstamo es deducible para determinar la base imponible en el supuesto mortis causa (herencias y similares) en los siguientes casos: Sea deuda del causante fallecido reconocida en sentencia judicial firme; Sea deuda contraída antes del fallecimiento si su existencia se acredita por documento público o privado, o se justifica de cualquier modo su existencia, salvo las deudas que lo fueren a favor de herederos, legatarios, cónyuges y parientes, aunque renuncien a la herencia (éstas no son nunca deducibles).</p>
<p>En el supuesto inter vivos (donaciones y equivalentes) la deuda del préstamo es deducible si corresponde al garantizada con derecho real que recaiga sobre el bien o derecho transmitido y el adquirente ha asumido fehacientemente la obligación de pagarla.</p>
</div>
</div>
</div>
</details>
<hr>
<ol start="68" type="1">
<li>Un residente fiscal en España reembolsa en marzo de 2016 por 5.000 euros, con destino a su cuenta de ahorros, diversas participaciones en un Fondo de Inversión español que había comprado en abril de 2015 por 4.000 euros. La tributación de esta operación en el IRPF 2016:</li>
</ol>
<!-- -->
<ol type="a">
<li><p>Es una ganancia patrimonial generada en más de un año que, por tanto, se reducirá en un 40%. Es decir, la ganancia patrimonial neta será de 600 euros.</p></li>
<li><p>Es una ganancia patrimonial de 1.000 euros que se integrará en la base imponible del ahorro.</p></li>
<li><p>Es una ganancia patrimonial de 1.000 euros, generada en más de un año no sujeta a tributación pues se le aplica el diferimiento por reinversión en otros fondos.</p></li>
<li><p>Es una ganancia patrimonial de 1.000 euros que se integrará en la base imponible general.</p></li>
</ol>
<details>
<summary>
</summary>
<div class="FOO callout-tip callout callout-style-simple">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-body-container">
<p><strong>Respueta correcta la b</strong></p>
<p>Determinada la ganancia o pérdida patrimonial obtenida por la enajenación de estas acciones o participaciones de IIC, se integra en la renta del ahorro, con independencia de su período de generación.</p>
</div>
</div>
</div>
</details>
<hr>
<ol start="69" type="1">
<li>Ana (con rendimientos netos del trabajo de 100.000 euros) aporta 1.500 euros al plan de pensiones individual de su cónyuge Antonio, que no trabaja aunque obtiene un rendimiento neto del capital inmobiliario de 6.000 euros al año por el alquiler de un local de su propiedad. En el IRPF de Ana, ¿qué reducción en la base imponible corresponde por la aportación al plan de pensiones de su marido?</li>
</ol>
<!-- -->
<ol type="a">
<li><p>0 euros.</p></li>
<li><p>2.000 euros.</p></li>
<li><p>1.500 euros.</p></li>
<li><p>2.500 euros.</p></li>
</ol>
<details>
<summary>
</summary>
<div class="FOO callout-tip callout callout-style-simple">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-body-container">
<p><strong>Respueta correcta la c</strong></p>
<p>Adicionalmente, la Ley del IRPF (artículo 51.7) permite, bajo ciertos requisitos y límites, reducir en la base imponible general del sujeto pasivo las aportaciones realizadas a Sistemas de Previsión Social de los que sea partícipe, mutualista o tomador su cónyuge.</p>
<p>Tal reducción se puede hacer con independencia de las reducciones realizadas por las aportaciones del partícipe y por las contribuciones empresariales imputadas, respetando el orden legal de aplicación de las reducciones. Para ello el cónyuge no ha de obtener rendimientos netos del trabajo o de actividades económicas, o si los obtiene que no superen 8.000 euros anuales. El límite único y máximo para esta reducción será de 2.500 euros anuales y por su aplicación no se puede dar lugar a una base liquidable general negativa.</p>
</div>
</div>
</div>
</details>
<hr>
<ol start="70" type="1">
<li>En el caso de que una persona física no residente en España herede bienes o derechos situados en territorio español, el impuesto aplicable es…</li>
</ol>
<!-- -->
<ol type="a">
<li><p>IRNR</p></li>
<li><p>ISD</p></li>
<li><p>Se trata de adquisiciones exentas para no residentes</p></li>
<li><p>Ninguna de las anteriores</p></li>
</ol>
<details>
<summary>
</summary>
<div class="FOO callout-tip callout callout-style-simple">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-body-container">
<p><strong>Respueta correcta la b</strong></p>
<p>Para una persona física no residente en España herede bienes o derechos situados en territorio español, el impuesto aplicable será el ISD.</p>
</div>
</div>
</div>
</details>
<hr>
<ol start="71" type="1">
<li>El reparto de beneficios por parte de una SICAV a sus accionistas, supone para éstos…</li>
</ol>
<!-- -->
<ol type="a">
<li><p>No tributa</p></li>
<li><p>Ganancia patrimonial</p></li>
<li><p>Rendimiento de capital mobiliario</p></li>
<li><p>Minorar el precio de adquisición de las acciones</p></li>
</ol>
<details>
<summary>
</summary>
<div class="FOO callout-tip callout callout-style-simple">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-body-container">
<p><strong>Respueta correcta la c</strong></p>
<p>El reparto de beneficios por parte de una SICAV a sus accionistas, supone para éstos un rendimiento de capital mobiliario.</p>
</div>
</div>
</div>
</details>
<hr>
<ol start="72" type="1">
<li>Una persona aportó a un seguro con prestación en forma de capital una prima única de 10.000 euros, al vencimiento del contrato percibe 15.000 euros, el RCM a declarar es de:</li>
</ol>
<!-- -->
<ol type="a">
<li><p>15.000 euros con la reducción del 40% por rendimiento generado en más de 2 años.</p></li>
<li><p>15.000 euros multiplicados por un porcentaje según la edad del perceptor.</p></li>
<li><p>5.000 euros.</p></li>
<li><p>15.000 euros.</p></li>
</ol>
<details>
<summary>
</summary>
<div class="FOO callout-tip callout callout-style-simple">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-body-container">
<p>La <strong>respuesta correcta es la c</strong>.</p>
<p>Seguros de vida con prestación <strong>en forma de capital</strong>:</p>
<ul>
<li>RCM = 15.000 – 10.000 = 5.000€</li>
</ul>
<p>(*) Se elimina con efectos uno de enero de 2015 el mecanismo compensatorio existente para prestaciones de capital diferido derivadas de un contrato de seguro de vida o invalidez contratado antes del 20 de enero de 2006, cuando el nuevo régimen resulte menos favorable.</p>
</div>
</div>
</div>
</details>
<hr>
<ol start="73" type="1">
<li>¿Qué régimen fiscal es aplicable a los inversores en los Exchanged Traded Funds (ETF)?</li>
</ol>
<!-- -->
<ol type="a">
<li><p>Se aplica la misma fiscalidad que los Fondos de Inversión.</p></li>
<li><p>Se aplica la fiscalidad correspondiente a las acciones, salvo en lo relativo a los dividendos, los cuales no disfrutan de la exención de los primeros 1.500 euros desde el año 2014.</p></li>
<li><p>Se aplica la fiscalidad correspondiente a las acciones, salvo en lo relativo a las plusvalías, las cuales tributan como rendimiento del capital mobiliario.</p></li>
<li><p>Se aplica la fiscalidad correspondiente a las acciones sin ninguna excepción.</p></li>
</ol>
<details>
<summary>
</summary>
<div class="FOO callout-tip callout callout-style-simple">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-body-container">
<p>La <strong>respuesta correcta es la b</strong>.</p>
<p><strong>Se le aplica el mismo régimen de fiscalidad que a la transmisión de acciones</strong>. Las ganancias (precio de venta menos precio de compra) se integran en la base del ahorro como Ganancia Patrimonial aplicándose una tarifa progresiva en el 2017 del 19% / 21% / 23%, <strong>sin retención</strong>.</p>
<p>La principal diferencia estriba en que para <strong>los dividendos otorgados por ETFs no era en 2014 de aplicación la exención fiscal en los primeros 1.500 €</strong>. Todo dividendo recibido por ETFs tributaba como rendimiento del capital mobiliario con retención fiscal.</p>
</div>
</div>
</div>
</details>
<hr>
<ol start="74" type="1">
<li>Que tienen en común fiscalmente los fondos cotizados (o ETFs) con los contratos por diferencia (o CFDs):</li>
</ol>
<!-- -->
<ol type="a">
<li><p>Que no se encuentran sujetos a retención.</p></li>
<li><p>Que los rendimientos se califican como ganancias o pérdidas patrimoniales a integrar en la base imponible del ahorro.</p></li>
<li><p>Reciben el mismo tratamiento fiscal que las acciones.</p></li>
<li><p>Todas las respuestas son correctas.</p></li>
</ol>
<details>
<summary>
</summary>
<div class="FOO callout-tip callout callout-style-simple">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-body-container">
<p>La <strong>respuesta correcta es la d</strong>.</p>
<p><strong>Tanto los fondos cotizados (o ETFs) como los contratos por diferencia (o CFDs) reciben el mismo tratamiento fiscal que las acciones</strong>, y se califican como <strong>ganancias o pérdidas patrimoniales</strong> al 19% / 21% / 23% (en 2017) a integrar en la <strong>base</strong> imponible <strong>del ahorro y sin retención</strong>.</p>
</div>
</div>
</div>
</details>
<hr>
<ol start="75" type="1">
<li>Cuál de las siguientes afirmaciones es cierta en relación a los beneficios fiscales de los planes de pensiones y los Planes Individuales de Ahorro Sistemático (PIAS):</li>
</ol>
<!-- -->
<ol type="a">
<li><p>Los beneficios fiscales de los planes de pensiones se producen en el momento de la aportación, a diferencia de los Planes Individuales de Ahorro Sistemático (PIAS), que se producen en la salida.</p></li>
<li><p>Los beneficios fiscales de los Planes Individuales de Ahorro Sistemático (PIAS) se producen en el momento de la aportación, a diferencia de los planes de pensiones, que se producen en la salida.</p></li>
<li><p>En ambos casos los beneficios fiscales se producen en el momento de la aportación.</p></li>
<li><p>En ambos casos los beneficios fiscales se producen en el momento de salida.</p></li>
</ol>
<details>
<summary>
</summary>
<div class="FOO callout-tip callout callout-style-simple">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-body-container">
<p>La <strong>respuesta correcta es la a</strong>.</p>
<p>Los beneficios fiscales de los planes de pensiones se producen en el momento de la aportación, a diferencia de los Planes Individuales de Ahorro Sistemático (PIAS), que se producen en la salida.</p>
</div>
</div>
</div>
</details>
<hr>
<ol start="76" type="1">
<li>¿Cómo tributan las primas de emisión de acciones o participaciones?</li>
</ol>
<!-- -->
<ol type="a">
<li><p>Depende de si las acciones cotizan o no en bolsa.</p></li>
<li><p>En acciones cotizadas, partir del 1 de Enero de 2017 el importe de la transmisión será Ganancia Patrimonial, sometida en principio a una retención del 19%.</p></li>
<li><p>En acciones no cotizadas, el importe obtenido en la transmisión de derechos tendrá la consideración de Ganancia Patrimonial para el transmitente, en el periodo en el que se produzca la transmisión de dichos derechos.</p></li>
<li><p>Todas las respuestas son correctas.</p></li>
</ol>
<details>
<summary>
</summary>
<div class="FOO callout-tip callout callout-style-simple">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-body-container">
<p>La <strong>respuesta correcta es la d</strong>.</p>
<p>El tratamiento fiscal de estos derechos <strong>depende de si las acciones cotizan o no en bolsa</strong>:</p>
<ol type="1">
<li>Acciones que <strong>cotizan en Bolsa</strong>:</li>
</ol>
<!-- -->
<ol type="a">
<li><p>Si el importe obtenido por la transmisión de los derechos NO ES &gt; Valor de Adquisición de las acciones de las que proceden (situación más normal), la venta no tiene efectos fiscales hasta que se transmitan las acciones. En dicho momento el importe de los derechos vendidos minorará el valor de adquisición para calcular la ganancia o pérdida patrimonial. Hasta 31 de diciembre de 2016. Ya que <strong>a partir del 1 de Enero de 2017 el importe de la transmisión será GANANCIA PATRIMONIAL, sometida en principio a una retención del 19%</strong>.</p></li>
<li><p>Si el importe obtenido por la transmisión de los derechos ES &gt; Valor de Adquisición de las acciones de las que proceden (situación remota), el exceso tiene la consideración de Ganancia Patrimonial. Posteriormente, cuando se vendan las acciones el valor de adquisición de las mismas será cero, a efectos de calcular la ganancia o pérdida patrimonial.</p></li>
</ol>
<!-- -->
<ol start="2" type="1">
<li>Acciones <strong>sin cotización</strong>:</li>
</ol>
<p><strong>El importe obtenido en la transmisión de derechos tendrá la consideración de Ganancia Patrimonial para el transmitente, en el periodo en el que se produzca la transmisión de dichos derechos</strong>.</p>
<p>Nota: <strong>en los dos casos se le aplica retención en el año 2017 (a diferencia de lo que ocurría en 2016)</strong>.</p>
</div>
</div>
</div>
</details>
<hr>
<ol start="77" type="1">
<li>¿Cuál de las siguientes afirmaciones es falsa?</li>
</ol>
<!-- -->
<ol type="a">
<li><p>Se entenderá por cuota íntegra la cantidad resultante de aplicar a la base imponible el tipo de gravamen.</p></li>
<li><p>La exención por doble imposición de dividendos interna será aplicable cuando los dividendos o participaciones en beneficios procedan de entidades residentes en las que el porcentaje de participación, directo o indirecto, sea igual o superior al cinco por ciento, siempre que dicho porcentaje se hubiere tenido de manera ininterrumpida durante el año anterior al día en que sea exigible el beneficio que se distribuya o, en su defecto, que se mantenga durante el tiempo que sea necesario para completar un año.</p></li>
<li><p>Los dividendos se integran en la base imponible por su importe bruto.</p></li>
<li><p>Como regla general, cuando entre las rentas del sujeto pasivo se computen dividendos o participaciones en beneficios de otras entidades residentes en España se deducirá el 80 por ciento de la cuota íntegra que corresponda a la base imponible derivada de dichos dividendos o participaciones en beneficios.</p></li>
</ol>
<details>
<summary>
</summary>
<div class="FOO callout-tip callout callout-style-simple">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-body-container">
<p>La <strong>respuesta correcta es la a</strong>.</p>
<p>La Cuota Íntegra = Base Imponible x tipo de gravamen (A es correcta).</p>
<p>Exención por Doble Imposición de Dividendos: cuando la participación, directa o indirecta, sea del 5%, o valor de adquisición superior a 20 millones de euros y se cumpla un año de tenencia (+/- 1 año). Se elimina el requisito relativo a que la entidad participada realice actividad económica. (B es correcta).</p>
<p>Los dividendos se integran en la base imponible por su importe bruto. (C es correcta).</p>
<p>Desaparece la deducción para evitar la doble imposición económica interna, incluyéndose en su lugar el método de exención.</p>
<blockquote class="blockquote">
<p>La ley 27/2014, de 27 de noviembre, del Impuesto sobre Sociedades (en vigor desde 1 de enero de 2015) ha introducido en el ordenamiento español importantes novedades en materia tributaria. Entre ellas, destaca la regulación de una nueva exención como método para evitar la doble imposición de dividendos y plusvalías obtenidos de filiales espa- ñolas y la reformulación de la exención aplicable a dividendos y plusvalías de filiales no-residentes (todo ello en un mismo artículo).</p>
</blockquote>
</div>
</div>
</div>
</details>
<hr>
<ol start="78" type="1">
<li>En el caso del cónyuge que no trabaja, las aportaciones a un plan de pensiones realizadas por el cónyuge que sí trabaja:</li>
</ol>
<!-- -->
<ol type="a">
<li><p>Son deducibles fiscalmente en la declaración del cónyuge que no trabaja.</p></li>
<li><p>Son deducibles fiscalmente en la declaración del cónyuge que trabaja.</p></li>
<li><p>Se deducen al 50% entre el cónyuge que trabaja y el que no trabaja.</p></li>
<li><p>Está prohibido realizar aportaciones a un plan que no sea el propio.</p></li>
</ol>
<details>
<summary>
</summary>
<div class="FOO callout-tip callout callout-style-simple">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-body-container">
<p>La <strong>respuesta correcta es la b</strong>.</p>
<p>Las aportaciones a un plan de pensiones realizadas por el cónyuge que sí trabaja serán fiscalmente deducibles en su propia declaración de la renta.</p>
</div>
</div>
</div>
</details>
<hr>
<ol start="79" type="1">
<li>La reducción de la base imponible del ISD en el caso de adquisiciones de empresas familiares…</li>
</ol>
<!-- -->
<ol type="a">
<li><p>Se aplica en idénticas condiciones en los casos de sucesión y en los de donación</p></li>
<li><p>Se aplica en condiciones diferentes en los casos de sucesión y en los de donación</p></li>
<li><p>Se aplica sólo en los casos de sucesión</p></li>
<li><p>Se aplica sólo en los casos de donación</p></li>
</ol>
<details>
<summary>
</summary>
<div class="FOO callout-tip callout callout-style-simple">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-body-container">
<p>La <strong>respuesta correcta es la b</strong>.</p>
<p>La reducción de la base imponible del ISD en el caso de adquisiciones de empresas familiares se aplicara en diferentes condiciones en caso de sucesión o donación.</p>
</div>
</div>
</div>
</details>
<hr>
<ol start="80" type="1">
<li>El banco me ha regalado una tablet al contratar una cuenta corriente, ¿tengo que declararla en el IRPF?</li>
</ol>
<!-- -->
<ol type="a">
<li><p>Sí, se considera un rendimiento del capital mobiliario en especie sometida a una retención del 19%.</p></li>
<li><p>Sí, se considera un rendimiento del capital inmobiliario en especie sometida a una retención del 19%.</p></li>
<li><p>Sí, deberá declararlo en el IRPF por el valor de la entrega aumentado en un 20% el valor de adquisición o el coste de la tablet para la entidad financiera.</p></li>
<li><p>Estará exenta en todos los casos por tratarse de un regalo.</p></li>
</ol>
<details>
<summary>
</summary>
<div class="FOO callout-tip callout callout-style-simple">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-body-container">
<p>La <strong>respuesta correcta es la a</strong>.</p>
<p>A efectos fiscales, la tablet tiene la consideración de <strong>rendimiento del capital mobiliario en especie por lo que, por una parte, quedará sometida a una retención del 19%</strong>, que practicará la entidad financiera y que le cargarán en su cuenta corriente, y, por otra parte, <strong>deberá declararlo en el IRPF por el valor de mercado</strong>. En estos casos se entiende que el valor de mercado es el resultado de aumentar en un 20% el valor de adquisición o el coste de la tablet para la entidad financiera.</p>
<p>En caso de que el contribuyente no obtenga otros rendimientos del capital mobiliario en el ejercicio, la Tablet tributaría al 19%, pues se entiende que su valor no llegaría a los 6.000€.</p>
<p>No obstante, en caso de que se tratara de otro bien más caro, se tributaría según los tramos indicados anteriormente. En caso de que obtuviera en el mismo ejercicio otros rendimientos del capital mobiliario adicionales, se aplicarían idénticos tramos a la suma de todos los rendimientos del capital mobiliario obtenidos.</p>
</div>
</div>
</div>
</details>
<hr>
<ol start="81" type="1">
<li>¿Cuál de las siguientes personas NO podrá aplicarse una reducción por parentesco en la base imponible del impuesto de sucesiones y donaciones?</li>
</ol>
<!-- -->
<ol type="a">
<li><p>Un primo.</p></li>
<li><p>El cónyuge.</p></li>
<li><p>Un tío.</p></li>
<li><p>Un hijo adoptado recientemente.</p></li>
</ol>
<details>
<summary>
</summary>
<div class="FOO callout-tip callout callout-style-simple">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-body-container">
<p>La respuesta <strong>correcta es la a</strong>.</p>
<p>Un primo es un familiar colateral de cuarto grado (1er grado: Sujeto a su padre; 2do grado: padre al abuelo; 3er grado: abuelo al tío; 4to grado: tío al primo). Según la ley del ISD las personas pertenecientes al grupo IV (colaterales de cuarto grado o más y extraños) no tienen derecho a reducción por parentesco. El cónyuge pertenece al grupo II, un tío sería del grupo III y un hijo adoptado será del grupo I o del grupo II dependiendo si es menor de 21 años o no.</p>
</div>
</div>
</div>
</details>
<hr>
<ol start="82" type="1">
<li>¿Cuál es el límite para la exención parcial en la vivienda habitual en el Impuesto sobre el Patrimonio, según la normativa estatal?</li>
</ol>
<!-- -->
<ol type="a">
<li><p>108.182 euros</p></li>
<li><p>150.253 euros</p></li>
<li><p>300.000 euros</p></li>
<li><p>700.000 euros</p></li>
</ol>
<details>
<summary>
</summary>
<div class="FOO callout-tip callout callout-style-simple">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-body-container">
<p>La respuesta <strong>correcta es la c</strong>.</p>
<p>En el Impuesto sobre el Patrimonio (restablecido para los ejercicios 2011 a 2016) se aumentó el mínimo exento por vivienda habitual, pasando de 150.253 euros (veinticinco millones de pesetas) hasta los 300.000 euros.</p>
</div>
</div>
</div>
</details>
<hr>
<ol start="83" type="1">
<li>En una transmisión lucrativa mortis causa, a la cuota tributaria del ISD se le aplica un coeficiente multiplicador que tiene en cuenta (señala la incorrecta):</li>
</ol>
<!-- -->
<ol type="a">
<li><p>La masa hereditaria</p></li>
<li><p>El grado de parentesco con el causante</p></li>
<li><p>El patrimonio preexistente del beneficiario</p></li>
<li><p>Son correctas b) y c)</p></li>
</ol>
<details>
<summary>
</summary>
<div class="FOO callout-tip callout callout-style-simple">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-body-container">
<p>La respuesta <strong>correcta es la a</strong>.</p>
<p>Para obtener la base liquidable del ISD, una vez calculada la masa hereditaria, se puede reducir en función del grado de parentesco que exista con el transmitente. Esta reducción no se aplica en las donaciones (transmisión lucrativa inter vivos).</p>
</div>
</div>
</div>
</details>
<hr>
<ol start="84" type="1">
<li>¿Cuál de las siguientes afirmaciones relativas al Régimen Fiscal de la empresa Familiar NO es correcta?</li>
</ol>
<!-- -->
<ol type="a">
<li><p>El régimen Fiscal de la Empresa Familiar se apoya en incentivos fiscales aplicables en el ISD (reducción del 95% del valor de los bienes afectos) y en el IP (exención sobre dichos bienes afectos).</p></li>
<li><p>Ante una persona física con diversas participaciones en diferentes entidades, el régimen Fiscal de la Empresa Familiar permite su aplicación indistintamente a todas y cada una de las participaciones de forma individual siempre que se cumplan los requisitos establecidos en cada una de ellas.</p></li>
<li><p>El régimen Fiscal de la Empresa Familiar se apoya en incentivos fiscales aplicables principalmente en el IRPF (reducciones en base) y en el IP (bienes exentos).</p></li>
<li><p>Es posible que por aplicación del régimen fiscal de la Empresa Familiar una persona física deba presentar declaración de IP aunque con cuota cero.</p></li>
</ol>
<details>
<summary>
</summary>
<div class="FOO callout-tip callout callout-style-simple">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-body-container">
<p>La respuesta <strong>correcta es la c</strong>.</p>
<p>No hay incentivos fiscales en el IRPF derivados del RF Empresa Familiar. Y el resto de opciones son correctas.</p>
</div>
</div>
</div>
</details>
<hr>
<ol start="85" type="1">
<li>Un hijo quiere ayudar a su padre jubilado con pensión mínima y sin ingresos suficientes. Tiene 45 años y un inmueble alquilado (renta anual por alquiler 15.000 Euros) cuyo valor de mercado es de 200.000 Euros. Decide donar el usufructo temporal por 5 años a su padre de 70 años. ¿Sobre cuánto deberá tributar el padre beneficiario de la donación (donatario)?</li>
</ol>
<!-- -->
<ol type="a">
<li><p>Base liquidable: 20.000 Euros.</p></li>
<li><p>Base liquidable: 20.000 Euros menos la reducción por parentesco que resulte de aplicación.</p></li>
<li><p>Base liquidable: 10.000 Euros.</p></li>
<li><p>El sujeto pasivo es el donante HIJO.</p></li>
</ol>
<details>
<summary>
</summary>
<div class="FOO callout-tip callout callout-style-simple">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-body-container">
<p>La respuesta <strong>correcta es la a</strong>.</p>
<p>La base liquidable será el resultado de aplicar 2% * 5 años = 10% sobre el valor del inmueble. Las reducciones por parentesco en donaciones no aplican y las reglas de cálculo del usufructo temporal no son las mismas que las del cálculo del usufructo vitalicio (89- edad usufructuario).</p>
</div>
</div>
</div>
</details>
<hr>
<ol start="86" type="1">
<li>¿Cuál es la principal diferencia en el IRPF de tener un Rendimiento de Capital (RC) Inmobiliario derivado del alquiler de bienes inmuebles o bien que ello tenga la consideración de Rendimiento de Actividad (RA) Económica?:</li>
</ol>
<!-- -->
<ol type="a">
<li><p>Cuando son RC Inmobiliario existen gastos que son deducibles con un límite y son de aplicación unas reducciones según la naturaleza del inmueble alquilado mientras en RAE económica no es así.</p></li>
<li><p>Siempre y en todo caso los rendimientos provinentes del alquiler de bienes inmuebles generan en el IRPF del perceptor RC Inmobiliario.</p></li>
<li><p>Cuando son RA Económica son de aplicación unas reducciones según la naturaleza del inmueble alquilado y los gastos deducibles lo son sin límite mientras que cuando son RC Inmobiliario no son de aplicación reducciones sobre el rendimiento neto.</p></li>
<li><p>Los RCM se integran en la Base Imponible General (BIG) del IRPF mientras que los RAE se integran en la BIA.</p></li>
</ol>
<details>
<summary>
</summary>
<div class="FOO callout-tip callout callout-style-simple">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-body-container">
<p>La respuesta <strong>correcta es la a</strong>.</p>
<p>La opción b) no es cierta porque si una persona física alquila bienes inmuebles disponiendo de medios mínimos para su gestión (empleado a jornada completa desde 2015) los rendimientos que obtiene son de Actividad Económica y la c) y la d) no son correctas.</p>
</div>
</div>
</div>
</details>
<hr>
<ol start="87" type="1">
<li>La sociedad Vival residente en Marruecos y sin EP en España vendió en marzo del 2018 unas acciones de una sociedad española que cotiza en bolsa por 150.000€ cuando los compró en 1990 por 80.000€. ¿Cuál es la cuota tributaria?</li>
</ol>
<!-- -->
<ol type="a">
<li><p>Cuota tributaria 12.600 €</p></li>
<li><p>Cuota tributaria 13.300 €</p></li>
<li><p>Cuota tributaria 14.700 €</p></li>
<li><p>Cuota tributaria 15.500 €</p></li>
</ol>
<details>
<summary>
</summary>
<div class="FOO callout-tip callout callout-style-simple">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-body-container">
<p>La respuesta <strong>correcta es la b</strong>.</p>
<p>Ganancia patrimonial = 70.000; cuota = (70.000*0,19) = 13.300 euros</p>
</div>
</div>
</div>
</details>
<hr>
<ol start="88" type="1">
<li>El Señor Marqués residente en Francia, ha vendido en el mes de octubre de 2018 acciones de una sociedad española por 10.000€ habiéndolas adquirido en julio del 2001 por 8.000€. ¿Cómo tributan en España?</li>
</ol>
<!-- -->
<ol type="a">
<li><p>Los intereses o ganancias patrimoniales derivados de la transmisión de acciones que correspondan a personas físicas o entidades con la residencia habitual en estados miembros de la UE y que no operen en España por medio de EP están exentos.</p></li>
<li><p>Podrá aplicar los coeficientes de abatimiento y no tributará por ello.</p></li>
<li><p>Tributará al tipo general de gravamen del 24%.</p></li>
<li><p>Tributará al tipo general de las ganancias patrimoniales del 14%, 21%, 23%, por haberse generado la plusvalía en un periodo superior al año.</p></li>
</ol>
<details>
<summary>
</summary>
<div class="FOO callout-tip callout callout-style-simple">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-body-container">
<p>La respuesta <strong>correcta es la a</strong>.</p>
<p>Los intereses o ganancias patrimoniales derivados de la transmisión de acciones que correspondan a personas físicas o entidades con la residencia habitual en estados miembros de la UE y que no operen en España por medio de EP están exentos. Precisamente ese es el caso de las rentas exentas del IRNR.</p>
</div>
</div>
</div>
</details>
<hr>
<ol start="89" type="1">
<li>En cuanto al IRNR, ¿Cuál de las siguientes afirmaciones es correcta?</li>
</ol>
<!-- -->
<ol type="a">
<li><p>Se considera residente aquella persona física que permanezca más de 183 días durante el año natural en territorio español, y por ende, se le aplicará el régimen de IRNR.</p></li>
<li><p>Las personas jurídicas que tengan su domicilio social en España pero que obtengan más del 50% de sus ingresos de terceros países se les aplica el régimen de IRNR.</p></li>
<li><p>Los intereses y ganancias patrimoniales derivados de deuda pública obtenidos por personas físicas o jurídicas no residentes y que no operan en España por medio de un establecimiento permanente (EP), forman parte de las rentas exentas en el IRNR.</p></li>
<li><p>Cuando un no residente obtiene rentas sin mediación de establecimiento permanente (EP), hace una declaración única, la cual puede dar lugar a compensaciones entre rentas o ganancias patrimoniales positivas con las negativas.</p></li>
</ol>
<details>
<summary>
</summary>
<div class="FOO callout-tip callout callout-style-simple">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-body-container">
<p>La respuesta <strong>correcta es la c</strong>.</p>
<p>Los intereses y ganancias patrimoniales derivados de la Deuda Pública obtenidos por personas físicas o jurídicas no residentes y que no operen en España por medio de EP, tienen la consideración de rentas exentas del IRNR. Las demás afirmaciones son incorrectas.</p>
</div>
</div>
</div>
</details>
<hr>
<ol start="90" type="1">
<li>En el IRNR el representante es obligatorio cuando:</li>
</ol>
<!-- -->
<ol type="a">
<li><p>El no residente opere por medio de EP.</p></li>
<li><p>El no residente realice actividades o explotaciones económicas en España sin mediación de EP.</p></li>
<li><p>Se trate de entidades en régimen de atribución de rentas constituidas en el extranjero con presencia en territorio español.</p></li>
<li><p>Es obligatorio en todos los casos indicados.</p></li>
</ol>
<details>
<summary>
</summary>
<div class="FOO callout-tip callout callout-style-simple">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-body-container">
<p>La respuesta <strong>correcta es la d</strong>.</p>
<p>El representante es obligatorio cuando:</p>
<ol type="1">
<li><p>El no residente opere por medio de EP (Establecimiento permanente).</p></li>
<li><p>El no residente realice actividades o explotaciones económicas en España sin mediación de EP.</p></li>
<li><p>Se trate de entidades en régimen de atribución de rentas constituidas en el extranjero con presencia en territorio español.</p></li>
<li><p>Cuando así lo requiera la Administración tributaria. También se puede nombrar de forma voluntaria.</p></li>
</ol>
</div>
</div>
</div>
</details>
<hr>
<ol start="91" type="1">
<li>¿Cuál es el tipo de gravamen especial sobre bienes inmuebles de entidades no residentes?</li>
</ol>
<!-- -->
<ol type="a">
<li><p>19%</p></li>
<li><p>20%</p></li>
<li><p>24%</p></li>
<li><p>Ninguno de los anteriores.</p></li>
</ol>
<details>
<summary>
</summary>
<div class="FOO callout-tip callout callout-style-simple">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-body-container">
<p>La respuesta <strong>correcta es la d</strong>.</p>
<p>Las entidades No Residentes que sean propietarias o posean en España bienes inmuebles o derechos reales de goce o disfrute sobre éstos, estarán sujetas al impuesto mediante un gravamen especial del 3%. (La transmisión de bienes inmuebles situados en territorio español: (En las ventas de inmuebles hechas por no residentes, el comprador tendrá que (retener el tipo del 3% sobre el importe de la venta en todo caso).</p>
<p>La persona que adquiere el inmueble, sea o no residente, está obligada a retener e ingresar en el Tesoro Público el 3% de la contraprestación acordada.</p>
<p>Esta retención tiene para el vendedor el carácter de pago a cuenta del impuesto que corresponda por la ganancia derivada de la transmisión.</p>
</div>
</div>
</div>
</details>
<hr>
<ol start="92" type="1">
<li>¿Qué rentas están exentas en el IRNR si se obtienen sin mediación de EP (Establecimiento Permanente)?</li>
</ol>
<!-- -->
<ol type="a">
<li><p>Las que estén exentas en el IRPF</p></li>
<li><p>Los intereses de la Deuda Pública</p></li>
<li><p>Las ganancias derivadas de la Deuda Pública</p></li>
<li><p>Todas las respuestas anteriores son correctas</p></li>
</ol>
<details>
<summary>
</summary>
<div class="FOO callout-tip callout callout-style-simple">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-body-container">
<p>La respuesta <strong>correcta es la d</strong>.</p>
<p>Las rentas exentas, y siempre sin mediación de EP, son:</p>
<ol type="1">
<li><p>Las rentas exentas en el IRPF.</p></li>
<li><p>Los intereses o ganancias patrimoniales derivados de bienes muebles obtenidos por residentes en otro estado miembro de la UE.</p></li>
<li><p>Los intereses y ganancias patrimoniales derivados de la Deuda Pública.</p></li>
<li><p>Los rendimientos de capital mobiliario y ganancias patrimoniales derivadas de valores emitidos en España por no residentes.</p></li>
<li><p>Los rendimientos de cuentas de no residentes.</p></li>
<li><p>Los beneficios distribuidos por las sociedades filiales a sus matrices situadas en la UE.</p></li>
<li><p>Las rentas derivadas de la transmisión de valores o el reembolso de participaciones en fondos (de inversión realizadas en un mercado secundario.</p></li>
<li><p>Las becas y otras cantidades.</p></li>
</ol>
</div>
</div>
</div>
</details>
<hr>
<ol start="93" type="1">
<li>Un inversor ruso, residente en Grecia, adquirió, en abril de 2018, un Bono del Estado Español a cinco años que paga cupones anuales del 2% cada 31 de mayo. ¿Cómo tributará en España?</li>
</ol>
<!-- -->
<ol type="a">
<li><p>A la escala de gravamen progresiva del IRPF</p></li>
<li><p>Al tipo general de los rendimientos del 24%.</p></li>
<li><p>Al tipo general de las ganancias del 21%.</p></li>
<li><p>Estará exento</p></li>
</ol>
<details>
<summary>
</summary>
<div class="FOO callout-tip callout callout-style-simple">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-body-container">
<p>La respuesta <strong>correcta es la d</strong>.</p>
<p>Estará exento porque los cupones de Deuda pública obtenidos por personas físicas o jurídicas no residentes y que no operan en España por medio de Establecimiento Permanente están exentos en el IRNR.</p>
</div>
</div>
</div>
</details>
<hr>
<ol start="94" type="1">
<li>¿Qué rentas NO están exentas en el IRNR si se obtienen sin mediación de EP (Establecimiento Permanente)?</li>
</ol>
<!-- -->
<ol type="a">
<li><p>Becas y otras cantidades</p></li>
<li><p>Intereses de la Deuda Pública</p></li>
<li><p>Rendimientos de cuentas de no residentes</p></li>
<li><p>Todas las respuestas anteriores están exentas.</p></li>
</ol>
<details>
<summary>
</summary>
<div class="FOO callout-tip callout callout-style-simple">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-body-container">
<p>La respuesta <strong>correcta es la d</strong>.</p>
<p>Las rentas exentas, y siempre sin mediación de EP, son:</p>
<ol type="1">
<li><p>Las rentas exentas en el IRPF.</p></li>
<li><p>Los intereses o ganancias patrimoniales derivados de bienes muebles obtenidos por residentes (en otro estado miembro de la UE.</p></li>
<li><p>Los intereses y ganancias patrimoniales derivados de la Deuda Pública.</p></li>
<li><p>Los rendimientos de capital mobiliario y ganancias patrimoniales derivadas de valores emitidos en España por no residentes.</p></li>
<li><p>Los rendimientos de cuentas de no residentes.</p></li>
<li><p>Los beneficios distribuidos por las sociedades filiales a sus matrices situadas en la UE.</p></li>
<li><p>Las rentas derivadas de la transmisión de valores o el reembolso de participaciones en fondos (de inversión realizadas en un mercado secundario.</p></li>
<li><p>Las becas y otras cantidades.</p></li>
</ol>
</div>
</div>
</div>
</details>
<hr>
<ol start="95" type="1">
<li>Una persona física residente en Alemania dispone de una vivienda de uso propio en Mallorca. ¿Tiene algún tipo de implicación fiscal en territorio español?:</li>
</ol>
<!-- -->
<ol type="a">
<li><p>Deberá declarar por el IRNR la imputación de rentas inmobiliarias igual que cualquier residente en su IRPF.</p></li>
<li><p>Ninguna dado que no obtiene Rentas en territorio español y el IRNR no aplicaría</p></li>
<li><p>Únicamente quedaría obligada a satisfacer el IBI como cualquier residente.</p></li>
<li><p>Debería tributar por el IRNR considerándose que obtiene rendimientos a través de un Establecimiento Permanente (EP) con motivo del inmueble radicado en territorio español.</p></li>
</ol>
<details>
<summary>
</summary>
<div class="FOO callout-tip callout callout-style-simple">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-body-container">
<p>La respuesta <strong>correcta es la a</strong>.</p>
<p>Deberá declarar por el IRNR la imputación de rentas inmobiliarias igual que cualquier residente en su IRPF.</p>
</div>
</div>
</div>
</details>
<hr>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copiado");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copiado");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./M7-test.html" class="pagination-link">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text">Módulo 7</span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./M9-test.html" class="pagination-link">
        <span class="nav-page-text">Módulo 9</span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->



</body></html>